### DISCUSSION TITLE
Should we default to only inject chaos into `Running` pods?

### DISCUSSION THREAD

**Discussion by STRRL** [chaos-mesh/chaos-mesh#1488] [Ideas]
As https://github.com/chaos-mesh/chaos-mesh/issues/1435 mentions, chaos experiments failed because of trying to inject chaos into `Pending` Pod.

It's very easy for re-producing on one-node minikube cluster:

```yaml
---
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: 263-cpu.yaml
  namespace: chaos-testing
spec:
  duration: 20s
  mode: all
  scheduler:
    cron: '@every 30s'
  selector:
    # podPhaseSelectors:
    # - Running
    labelSelectors:
      app: web-show
    namespaces:
    - default
  stressors:
    cpu:
      load: 20
      workers: 1
  value: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-show
  labels:
    app: web-show
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-show
  template:
    metadata:
      labels:
        app: web-show
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: web-show
      containers:
        - name: web-show
          image: pingcap/web-show
          imagePullPolicy: Always
          command:
            - /usr/local/bin/web-show
            - --target-ip=1.1.1.1
          ports:
            - name: web-port
              containerPort: 8081
```

Most implementations of chaos are based on a running container, it requires that Pod must be in `Running` status. And we already have a "PodPhaseSelector", I think what we should do is appending this selector for some of the chaos mutating webhook.

Should we do that?
