### DISCUSSION TITLE
Update chaosmesh

### DISCUSSION THREAD

**Discussion by Muscule** [chaos-mesh/chaos-mesh#2065] [Q&A]
Can I update the chaosmesh on openshift or kubernetes with the help of helm?

**Comment by Muscule** [comment]
Or is it enogh just to pull new images?

**Comment by YangKeao** [comment]
Updating the chaos-mesh from `1.x` to `1.x` with `helm` is fine and everything should work.

Updating the chaos-mesh from `1.x` to `2.0` will make the `.spec.scheduler` field doesn't work, because it's replaced by `Schedule` object in `2.0`. For example, the object:

```
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: xxx
spec:
  action: "pod-kill"
  mode: one
  selector:
    labelSelectors:
      "app.kubernetes.io/component": "tikv"
  scheduler:
    cron: "@every 1h"
```

Should be replaced by:

```
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: schedule-pod-kill-example
spec:
  schedule: "@every 1h"
  type: "PodChaos"
  historyLimit: 5
  concurrencyPolicy: Forbid
  podChaos:
    action: "pod-kill"
    mode: one
    selector:
      labelSelectors:
        "app.kubernetes.io/component": "tikv"
```

We have also developed a migration tool in `./tools/schedule-migration`, and the document of it is in reviewing stage :beers: .
