### DISCUSSION TITLE
Is there a way to create a Schedule object with labels that carry on with the PodChaos objects it creates?

### DISCUSSION THREAD

**Discussion by adamjk-dev** [chaos-mesh/chaos-mesh#2485] [Q&A] [answered]
For instance, I want to add metadata and labels to my schedule objects so I can identify and clean them up easily later (say with an ID I recognize). But, I also want to tag the PodChaos objects it creates under the hood with those same labels.

I was trying to use spec.metadata.labels to have it carry on, but wasn't having success just yet.

Any help would be greatly appreciated, thanks!

**Comment by adamjk-dev** [comment]
For instance, I was hoping something like this, but the metadata.labels don't carry forward on the PodChaos objects created:

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: pod-kill-schedule-demo
  namespace: templab
  labels:
    app_cmdb_id: "A0000001"
spec:
  schedule: "@every 30s"
  metadata:
    labels:
      app_cmdb_id: "A0000001"
  historyLimit: 10
  concurrencyPolicy: 'Forbid'
  type: 'PodChaos'
  podChaos:
    metadata:
      labels:
        app_cmdb_id: "A0000001"
    action: pod-kill
    mode: one
    duration: '10s'
    selector:
      labelSelectors:
        'app': 'nginx-demo'
```

The objects created from the YAML above:
```
⇒  oc get schedule,podchaos,po -n templab --show-labels
NAME                                             AGE   LABELS
schedule.chaos-mesh.org/pod-kill-schedule-demo   32s   app_cmdb_id=A0000001

NAME                                                   AGE   LABELS
podchaos.chaos-mesh.org/pod-kill-schedule-demo-486rb   3s    managed-by=pod-kill-schedule-demo
podchaos.chaos-mesh.org/pod-kill-schedule-demo-p98wp   3s    managed-by=pod-kill-schedule-demo

NAME                              READY   STATUS              RESTARTS   AGE   LABELS
pod/nginx-demo-677f4fc6c7-92jmd   0/1     ContainerCreating   0          3s    app=nginx-demo,pod-template-hash=677f4fc6c7
pod/nginx-demo-677f4fc6c7-9xrgw   0/1     ContainerCreating   0          3s    app=nginx-demo,pod-template-hash=677f4fc6c7
```

The goal would be to have the podchaos objects also have a label of app_cmdb_id=A0000001, so one could identify all created objects with one command and do cleanup.
