### DISCUSSION TITLE
fix vauth.kb.io webhook, to use the plural form of resource name instead of singular.

### DISCUSSION THREAD

**Discussion by kishoregv** [chaos-mesh/chaos-mesh#3608] [Q&A]
## Bug Report

**What version of Kubernetes are you using?**
1.22

**What version of Chaos Mesh are you using?**
v2.1.2

**What did you do?**
We need to have an explicit list of resource name in the cluster role where we grant the permissions to the users, like below. 
```
- apiGroups:
  - chaos-mesh.org
  resources:
  - podhttpchaos
  - schedules
  - jvmchaos
  - gcpchaos
  - kernelchaos
  - podchaos
  - podiochaos
  - networkchaos
  - workflownodes
  - timechaos
  - podnetworkchaos
  - httpchaos
  - iochaos
  - physicalmachines
  - stresschaos
  - workflows
  - awschaos
  - dnschaos
  - physicalmachinechaos
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
```

and apply a workflow object we get an error

**What did you expect to see?**
I should have seen the resource created message.

On investigating the code base it seems like, the auth webhook is making a SubjectAccessReview on singular for of the resource when it should have been making on plural form of the resource
```
cat << EOF | kubectl create -f - -o json
apiVersion: authorization.k8s.io/v1
kind: SubjectAccessReview
metadata:
  creationTimestamp: null
spec:
  resourceAttributes:
    group: "chaos-mesh.org"
    resource: workflows
    namespace: ""
    verb: create
  user: "xyz"
EOF
```

**What did you see instead?**
Error from server (xyz is forbidden on cluster): error when creating "workflowserial.yaml": admission webhook "vauth.kb.io" denied the request: xyz is forbidden on cluster
**Output of chaosctl**

**Comment by kishoregv** [comment]
This is an issue on the resource which a different plural form than singular form.
physicalmachines, schedules, workflows and workflownodes are the once hit by this bug.

**Comment by STRRL** [comment]
Hi @kishoregv, I could not reproduce the issue  on my local environment, chaos mesh 2.3.0, kubernetes 1.24.3:

I use helm to install Chaos Mesh 2.3.0, then create these resources:

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: could-only-get-list-workflows
  namespace: default
rules:
- apiGroups:
  - chaos-mesh.org
  resources:
  - workflows
  verbs:
  - get
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adhoc-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: adhoc-sa-could-get-list-workflow
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: could-only-get-list-workflows
subjects:
- kind: ServiceAccount
  name: adhoc-sa
  namespace: default
```


Then I execute:


```
  ~/playground/github/chaos-mesh/chaos-mesh on   integrate-with-helm ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✘ INT  system  1.18.3 at ⎈ minikube at  20:42:21
❯ k auth can-i get workflow --as system:serviceaccount:default:adhoc-sa                
yes
  ~/playground/github/chaos-mesh/chaos-mesh on   integrate-with-helm ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────  system  1.18.3 at ⎈ minikube at  20:42:23
❯ k auth can-i get workflows --as system:serviceaccount:default:adhoc-sa    
yes

```

With both plural / singular resource names, I could get the `yes` response.
