### DISCUSSION TITLE
open the `mount_only` option to the user for IO fault injection

### DISCUSSION THREAD

**Discussion by track87** [chaos-mesh/chaos-mesh#3831] [Ideas]
# Topic
IO fault injection tool `toda` provides the `mount_only` option. After the `mount_only` option is enabled, faults take effect only for newly opened file handles. This option is important in a production environment because of business concerns about the risk to the business of `ptrace` replacement.

# Expection
I would like to declare `IOChaos` with an entry that specifies the mount_only option so that you can customize the behavior of `toda `from a user perspective, for example:

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-latency-example
  namespace: chaos-mesh
spec:
  action: latency
  mode: one
  selector:
    labelSelectors:
      app: etcd
  volumePath: /var/run/etcd
  path: '/var/run/etcd/**/*'
  mount_only: false
  delay: '100ms'
  percent: 50
  duration: '400s'
```
`mount_only might be replaced with a more readable word?`
