### DISCUSSION TITLE
Close active connections during NetworkChaos resource is applied

### DISCUSSION THREAD

**Discussion by partemyeva** [chaos-mesh/chaos-mesh#3864] [Q&A]
Hello,

We are using Kubernetes version 1.22.6 and chaos-mesh version 2.4.1.

We'd like to use NetworkChaos with partition action in negative autotests.

Our scenario is the following:
1. Redis client create resource lock in Redis service pod
2. Apply NetworkChaos resource for all Redis service pods:
```
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: test-redis-partition
  namespace: test
spec:
  action: partition
  direction: to
  mode: all
  selector:
    labelSelectors:
      app.kubernetes.io/name: test-redis
    namespaces:
    - test
```
3. Wait NetworkChaos resource AllInjected status is true
4. Execute in Redis service pod a command to list client connections (https://redis.io/commands/client-list/):
![image](https://user-images.githubusercontent.com/44258087/207368346-41309720-0f46-4d29-aba9-0e4073a5a2b8.png)

New connections to Redis could not be established, but existing connections are still workable.

Is it possible to close active connections during network partition chaos is applied? May be created resource should contain some additional fields?
