### DISCUSSION TITLE
Is there an option to make a schedule object to create experiments every 10 seconds ?

### DISCUSSION THREAD

**Discussion by Dorsosiv** [chaos-mesh/chaos-mesh#3881] [Ideas]
Hey, I want to create a schedule that will create experiment every 10 seconds . 

The experiment is pod kill.

**Comment by fewdan** [comment]
@Dorsosiv 
You can refer to [it](https://github.com/chaos-mesh/chaos-mesh/blob/master/examples/schedule-podchaos.yaml).
It probably likes this:
```
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: schedule-pod-kill-example
spec:
  schedule: "@every 10s"
  type: "PodChaos"
  historyLimit: 5
  concurrencyPolicy: Forbid
  podChaos:
    action: "pod-kill"
    mode: one
    selector:
      labelSelectors:
        "app.kubernetes.io/component": "tikv"
```
