### DISCUSSION TITLE
Google OAuth enabled but user can create Chaos experiments even if he doesn't have access to GCP itself

### DISCUSSION THREAD

**Discussion by himeshkothari** [chaos-mesh/chaos-mesh#3896] [Q&A]
I have added a user account in below 

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaos-mesh-cluster-manager
rules:
  - apiGroups:
      - chaos-mesh.org
    resources: ['*']
    verbs: ['get', 'list', 'watch', 'create', 'delete', 'patch', 'update']
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-manager-binding
  namespace: chaos-mesh
subjects:
  - kind: User
    name: example@gmail.com
roleRef:
  kind: ClusterRole
  name: chaos-mesh-cluster-manager
  apiGroup: rbac.authorization.k8s.io
```

but example@gmail.com is not added to the GCP where my cluster (in which Chaos Mesh) and my apps are deployed. But user is still authenticated to the Chaos Dashboard and is able to create experiments
