### DISCUSSION TITLE
Operating Network fault (partition) - No difference between from/to/both

### DISCUSSION THREAD

**Discussion by ardole** [chaos-mesh/chaos-mesh#4044] [Q&A]
Hi community,

I've a question about the network faults scenarios. I would like to drop traffic from one pod to another within the same namespace.
I'm starting from here in the documentation: https://chaos-mesh.org/docs/simulate-network-chaos-on-kubernetes/#partition-example

- Giving two pods (**pod-1**, **pod-2**)
- When I try to block traffic from pod-1 to pod-2 with
```yaml
kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-mesh
  name: chaos1
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - test
    labelSelectors:
      app: pod-1
  direction: to
  target:
    selector:
      namespaces:
        - test
      labelSelectors:
        app: pod-2
    mode: all
```
- Then both traffic from/to pod1/pod2 are blocked, not only from pod1.
- When I try to block traffic from pod-2 to pod-1 with `direction: from`
- Then both traffic from/to pod1/pod2 are blocked, not only from pod2.
- Same thing with `direction: both`

My questions are:

- Is my understand of partition to/from good ?
- If no, what am i doing wrong ?
- If yes, should i raise a ticket ?

I'm running with this context:
- Azure AKS
- Kube v1.24.9
- Network Type: Azure CNI
- Chaos mesh helm chart 2.5.2

Thanks for your help

Best regards,
Arnaud
