### DISCUSSION TITLE
support for Cilium/DPv2 - enable NetworkChaos with the use of eBPF

### DISCUSSION THREAD

**Discussion by hoozgomk** [chaos-mesh/chaos-mesh#4131] [Ideas]
## Feature Request

**Is your feature request related to a problem? Please describe:**
I'm working on emulating various types of incidents on services running on Kubernetes.
I'm using the Chaos Mesh as it provides me the multiple possibilities to inject issues into the pods and it works great with Netem.

I see that the eBPF standard is becoming very popular nowadays and I'm seeing the lack of support for eBPF while emulating Network Issues as a noticeable flaw.

**Describe the feature you'd like:**
Provide support for emulating NetworkChaos on the k8s clusters with eBPF.

**Comment by STRRL** [comment]
Thanks @hoozgomk! We would consider that.


Chaos Mesh NetworkChaos builds the features based on Kubernetes Pod Networking Standard, it means no matter which CNI is used in the Kubernetes cluster, Chaos Mesh could always make the effect.

eBPF is a powerful way to leverage the user space modification for the linux kernel, but I do not realize what thing or which kind of certain experiment could be done by eBPF. Would you give us some examples? :heart:

**Reply by hoozgomk** [reply]
Hello,

Thank you for the reply.
In my experiment setup, I'm using Linkerd as a service mesh to monitor the L7 traffic between the services. 
Based on my tests, I noticed that network failure simulation using Chaos Mesh packet loss scenario works correctly with Linkerd. Injecting the fault makes the effect, I can clearly see it when monitoring the metrics, such as request rate.

I started this topic because when I started to work with Cilium, I noticed that network failures don't take effect there. (pod failures and other scenarios work correctly though).
I assumed that this is because of the different methods of how the traffic is proxied between the services with these two technologies. Based on what you are saying this should work here too, but I didn't make it to work yet.

So maybe this ticket shouldn't be a feature request but configuration support.

The example of the scenario which works correctly with Linkerd and doesn't work with Cilium is:

```
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: loss-js
  namespace: default
spec:
  action: loss
  mode: all
  selector:
    labelSelectors:
      name: "js-client"
  loss:
    loss: "75"
    correlation: "75"
  direction: to
  target:
    selector:
      namespaces:
        - 'default'
    mode: all
```

I can provide more details about the cluster, services, chaos mesh and service mesh configuration.
Any support will be appreciated.

Kind regards,
