### DISCUSSION TITLE
Chaos test in zones

### DISCUSSION THREAD

**Discussion by artur-akh** [chaos-mesh/chaos-mesh#4135] [Q&A]
How to make a similar config in the form of a yaml manifest, we are interested in randomly choosing a zone for a chaos test?
```
$zone=(Get-Random -InputObject ('zone-1a', 'zone-1b', 'zone-1c'))
Write-Output 'zone = ', $zone
@"
kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: grafana-mimir
  name: chaos-test-mimir-kill
spec:
  selector:
    namespaces:
      - grafana-mimir
    labelSelectors:
      app.kubernetes.io/name: mimir
    nodeSelectors:
      topology.kubernetes.io/zone: $zone
    podPhaseSelectors:
      - 'Running'
  mode: all
  action: pod-kill
"@ | kubectl apply -f -
```
