### DISCUSSION TITLE
PhysicalMachineChaos 404 page not found : HTTP status is not OK

### DISCUSSION THREAD

**Discussion by wrdls** [chaos-mesh/chaos-mesh#4230] [Q&A]
Asked on Slack as well: https://cloud-native.slack.com/archives/C0193VAV272/p1697201701943849

I installed chaos-mesh (2.6.2) with Helm in GKE (v1.24.14-gke.2700). I enabled the chaos-daemon daemonset to stress the nodes.
However I can't get PhysicalMachineChaos to work. I want to run the following where the addresses are the IPs of the chaos-daemon pods in Kubernetes:

```yaml
kind: PhysicalMachineChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-mesh
  name: mp60-1697201462
spec:
  action: stress-cpu
  address:
    - http://172.29.3.48:31766
    - http://172.29.4.132:31766
  selector: {}
  mode: all
  stress-cpu:
    load: 60
    workers: 1
  duration: 200s
```

I get the following error:
```
Failed to apply chaos: 404 page not found : HTTP status is not OK
```
I tried port `31767` as well but that returns
```
Failed to apply chaos: : Post "http://172.29.7.64:31767/api/attack/stress": EOF
```
(which makes sense since 31767  is listed as a GRPC port so HTTP should not work)
