### DISCUSSION TITLE
Are "wildcard" selectors supported?

### DISCUSSION THREAD

**Discussion by timflannagan** [chaos-mesh/chaos-mesh#4386] [Q&A]
When configuring a PodChaos, NetworkChaos, etc. custom resource, I would like the ability to use a wildcard in the selector. For example, I deployed the same application across N namespaces that are all prefixed with the "ns-" (e.g. ns-1, ns-2, etc.) naming convention. In order to test this scenario, I would need to explicitly configure each namespace directly:

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: ns-pod-restart
  namespace: test
spec:
  action: pod-kill
  mode: all
  selector:
    namespaces:
    - ns-1
    - ns-2
    - ns-3
    - ...
    - ns-N
    annotationSelectors:
      app.kubernetes.io/name: "<...>"
```

Being able to use a wildcard matcher in the namespace field would help cut down on the overall YAML configuration, but also provide a better UX in the case where we can't statically configure the list of namespaces correctly:

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: ns-pod-restart
  namespace: test
spec:
  action: pod-kill
  mode: all
  selector:
    namespaces:
    - ns-*          # <--- prefix matcher; apply to any namespace prefixed with "ns-"
    - *                # <--- regex matcher; apply to all namespaces
    - *-ns.         # <--- suffix matcher; apply to any namespace that has the "-ns" suffix
    annotationSelectors:
      app.kubernetes.io/name: "<...>"
```
