### DISCUSSION TITLE
Unable to Expose Dashboard Due to Endpoints Not Being Found

### DISCUSSION THREAD

**Discussion by natenberenstein** [chaos-mesh/chaos-mesh#4463] [Q&A] [answered]
# Environment
- k3s (v1.30.2+k3s1)
- chaos-mesh (helm | v2.6.3)
- traefik controller (v2.10)

# Problem
Installed Chaos-Mesh using Helm.  The following is my values.yaml configuration:
```yaml
chaos-daemon:
  runtime: containerd
  socketPath: /run/k3s/containerd/containerd.sock

dashboard:
  securityMode: false
  ingress:
    enabled: true
    hosts:
      - name: chaos-mesh.test.com
```
Though the resources are deployed successfully, I'm unable to view my dashboard.  This is the error I see in my Traefik logs:
```
time="2024-07-31T23:12:24Z" level=error msg="Cannot create service: endpoints not found" servicePort="&ServiceBackendPort{Name:,Number:2333,}" ingress=ingress-chaos-dashboard namespace=chaos-mesh serviceName=chaos-dashboard providerName=kubernetes

time="2024-07-31T23:12:24Z" level=error msg="Cannot create service: endpoints not found" providerName=kubernetes servicePort="&ServiceBackendPort{Name:,Number:2333,}" serviceName=chaos-dashboard ingress=ingress-chaos-dashboard namespace=chaos-mesh

time="2024-07-31T23:12:24Z" level=error msg="Cannot create service: endpoints not found" ingress=ingress-chaos-dashboard serviceName=chaos-dashboard providerName=kubernetes servicePort="&ServiceBackendPort{Name:,Number:2333,}" namespace=chaos-mesh

time="2024-07-31T23:12:24Z" level=error msg="Cannot create service: endpoints not found" servicePort="&ServiceBackendPort{Name:,Number:2333,}" providerName=kubernetes namespace=chaos-mesh ingress=ingress-chaos-dashboard serviceName=chaos-dashboard

time="2024-07-31T23:12:24Z" level=error msg="Cannot create service: endpoints not found" providerName=kubernetes servicePort="&ServiceBackendPort{Name:http,Number:0,}" ingress=chaos-dashboard namespace=chaos-mesh serviceName=chaos-dashboard

time="2024-07-31T23:12:24Z" level=error msg="Cannot create service: endpoints not found" serviceName=chaos-dashboard servicePort="&ServiceBackendPort{Name:,Number:2333,}" providerName=kubernetes ingress=ingress-chaos-dashboard namespace=chaos-mesh

time="2024-07-31T23:12:46Z" level=error msg="Cannot create service: endpoints not found" servicePort="&ServiceBackendPort{Name:http,Number:0,}" providerName=kubernetes ingress=chaos-dashboard namespace=chaos-mesh serviceName=chaos-dashboard
```

# Discussion
I'm not exactly sure what the issue is.  I'm able to view the dashboard if I port forward the `chaos-dashboard` service, but won't work with ingress.  Could also be related to chaos-mesh supporting Kubernetes only till v1.28, but my current k3s version is v1.30.  With all said, what do you think could be the issue?

**Comment by natenberenstein** [comment, marked as answer]
Got this to work by adding the following annotations to `dashboard.service.annotations`:
```yaml
chaosDaemon:
  runtime: containerd
  socketPath: /run/k3s/containerd/containerd.sock

dashboard:
  securityMode: false
  service:
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
  ingress:
    enabled: true
    hosts:
      - name: chaos-mesh.test.com
```
