### DISCUSSION TITLE
Do ongoing experiments apply to new pods?

### DISCUSSION THREAD

**Discussion by savoie** [chaos-mesh/chaos-mesh#4479] [Q&A] [answered]
```
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
spec:
  action: partition
  direction: both
  mode: all
  selector:
    nodeSelectors:
      topology.kubernetes.io/zone: us-central1-a
    podPhaseSelectors:
    - Running
    - Pending
```

We have been trying to simulate a region outage by creating a network partition targeting all pods in a zone. I'd expect that when new pods come up matching the selectors, the chaos-mesh controller would target them as well, but we've found that new pods aren't affected by the networkchaos. Is this the intended behaviour or are we messing something up on our end? I haven't been able to find any docs that confirm/deny that chaos-mesh is intended to enforce experiments using a control loop.
