### DISCUSSION TITLE
Is it possible to inject an HTTP status code using HTTPChaos?

### DISCUSSION THREAD

**Discussion by s-cho-25** [chaos-mesh/chaos-mesh#4705] [Q&A]
Chaos Mesh version: 2.7.2

I use this way to inject:

```
apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: inject-500-errors
  namespace: chaos-mesh
spec:
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app.kubernetes.io/instance: "app"
  target: Request
  port: 3000
  path: /
  method: GET
  abort: true
  code: 500
  duration: 5m
```

But the status showed inject failed:

```
kubectl describe httpchaos inject-500-errors -n chaos-mesh

...
Status:
  Conditions:
    Status:  True
    Type:    Selected
    Status:  False
    Type:    AllInjected
    Status:  True
    Type:    AllRecovered
    Status:  False
    Type:    Paused
```

And the app's service is still accessible with a 200 status code during the injection period.
