### ISSUE TITLE
Add e2e test for external network delay

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#1047]
There is no e2e test and documents for external network delay and partition now :facepalm: .

The e2e test could be found in `/test/e2e/chaos/basic.go`. Reading other tests in that file could help accomplish this issue. 

```
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-netem-example
  namespace: chaos-testing
spec:
  action: netem
  mode: one
  selector:
    labelSelectors:
      "app.kubernetes.io/component": "tikv"
  delay:
    latency: "90ms"
    correlation: "25"
    jitter: "90ms"
  loss:
    loss: "25"
    correlation: "25"
  direction: to
  target:
    selector:
      labelSelectors:
        "app.kubernetes.io/component": "tikv"
    mode: one
  duration: "10s"
  scheduler:
    cron: "@every 15s"
```
