### ISSUE TITLE
admission webhook "vpodnetworkchaos.kb.io" denied the request: rpc error: code = Unknown desc = expected docker:// but got container

### ISSUE THREAD

**Issue by jasonstack** [chaos-mesh/chaos-mesh#1132]
## Bug Report

**What version of Kubernetes are you using?**
* Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
* Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**
Apply `NetworkChaos`, `IOChaos`, `StressChaos` on local cluster created by helm charts; but `PodChaos` works fine for me.

```
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: etcd-network-partition
  namespace: chaos-testing
spec:
  action: partition
  mode: one
  selector:
    namespaces:
      - "my-cluster-dev"
    fieldSelectors:
      "status.phase": "Running"
    labelSelectors:
      "app.kubernetes.io/name": "my-cluster"  
  direction: both
  target:
    selector:
      namespaces:
        - "my-cluster"
      labelSelectors:
        "app.kubernetes.io/name": "etcd"
    mode: one
  duration: "10s"
  scheduler:
    cron: "@every 15s"
```

**What did you expect to see?**
`NetworkChaos` being applied

**What did you see instead?**
From dashboard: `admission webhook "vpodnetworkchaos.kb.io" denied the request: rpc error: code = Unknown desc = expected docker:// but got container`
