### ISSUE TITLE
with StressChaos Experiment, an error occurred: rpc error: code = Unavailable desc = connection closed

### ISSUE THREAD

**Issue by gotoworld** [chaos-mesh/chaos-mesh#1134]
## Bug Report

**What version of Kubernetes are you using?**
Kubernetes V1.18

**What did you do?**
Try to do stresschoas experiment, but what i got as below.
"an error occurred: rpc error: code = Unavailable desc = connection closed"

the stresschaos.yaml 
```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: burn-cpu
  namespace: chaos-testing
spec:
  mode: one
  selector:
    namespaces:
      - "basicservice"
  stressors:
    cpu:
      workers: 1
  duration: "30s"
  scheduler:
    cron: "@every 3m"
```

**What did you expect to see?**

it working with the Pod cpu is burning

**What did you see instead?**
![image](https://user-images.githubusercontent.com/8605471/97871279-398b8980-1d4f-11eb-95f2-f79cdd75b6a6.png)
