### ISSUE TITLE
what's the different between PodKillExperiment and PodFailureExperiments,  since PodFailureExperiments will quickly cause Pod Killed and restarted.

### ISSUE THREAD

**Issue by gotoworld** [chaos-mesh/chaos-mesh#1173]
## Question

what's the different between PodKillExperiment and PodFailureExperiments,  
since PodFailureExperiments will quickly cause Pod Kill and restart.

As the Pod Failure experiment define, it's this will duration a monent, but actually what we encouter is the Pod be killed and restart as soon as quickly. 

and attach with screenshot
![image](https://user-images.githubusercontent.com/8605471/99018131-56685e00-2594-11eb-9049-2b80d9b7da15.png)

---
> Pod Failure action periodically injects errors to pods. And it will cause pod creation failure for a while. In other words, the selected pod will be unavailable in a specified period.

> Pod Kill action kills the specified pod (ReplicaSet or something similar might be needed to ensure the pod will be restarted).
---

**Comment by gotoworld** [comment]
following with the pod failure experiment yaml 

```
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-example
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - "basicservice"
    podPhaseSelectors:
      - "Running"
  scheduler:
    cron: "@every 4m"
```
