### ISSUE TITLE
Does the ChaosMesh support pid and thread exceed pid_max, thread-max exceed experiment?

### ISSUE THREAD

**Issue by gotoworld** [chaos-mesh/chaos-mesh#1202]
## Question

Does the ChaosMesh support pid and thread exceed pid_max, thread-max exceed experiment ?

once we have suffer a  accident in production environment,  since more and more pods is run in one OS. 
although a resource limit of pid and monitor of thread is added, but we want to make this accident repeating again and again.

**Comment by YangKeao** [comment]
```
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: burn-pid
spec:
  mode: one
  selector:
    labelSelectors:
      test: test
  stressngStressors: -f 16 --fork-max 255
```

This `StressChaos` configuration should work. `-f` means the `fork` worker, and the `--fork-max P` is creating  P child processes and then wait for them to exit per iteration. You can find a more detailed description in the [manpage](https://manpages.ubuntu.com/manpages/artful/man1/stress-ng.1.html)
