### ISSUE TITLE
chaos-dashboard: Can not create "Run immediately" Chaos

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#1225]
## Bug Report

**What version of Kubernetes are you using?**

```
❯ minikube version
minikube version: v1.15.1
commit: 23f40a012abb52eff365ff99a709501a61ac5876
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

chaos-mesh/chaos-mesh master branch, c7a7d15

I guess: chaos-dashboard ignore the "Run immediately" switcher.

**What did you do?**

- deploy chaos-mesh with helm, enable dashboard
- create a NetworkChaos, fill other unimportant specs
- switch "Run immediately" on, then click SUBMIT
![image](https://user-images.githubusercontent.com/20221408/100424147-23f84e00-30c8-11eb-9e4f-ebbe8d720c97.png)

**What did you expect to see?**
Chaos create succeed.

**What did you see instead?**
Nothing happened. No notice, no popup, console no log.

**Following-up story**

And I switch off "Run immediately", I found validator warn on "cron" and "schedule".
![image](https://user-images.githubusercontent.com/20221408/100424348-6e79ca80-30c8-11eb-80f5-b74c3f2be10d.png)

Then I fill "cron" and "schedule", but switch on "Run immediately" again, chaos created succeed; BUT it still hold a "cron" and "schedule".

Operation:
![](https://i.imgur.com/kFFmZ86.gif)

Result:
```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: just-another-delay
  namespace: default
  labels: null
  annotations: null
spec:
  action: partition
  mode: one
  value: ''
  selector:
    namespaces:
      - default
  duration: 8m # <= this is unexpected
  scheduler:
    cron: '@every 10m' # <= this is unexpected
  direction: to

```
