### ISSUE TITLE
Can't reuse the archived experiment by Chaos Dashboard

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#1318]
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-02-07T01:05:17Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
``` 
Chaos Mesh version: 

```
Controller manager Version: version.Info{GitVersion:"master-gb74b0e1ad5a032", GitCommit:"b74b0e1ad5a032950e160ead935ed754500525af", BuildDate:"2020-12-21T08:38:01Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**
 

Create a chaos experiment  -> pause -> archive -> reuse this chaos experiment and then get an error: 

![image](https://user-images.githubusercontent.com/22956341/102859822-a7a71f80-4467-11eb-976e-94016be823da.png)

Original experiment: 

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: delay-demo
  namespace: default
  labels: null
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  action: delay
  mode: one
  value: ''
  selector:
    namespaces:
      - default
    labelSelectors:
      app: web-show
  duration: 10s
  scheduler:
    cron: '@every 30s'
  delay:
    latency: 10ms
    correlation: '0'
    jitter: 0ms
  direction: to
  target:
    selector:
      namespaces:
        - chaos-testing
      labelSelectors:
        app.kubernetes.io/component: controller-manager
    mode: one
    value: ''

```

Reused experiment: 

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: delay-demo
  namespace: default
  labels: null
  annotations:
    experiment_chaos_mesh_org_pause: 'true'
spec:
  action: delay
  mode: one
  value: ''
  selector:
    namespaces:
      - default
    labelSelectors:
      app: web-show
  duration: 10s
  scheduler:
    cron: '@every 30s'
  delay:
    latency: 10ms
    correlation: '0'
    jitter: 0ms
  direction: to
  target:
    selector:
      namespaces:
        - default
      labelSelectors:
        app_kubernetes_io_component: controller-manager
    mode: one
    value: ''
```
