### ISSUE TITLE
Can't delete or pause a flawed TimeChaos experiment

### ISSUE THREAD

**Issue by torblerone** [chaos-mesh/chaos-mesh#1422]
## Bug Report

**What version of Kubernetes are you using?**
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**
```
Controller manager Version: version.Info{GitVersion:"v1.0.1", GitCommit:"f4f15091713bcf0fe7ec87f46e723a89e3184b46", BuildDate:"2020-10-16T15:10:29Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**
I created a TimeChaos experiment to run on a certain app in a certain namespace:

```
apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: timeshift-XXXXXXXXXXX
  namespace: XXXXXXXXXXX
  labels: null
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  mode: one
  value: ''
  selector:
    namespaces:
      - XXXXXXXXXXXX
    labelSelectors:
      app: XXXXXX
  timeOffset: '-8773h100m10s5ms3ns'
  clockIds:
    - CLOCK_REALTIME
  duration: 120s
  scheduler:
    cron: '@every 5m'

```

**What did you expect to see?**
I wanted to check if TimeChaos worked in our k8s cluster, as below screenshot shows it apparently didn't work yet, perhaps some misconfiguration by me.

![grafik](https://user-images.githubusercontent.com/64590448/104906100-8ad90b80-5983-11eb-9cdc-bc9e6c8575d3.png)

So, I thought I could just pause and archive/delete the experiment and go on with configuration.

**What did you see instead?**
The experiment is still shown as "running" when I try to pause it. When I click "Archive", it also shows a succeed message but keeps in state "Running".

(Also, why do I have to "Archive" an experiment first, before I can delete it?)
