### ISSUE TITLE
stresschaos-cpu label selector wrong behavior

### ISSUE THREAD

**Issue by marvinlchen** [chaos-mesh/chaos-mesh#1435]
## Bug Report

**What version of Kubernetes are you using?**
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T23:30:39Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
```
```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**
```
Controller manager Version: version.Info{GitVersion:"v1.0.3", GitCommit:"28de66e58ef60056b1f1966527fe85cc2396d670", BuildDate:"2020-12-16T14:57:04Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**
```
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: 263-cpu.yaml
  namespace: chaos-testing
spec:
  duration: 60s
  mode: all
  scheduler:
    cron: '@every 24h'
  selector:
    labelSelectors:
      app: web-show
    namespaces:
    - default
  stressors:
    cpu:
      load: 100
      workers: 1
  value: ""
```

**What did you expect to see?**
only one stress-ng should be found

**What did you see instead?**
a lot of stress-ng process
![image](https://user-images.githubusercontent.com/48372495/105327548-f8966900-5c09-11eb-8ddb-6b11a07d8b6c.png)

**Output of chaosctl**
![image](https://user-images.githubusercontent.com/48372495/105326715-039cc980-5c09-11eb-9999-e1fc97b86ea6.png)

**Comment by STRRL** [comment]
Hi @marvinlchen, could you provide pods info about chaos-mesh components by `kubectl -n chaos-testing get pods -o wide`?

**Comment by marvinlchen** [comment]
kubectl -n chaos-testing get pods -o wide
![image](https://user-images.githubusercontent.com/48372495/105964476-33dae100-60bd-11eb-8381-100ef3967cb5.png)

kubectl -n chaos-testing describe service chaos-daemon
![image](https://user-images.githubusercontent.com/48372495/105964440-29204c00-60bd-11eb-9026-40ced24030be.png)

**Comment by STRRL** [comment]
Hi @marvinlchen, it seems ChaosMesh components work well.  As the logs say, the `NodeName` of the `web-show` pod.spec is an empty string. Does it happen something like evicting on your k8s cluster?

One more thing, could you reproduce this issue and provide the output of `kubectl -nchaos-testing describe stresschaos 263-cpu.yaml` for us? 🥺 It might be something useful in the event.

I still trying to reproduce your issue on my machine, it will take a long time due to `cron: '@every 24h'`

**Comment by marvinlchen** [comment]
Hi, you can shorten the period `cron: '@every 24h'`. It is 100% reproducable on my machine.

**Comment by STRRL** [comment]
> Hi, you can shorten the period `cron: '@every 24h'`. It is 100% reproducable on my machine.

OK!

**Comment by marvinlchen** [comment]
Found how to reproduce it! If there is a pending pod, applying the yaml above, then there will be a lot of stress-ng-cpu.
![image](https://user-images.githubusercontent.com/48372495/105982157-e5840d00-60d1-11eb-96e0-29384309f9d0.png)

**Comment by STRRL** [comment]
> Found how to reproduce it! If there is a pending pod, applying the yaml above, then there will be a lot of stress-ng-cpu.
> ![image](https://user-images.githubusercontent.com/48372495/105982157-e5840d00-60d1-11eb-96e0-29384309f9d0.png)
> 

oh! thanks a lot! We will take a look.

**Comment by STRRL** [comment]
Hi @marvinlchen, before we resolve this issue, you could use `podPhaseSelectors` to avoid inject stress chaos into pending pods. Here is an example:

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: 263-cpu.yaml
  namespace: chaos-testing
spec:
  duration: 20s
  mode: all
  scheduler:
    cron: '@every 30s'
  selector:
    # only inject chaos into running pods
    podPhaseSelectors:
    - Running
    labelSelectors:
      app: web-show
    namespaces:
    - default
  stressors:
    cpu:
      load: 20
      workers: 1
  value: ""

```

**Comment by marvinlchen** [comment]
```
  selector:
    labelSelectors:
      app: web-show
    namespaces:
    - default
    podPhaseSelectors:
    - running
```
 When I add podPhaseSelectors, it is not working at all. No stress-ng is activated.
