### ISSUE TITLE
after change the set of target pods, stresschaos failed, and can not delete stresschaos anymore

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#1465]
## Bug Report

I am not sure this issue only occurs on StressChaos, I have not tested on other types of chaos.

**What version of Kubernetes are you using?**

```bash
# strrl @ giu in ~ [17:10:08] C:1
$ minikube version
minikube version: v1.14.2
commit: 2c82918e2347188e21c4e44c8056fc80408bce10

# strrl @ giu in ~ [17:16:09]
$ k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"archive", BuildDate:"2020-07-28T00:00:00Z", GoVersion:"go1.15rc1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**

```bash
$ k -n chaos-testing exec chaos-controller-manager-7df4574bcf-dtdls -- /usr/local/bin/chaos-controller-manager -version
Controller manager Version: version.Info{GitVersion:"v1.1.1", GitCommit:"88e265c1ad2bcc3931645371a71683dd52b576fb", BuildDate:"2021-01-21T11:24:39Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

workload:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-show
  labels:
    app: web-show
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-show
  template:
    metadata:
      labels:
        app: web-show
    spec:
      containers:
        - name: web-show
          image: pingcap/web-show
          imagePullPolicy: Always
          command:
            - /usr/local/bin/web-show
            - --target-ip=1.1.1.1
          ports:
            - name: web-port
              containerPort: 8081
```

stresschaos:
```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: 263-cpu.yaml
  namespace: chaos-testing
spec:
  duration: 20s
  mode: all
  scheduler:
    cron: '@every 30s'
  selector:
    labelSelectors:
      app: web-show
    namespaces:
    - default
  stressors:
    cpu:
      load: 20
      workers: 1
  value: ""

```

- start up kubernetes cluster with minikube, install ChaosMesh 1.1.1 and apply workloads and stresschaos
- `k -n default delete pod --all` it will remove all the `web-show` pods (it will re-spawn new pods later)

**What did you expect to see?**
I want stress chaos could keep working with new pods. But it will take a long way to go for changing the pods. At least I could delete the failed stress chaos.

**What did you see instead?**
Stress chaos failed, and I can not delete this stress chaos CRD. It hangs on waiting for the finalizers.

Until I manually remove all the finalized with `kubectl edit`, I could finally delete this stresschaos.

```bash
k -nchaos-testing describe stresschaos.chaos-mesh.org 263-cpu.yaml
Name:         263-cpu.yaml
Namespace:    chaos-testing
Labels:       <none>
Annotations:  API Version:  chaos-mesh.org/v1alpha1
Kind:         StressChaos
Metadata:
  Creation Timestamp:  2021-01-28T09:10:14Z
  Finalizers:
    default/web-show-5886c5bffc-tdrfw
    default/web-show-5886c5bffc-fzkts
    default/web-show-5886c5bffc-2vrgg
    default/web-show-5886c5bffc-zkvxx
    default/web-show-5886c5bffc-55k99
    default/web-show-5886c5bffc-7jj7g
    default/web-show-5886c5bffc-76q9s
    default/web-show-5886c5bffc-cvgk8
    default/web-show-5886c5bffc-lwmvb
    default/web-show-5886c5bffc-rwv8p
  Generation:  36
  # ... rest of outputs
```

```bash
$ k -n default get pods
NAME                        READY   STATUS    RESTARTS   AGE
web-show-5886c5bffc-2vrgg   1/1     Running   0          46m
web-show-5886c5bffc-fzkts   1/1     Running   0          46m
web-show-5886c5bffc-lwmvb   1/1     Running   0          46m
web-show-5886c5bffc-rwv8p   1/1     Running   0          46m
web-show-5886c5bffc-tdrfw   1/1     Running   0          46m
```

Here seems are two problems:
- finalizers in stresschaos have more entry than actual exist pods
- finalizers will not be updated anymore

**Output of chaosctl**
