### ISSUE TITLE
NetworkChaos direction:Both has no affect 

### ISSUE THREAD

**Issue by Robbie558** [chaos-mesh/chaos-mesh#1486]
## Bug Report

**What version of Kubernetes are you using?**
```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:18:22Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**
```
Controller manager Version: version.Info{GitVersion:"v1.1.1", GitCommit:"88e265c1ad2bcc3931645371a71683dd52b576fb", BuildDate:"2021-01-21T11:24:39Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**
We have the following `NetworkChaos` experiment spec and two pods of the target application running, but when running there appears no network loss at all:

```
spec:
  action: loss
  mode: all
  value: ''
  selector:
    namespaces:
      - <app_namespace>
    labelSelectors:
      app: <app_label_name>
  loss:
    loss: '100'
    correlation: '100'
  direction: both
```

Testing using separate `to` and `from` NetworkChaos experiment specs does appear to work for us.  The configuration used for these specs is as follows:

**From:**
```
spec:
  action: loss
  direction: from
  loss:
    correlation: "100"
    loss: "100"
  mode: all 
  selector:
    namespaces:
    - <app_namespace>
  target:
    mode: all 
    selector:
      labelSelectors:
        app: <app_label_name>
      namespaces:
      - <app_namespace>
    value: ""
  value: ""
```

In this we are limiting (non-target section `selector` option) on namespace as we wish to affect traffic from all pods in that given namespace going to our target pod.

**To:**
```
spec:
  action: loss
  direction: to
  loss:
    correlation: "100"
    loss: "100"
  mode: all 
  selector:
    labelSelectors:
      app: <app_label_name>
    namespaces:
    - <app_namespace>
  target:
    mode: all 
    selector:
      namespaces:
      - <app_namespace>
    value: ""
  value: ""

```

**What did you expect to see?**
Bi-directional network loss for pods 

**What did you see instead?**
No network loss in either direction for the target pods 

**Output of chaosctl**

Not captured

-----
Please advise if I am doing something wrong, but I could not get anything working using the [examples](https://github.com/chaos-mesh/chaos-mesh/blob/master/examples/network-loss-example.yaml) or [documentation](https://chaos-mesh.org/docs/chaos_experiments/networkchaos_experiment).

**Comment by cwen0** [comment]
@Robbie558 Thanks for your report. We will troubleshoot this issue ASAP!

**Comment by YangKeao** [comment]
Setting `direction` without `target` field is not expected. Omitting the `direction` value should make it work.

**Comment by STRRL** [comment]
Related issue: https://github.com/chaos-mesh/chaos-mesh/issues/1437.

If we could make NetworkChaos effect on incoming traffic, I think this problem could finally be resolved, with an implicit rule: no `target` in `Spec` means all traffic. Am I right? @cwen0 @YangKeao 

For network delay, I think we could make it by [ref](https://wiki.linuxfoundation.org/networking/netem#how_can_i_use_netem_on_incoming_traffic). We cuold have a try, test it's compatible with other rules(ipset/iptables), and its overheads.

**Comment by Robbie558** [comment]
> Setting `direction` without `target` field is not expected. Omitting the `direction` value should make it work.

The documentation doesn't cover this and states "both" as a supported option.  Having said that I now see that the [example](https://github.com/chaos-mesh/chaos-mesh/blob/master/examples/network-loss-example.yaml)  doesn't use the `direction` field, but this is actually not possible when defining an experiment through the WUI.  Not selecting a direction through the WUI results in the direction defaulting to `to`, and this cannot be removed through the 'update' view in the WUI.

Testing with the following spec does indeed appear to result in a loss of traffic in and out of the selected pods:
```
spec:
  action: loss
  mode: all
  value: ''
  selector:
    namespaces:
      - <app_namespace>
    labelSelectors:
      app: <app_label_name>
  loss:
    loss: '100'
    correlation: '100'
  direction: to
```  
However, this **impacts all traffic**, whilst my requirement is only to impact traffic in both directions to/from a target namespace. Is my method of setting to and a from experiment independently correct?
