### ISSUE TITLE
Spurious Debug Messages "got runtime.Object without object metadata"

### ISSUE THREAD

**Issue by Robbie558** [chaos-mesh/chaos-mesh#1487]
## Bug Report

**What version of Kubernetes are you using?**
```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:18:22Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**
```
Controller manager Version: version.Info{GitVersion:"v1.1.1", GitCommit:"88e265c1ad2bcc3931645371a71683dd52b576fb", BuildDate:"2021-01-21T11:24:39Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**
Add PodChaos and NetworkChaos experiments with the following labels and annotations:

```
  labels:
    app: <app_name>
    chart: <app_version>
    environment: <namespace>
    heritage: <heritage>
    release: <release_name>
...
annotations:
    description: <description_string>
    experiment.chaos-mesh.org/pause: "true"
    hypothesis: <extended_description>

```

We also attempted to create an experiment via the dashboard that contains no labels and annotations, but the same debug message is observed on the Chaos controller pod.

**What did you expect to see?**
No error message regarding labels / annotations for all PodChaos and NetworkChaos experiments

**What did you see instead?**
Error messages regarding labels / annotations for all  PodChaos and NetworkChaos experiments

**Output of chaosctl**

TBC
