### ISSUE TITLE
How to select pods under multiple labels when creating Network Partition Chaos?

### ISSUE THREAD

**Issue by zhuwenxing** [chaos-mesh/chaos-mesh#1582]
## Question

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/chaos-mesh/chaos-mesh/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [Chaos Mesh Readme](https://github.com/chaos-mesh/chaos-mesh)
  - [Chaos Mesh Doc](https://chaos-mesh.org/docs)

**Output of chaosctl**

I hope that the pods under the two labels of kafka and mongo are separated by the network, but when I select these two labels in the label selectors of the webpage, after submission, the final Affected Pods will only have the pods under the last selected label.

![image](https://user-images.githubusercontent.com/12268675/111961350-ecf0f100-8b2b-11eb-8b5d-9a8b311f8b35.png)

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: test-1
  namespace: default
  labels: null
  annotations: null
spec:
  action: partition
  mode: all
  value: ''
  selector:
    namespaces:
      - default
    labelSelectors:
      app: mongo
  direction: to
```

**Comment by g1eny0ung** [comment]
Because they all have the same key (`app`) so the following selector will overwrite the previous. Add a common label to them can solve this problem temporarily.

**Comment by zhuwenxing** [comment]
I solve this problem temporarily by select pods as selector 
```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: test-network-part-03-22
  namespace: default
  labels: null
  annotations:
    experiment.chaos-mesh.org/pause: 'false'
spec:
  action: partition
  mode: all
  value: ''
  selector:
    namespaces:
      - default
    pods:
      default:
        - clickhouse-0
        - kafka-585f8754f4-rclwn
        - mongo-566969849f-pfd87
        - mysql-547f49676f-hpfnl
  direction: both
```
Does it mean the network between these four pods unconnected?
But I entered the `clickhouse-0` pod through `kubectl exec`, and `ping ${kafka_pod_ip}`. The result showed that it was still normal.

**Comment by g1eny0ung** [comment]
@YangKeao PTAL when you have time.

**Comment by zhuwenxing** [comment]
more info
![image](https://user-images.githubusercontent.com/12268675/111972574-94742080-8b38-11eb-86fc-5470f2e24572.png)

![image](https://user-images.githubusercontent.com/12268675/111972581-95a54d80-8b38-11eb-9323-4b9ecf5261d2.png)

**Comment by YangKeao** [comment]
The expected `NetworkChaos` resource to setup a network partition between clickhouse and kafka should be :

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: test-network-part-03-22
  namespace: default
  labels: null
  annotations:
    experiment.chaos-mesh.org/pause: 'false'
spec:
  action: partition
  mode: all
  value: ''
  selector:
    namespaces:
      - default
    pods:
      default:
        - clickhouse-0
  target:
    mode: all
    value: ""
    selector:
      namespaces:
        - default
      pods:
        default:
          - kafka-585f8754f4-rclwn
  direction: both
```

The `target` field can be selected in the `target` button of the dashboard
 
![image](https://user-images.githubusercontent.com/5244316/112264510-f5703580-8cab-11eb-9fa8-21d50783412a.png)

(The right-bottom part)

I will setup another issue to discuss the behavior when `target` is not set. I cannot remember the behavior of it in the very beginning/design when the `target` field and `externalTarget` fields are not set. Obviously, it doesn't have any effect if the `target` and `externalTarget` are both not set now :man_facepalming: .
