### ISSUE TITLE
Network experiment doesn't work

### ISSUE THREAD

**Issue by lcwus2** [chaos-mesh/chaos-mesh#1746]
## Bug Report

**What version of Kubernetes are you using?**

v1.18.9

**What version of Chaos Mesh are you using?**

v1.1.4

**What did you do?**

1. I create network loss experiment in dashboard, detail experiment yaml:
```
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-loss-test
  namespace: mingzhu-simulation
  labels: null
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  action: loss
  mode: all
  value: ''
  selector:
    namespaces:
      - mingzhu-simulation
    labelSelectors:
      clientName: cloud-nome
  loss:
    loss: '100'
    correlation: '100'
  direction: both
  target:
    selector:
      namespaces:
        - mingzhu-simulation
      labelSelectors:
        clientName: cloud-nome
    mode: all
    value: ''
```
2. then start this experiment, return success, but in the pod that was controlled, ` ping www.baidu.com`, still have no loss

**What did you expect to see?**
network loss experiment works

**What did you see instead?**

**Output of chaosctl**

**Comment by fewdan** [comment]
```
annotations:
    experiment.chaos-mesh.org/pause: 'true'
```
Judging from the above yaml file, this network experiment has been paused?

**Comment by lcwus2** [comment]
> ```
> annotations:
>     experiment.chaos-mesh.org/pause: 'true'
> ```
> 
> Judging from the above yaml file, this network experiment has been paused?

I stopped this experiment when I copy this yaml in dashboard...

**Comment by fewdan** [comment]
@lcwus2 Sorry for the slow response, does this problem still exist?

**Comment by austinpray-mixpanel** [comment]
@Icwus2 check that your "target" section is valid. As far as I can tell your experiment in the OP is targeting itself when the target should probably be omitted.

**Comment by AsterNighT** [comment]
As @austinpray-mixpanel mentioned, you should not specify a target or you will get a networkchaos targeting the pod itself. And `mode: all` only indicates that it will work on all pods selected by the `target` part. 
Would you try again after deleting the `target` part?

**Comment by lcwus2** [comment]
> As @austinpray-mixpanel mentioned, you should not specify a target or you will get a networkchaos targeting the pod itself. And `mode: all` only indicates that it will work on all pods selected by the `target` part.
> Would you try again after deleting the `target` part?

I try to remove `target` but something wrong as follow:
![image](https://user-images.githubusercontent.com/30100640/117600817-4adea400-b17f-11eb-9bc3-1edbba28d3d3.png)

now my experiment file like this:
```
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: test
  namespace: mingzhu-simulation
  labels: null
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  action: loss
  mode: one
  value: ''
  selector:
    namespaces:
      - mingzhu-simulation
    labelSelectors:
      clientName: cloud-nome
  loss:
    loss: '100'
    correlation: '0'
  direction: both
  target:
    selector:
      namespaces:
        - mingzhu-simulation
      labelSelectors:
        clientName: cloud-nome
    mode: one
    value: ''
```
my confusion is that there are two part to set experiment scope? I just want to use `target` to set injected pods scope
