### ISSUE TITLE
CRON stops after an error is encountered 

### ISSUE THREAD

**Issue by ojaswa1942** [chaos-mesh/chaos-mesh#1829]
## Bug Report

**Kubernetes Version:**
Client: v1.20.5
Server: v1.20.2

**Chaos Mesh Version**: v1.2.0 (CommitId: e9dc90589310013fbde93a8a5172c08d1091145f)

**What did I do?**
1. Setup a `container-kill` `PodChaos` with a CRON of every 40s.
```
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-api-containter
  namespace: chaos-testing
spec:
  action: container-kill
  mode: all
  containerName: 'api'
  selector: # for target pods
    namespaces:
      - 'default'
    labelSelectors:
      app: api
  scheduler:
    cron: '@every 40s'
```
2. Monitored pod status and application reachability
3. On unexpected behavior, used `chaos-dashboard` to debug

**What went wrong?**
The PodChaos went on running a few times until the time interval between the next `container-kill` event and the time take for the pod to restart diminished. At that moment, upon looking up in the dashboard, I found the following error:
```
rpc error: code = Unknown desc = Error response from daemon: Cannot kill container: abf0b83ef5dd644bb9116da894d72e48339b3f02a36a271d4f71d8aeae104c62: Container abf0b83ef5dd644bb9116da894d72e48339b3f02a36a271d4f71d8aeae104c62 is not running
```

The error makes sense. Since the container is not yet running, it has not been possible to kill it just yet.
**However, upon waiting for the next event, I observed that the CRON has stopped working anymore.**

Here is a screenshot from the dashboard:
![Screenshot from 2021-05-12 12-19-38](https://user-images.githubusercontent.com/35270649/117929357-57e3ca80-b31a-11eb-837a-bb6ce43cbf5f.png)

If this is expected behavior, I don't believe the CRON should stop after an error is encountered as it is not equivalent to generic CRON behaviors.
