### ISSUE TITLE
Add status for every records

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#1833]
For example, in the `Pod` there is a `containerStatuses`:

```
  containerStatuses:
  - image: mysql:5.6.aaaaa
    imageID: ""
    lastState: {}
    name: mysql
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "mysql:5.6.aaaaa"
        reason: ImagePullBackOff
```

It records the state and coresponding message. Maybe we should also add a message for every record?
