### ISSUE TITLE
NetworkChaos for MQTT

### ISSUE THREAD

**Issue by adbjo** [chaos-mesh/chaos-mesh#1852]
Hi,

We have a service that connects to an MQTT broker and publishes events.
We are trying to simulate network issues in MQTT using NetworkChaos experiments.

Blocking traffic with Network partition does not do anything, here's the experiment config:
```
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: mqtt-network-partition
  namespace: chaos
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - services
    labelSelectors:
      app: mqtt-service
  direction: to
  externalTargets:
    - "mqtt.broker.address"
  scheduler:
    cron: "*/12 * * * *"
  duration: 10m
```

The service successfully publishes events to the MQTT broker while the experiment is running.
MQTT runs on TCP/IP and should be blocked.
Do you have some idea why it is not working and how we might get it to work?
Do the NetworkChaos experiments have any effect on open TCP connections?

Thanks!
