### ISSUE TITLE
Workflow Webhook Validation: duration in chaos nodes

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#1877]
## Feature Request

That is actually an unexpected declaration of workflow chaos node:
```yaml
- name: network-chaos
  templateType: NetworkChaos
  duration: 20s
  networkChaos:
    selector:
      labelSelector:
        app: web-show
    mode: all
    action: delay
    delay:
      latency: '90ms'
    direction: to
    duration: 30s # <- unexpected
```

Users should not declare another `duration` in the chaos, and currently, we do not have a validator for that. That will cause problems.

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**
