### ISSUE TITLE
Cant limit chaos mesh to just 2 namespaces in my cluster

### ISSUE THREAD

**Issue by itaydj** [chaos-mesh/chaos-mesh#1953]
Hi All,
I am setting up ChaosMesh in our cluster but I would like it to apply only to a selected batch of namespaces.
Currently it is only applied to a single namespace using the following values.yml:
```
controllerManager:
  hostNetwork: false
  enableFilterNamespace: false
clusterScoped: false
  targetNamespace: "my-namespace"
```
I would like to add a second affected namespace, how should I do it?
tried the below but it didnt go so well:
```
controllerManager:
  hostNetwork: false
  enableFilterNamespace: false
clusterScoped: false
  targetNamespace: "my-namespace", "my-other-namespace"
```

Is specifying more than one target namespace even possible?
if so, how can I achieve that?

Thanks in advance
