### ISSUE TITLE
Memory stress is consuming full CPU core

### ISSUE THREAD

**Issue by anuragpaliwal80** [chaos-mesh/chaos-mesh#1964]
## Bug Report

**What version of Kubernetes are you using?**

`1.19.4`

**What version of Chaos Mesh are you using?**

`1.1.3`

**What did you do?**

Run memory stress tests:
```
  stressors:
    memory:
      workers: 1
      size: '512MB'
```

**What did you expect to see?**
The CPU should not go up.

**What did you see instead?**
It consume 1 full core CPU and if we increase number of worker, it will consume those many CPU core.

**Output of chaosctl**
