### ISSUE TITLE
pod-failure does not work well with SeccompProfile on kubernetes v1.19+

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2018]
## Bug Report

Origin issue: #1574

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**

```
Controller manager Version: version.Info{GitVersion:"chore/full-search-ge6f4df43efb843", GitCommit:"e6f4df43efb843a69062cb884fe37592f5e3409b", BuildDate:"2021-06-22T06:51:07Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

1. start a minikube cluster(version 1.19 +)
2. apply deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations: 
        # take a look on these annotations
        kubernetes.io/psp: restricted
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: {}
      dnsPolicy: ClusterFirst

```

3. apply chaos

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-example
  namespace: default
spec:
  action: pod-failure
  mode: one
  duration: "30s"
  selector:
    labelSelectors:
      "app": "nginx"
```

**What did you expect to see?**
PodChaos could be injected as expected.

**What did you see instead?**
PodChaos does not works well, with many event like:

```
  Warning  Failed  14s  records  Failed to apply chaos: Pod "nginx-64f5487c89-tk4qb" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
  core.PodSpec{
    ... // 10 identical fields
    AutomountServiceAccountToken: nil,
    NodeName:                     "minikube",
    SecurityContext: &core.PodSecurityContext{
      ... // 11 identical fields
      FSGroupChangePolicy: nil,
      Sysctls:             nil,
-     SeccompProfile:      nil,
+     SeccompProfile:      &core.SeccompProfile{Type: "RuntimeDefault"},
    },
    ImagePullSecrets: nil,
    Hostname:         "",
    ... // 15 identical fields
  }
  Warning  Failed  9s  records  Failed to apply chaos: Pod "nginx-64f5487c89-tk4qb" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
  core.PodSpec{
    ... // 10 identical fields
    AutomountServiceAccountToken: nil,
    NodeName:                     "minikube",
    SecurityContext: &core.PodSecurityContext{
      ... // 11 identical fields
      FSGroupChangePolicy: nil,
      Sysctls:             nil,
-     SeccompProfile:      nil,
+     SeccompProfile:      &core.SeccompProfile{Type: "RuntimeDefault"},
    },
    ImagePullSecrets: nil,
    Hostname:         "",
    ... // 15 identical fields
```

**Output of chaosctl**
