### ISSUE TITLE
workflow: enhance conditionalBranches display on UI

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2051]
## Feature Request

**Is your feature request related to a problem? Please describe:**

No.

**Describe the feature you'd like:**

I want to see the children nodes of one Task node, for example:

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: try-task
  namespace: default
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      deadline: 1h
      children:
        - customized-task
    - name: nginx-kill
      templateType: PodChaos
      deadline: 3m
      podChaos:
        selector:
          namespaces:
            - default
          labelSelectors:
            app: nginx
        mode: one
        action: pod-kill
        gracePeriod: 0
    - name: nginx-failure
      templateType: PodChaos
      deadline: 3m
      podChaos:
        selector:
          namespaces:
            - default
          labelSelectors:
            app: nginx
        mode: one
        action: pod-failure
        gracePeriod: 0
    - name: customized-task
      templateType: Task
      task:
        container:
          name: main
          image: busybox
          command:
            - echo
            - a
          resources: {}
      conditionalBranches:
        - target: nginx-kill
          expression: stdout == "a"
        - target: nginx-failure
          expression: exitCode == 0
```

Both `nginx-kill` and `nginx-failure` should be executed after `customized-task` accomplished. But we could not see these two node on Chaos Dashboard for now.
![image](https://user-images.githubusercontent.com/20221408/123905784-89395800-d9a5-11eb-878c-6e3b4a095550.png)

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

The Chaos Dashboard API should return the conditional branches in Task WorkflowNode, in `pkg/core/workflow.go`, new struct `ConditionalBranch` need to be created. And one new field in `Node` called `conditionalBranches` also will be created.

After the update of the backend API, the frontend could draw the children nodes.

(Optional) And could we also draw the `expression` on the line which connects the child node?

like that:
![image](https://user-images.githubusercontent.com/20221408/123906347-9276f480-d9a6-11eb-810c-8d536e093a96.png)
