### ISSUE TITLE
Chaos dashboard: Is the Namespace option required when executing AwsChaos?

### ISSUE THREAD

**Issue by abnoumaru** [chaos-mesh/chaos-mesh#2091]
## Bug Report

**What version of Kubernetes are you using?**

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**

```
❯ kubectl exec -n chaos-testing chaos-controller-manager-xxxxxxxxxxx-xxxxx -- /usr/local/bin/chaos-controller-manager -version
Controller manager Version: version.Info{GitVersion:"v1.2.1", GitCommit:"04ba84bee704e97e93335e34323d24466a59c3e8", BuildDate:"2021-05-21T11:08:23Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

Install chaos-mesh by Helm 3. Helm Chart version is, I've tried two versions, v0.5.1 and v0.5.2 .

```
$ helm install --reset-values --allow-unreleased chaos-mesh chaos-mesh/chaos-mesh --version v0.5.1 --namespace chaos-testing --values ./chaos-mesh.yaml
```

Values file is below

```
timezone: "Asia/Tokyo"

controllerManager:
  nodeSelector:
    xxxx/xxxx: "true"

chaosDaemon:
  nodeSelector:
    xxxx/xxxx: "true"

dashboard:
  nodeSelector:
    xxxx/xxxx: "true"

  securityMode: false

dnsServer:
  nodeSelector:
    xxxx/xxxx: "true"
```

I tried to execute AwsChaos via the Chaos Dashboard.

**What did you expect to see?**

When executing AwsChaos, A Scope Section is not required (the UI shows "(No need to fill in)").

**What did you see instead?**

However, when I press the SUBMIT button, I get a warning "The namespace selectors are required" and I can't submit.
Also, the namespace selector say "No options".

<img width="1464" alt="ec2-restart-dashboard-bug2" src="https://user-images.githubusercontent.com/7035505/124878403-077da600-e007-11eb-9a43-6367151f0da8.png">

<img width="1459" alt="ec2-restart-dashboard-bug" src="https://user-images.githubusercontent.com/7035505/124877157-c89b2080-e005-11eb-8be6-e9ad80a91dce.png">

When executing AwsChaos, Current Chaos Dashboard required a Namespace option , but a Namespace option should not be required.
