### ISSUE TITLE
IO INJECTION's status is always injecting

### ISSUE THREAD

**Issue by FingerLeader** [chaos-mesh/chaos-mesh#2114]
## Bug Report

**What version of Kubernetes are you using?**
client:v1.21.2
server:v1.21.2

**What version of Chaos Mesh are you using?**
```
Controller manager Version: version.Info{GitVersion:"master-g2bc0fa81544659", GitCommit:"2bc0fa815446599852116ac0dfb612f659376745", BuildDate:"2021-07-12T09:58:17Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**
I created an IO INJECTION on dashboard without filling in the volume path.
this is my configuration:
```
kind: IOChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: latency
  namespace: tidb-cluster
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  selector:
    namespaces:
      - tidb-cluster
    labelSelectors:
      app.kubernetes.io/component: tidb
  mode: one
  containerNames:
    - ''
  action: latency
  delay: 5ms
  percent: 50
  volumePath: ''
```
**What did you expect to see?**
The INJECTION's status be running.
**What did you see instead?**
The INJECTION's status is always injecting. This is the case for all of these three kinds of IO INJECTION.
