### ISSUE TITLE
An experiment still shows running without working in a workflow with an earlier deadling

### ISSUE THREAD

**Issue by FingerLeader** [chaos-mesh/chaos-mesh#2115]
## Bug Report

**What version of Kubernetes are you using?**
client:v1.21.2
server:v1.21.2

**What version of Chaos Mesh are you using?**
```
Controller manager Version: version.Info{GitVersion:"master-g2bc0fa81544659", GitCommit:"2bc0fa815446599852116ac0dfb612f659376745", BuildDate:"2021-07-12T09:58:17Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**
I add a pod-failure experiment which lasts 1h in workflow which lasts only 20s.

**What did you expect to see?**
The pod-failure ends after workflow ends

**What did you see instead?**
The workflow ends, but pod-failure still shows running on dashboard. But when I check my pod， the pod is running normally.
this is my configuration
```
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: wf-single-longerthanexp
  namespace: tidb-cluster
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      deadline: 20s
      children:
        - pod-failure
    - name: pod-failure
      templateType: PodChaos
      deadline: 1h
      podChaos:
        selector:
          namespaces:
            - tidb-cluster
          labelSelectors:
            app.kubernetes.io/component: pd
        mode: one
        action: pod-failure
        gracePeriod: 0
```
this is information of describe podchaos:
```
Name:         pod-failure-9gsf5-lblrk
Namespace:    tidb-cluster
Labels:       chaos-mesh.org/controlled-by=pod-failure-9gsf5
              chaos-mesh.org/workflow=wf-single-longerthanexp
Annotations:  <none>
API Version:  chaos-mesh.org/v1alpha1
Kind:         PodChaos
Metadata:
  Creation Timestamp:  2021-07-14T06:22:48Z
  Finalizers:
    chaos-mesh/records
  Generate Name:  pod-failure-9gsf5-
  Generation:     6
  Managed Fields:
    API Version:  chaos-mesh.org/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"chaos-mesh/records":
        f:generateName:
        f:labels:
          .:
          f:chaos-mesh.org/controlled-by:
          f:chaos-mesh.org/workflow:
        f:ownerReferences:
          .:
          k:{"uid":"837e836f-c5f5-4ce0-b4a2-2ef5680fd9c9"}:
            .:
            f:apiVersion:
            f:blockOwnerDeletion:
            f:controller:
            f:kind:
            f:name:
            f:uid:
      f:spec:
        .:
        f:action:
        f:gracePeriod:
        f:mode:
        f:selector:
          .:
          f:labelSelectors:
            .:
            f:app.kubernetes.io/component:
          f:namespaces:
      f:status:
        .:
        f:conditions:
        f:experiment:
          .:
          f:containerRecords:
          f:desiredPhase:
    Manager:    chaos-controller-manager
    Operation:  Update
    Time:       2021-07-14T06:22:48Z
  Owner References:
    API Version:           chaos-mesh.org/v1alpha1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  WorkflowNode
    Name:                  pod-failure-9gsf5
    UID:                   837e836f-c5f5-4ce0-b4a2-2ef5680fd9c9
  Resource Version:        906201
  UID:                     002945bc-8e33-45e2-acfa-347c2d2e1ed1
Spec:
  Action:        pod-failure
  Grace Period:  0
  Mode:          one
  Selector:
    Label Selectors:
      app.kubernetes.io/component:  pd
    Namespaces:
      tidb-cluster
Status:
  Conditions:
    Reason:  
    Status:  False
    Type:    AllRecovered
    Reason:  
    Status:  False
    Type:    Paused
    Reason:  
    Status:  True
    Type:    Selected
    Reason:  
    Status:  True
    Type:    AllInjected
  Experiment:
    Container Records:
      Id:            tidb-cluster/basic-pd-2
      Phase:         Injected
      Selector Key:  .
    Desired Phase:   Run
Events:
  Type    Reason           Age   From          Message
  ----    ------           ----  ----          -------
  Normal  FinalizerInited  12m   finalizer     Finalizer has been inited
  Normal  Started          12m   desiredphase  Experiment has started
  Normal  Updated          12m   records       Successfully update records of resource
  Normal  Updated          12m   finalizer     Successfully update finalizer of resource
  Normal  Updated          12m   desiredphase  Successfully update desiredPhase of resource
  Normal  Applied          12m   records       Successfully apply chaos for tidb-cluster/basic-pd-2
  Normal  Updated          12m   records       Successfully update records of resource
```
