### ISSUE TITLE
Content error on dashboard in creating a new experiment by YAML.

### ISSUE THREAD

**Issue by FingerLeader** [chaos-mesh/chaos-mesh#2116]
## Bug Report

**What version of Kubernetes are you using?**
client:v1.21.2
server:v1.21.2

**What version of Chaos Mesh are you using?**
```
Controller manager Version: version.Info{GitVersion:"master-g2bc0fa81544659", GitCommit:"2bc0fa815446599852116ac0dfb612f659376745", BuildDate:"2021-07-12T09:58:17Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}
```
**What did you do?**
I created a new experiment by YAML on dashboard.
This is my configuration:
```
kind: TimeChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: clock
  namespace: tidb-cluster
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  selector:
    namespaces:
      - tidb-cluster
    pods:
      tidb-cluster:
        - basic-pd-0
    labelSelectors:
      app.kubernetes.io/component: pd
  mode: one
  timeOffset: '-10m100ns'
  clockIds:
    - CLOCK_REALTIME

```

**What did you expect to see?**
Dashboard creates an experiment which excatly same to my YAML. 
**What did you see instead?**
It only fill namespace selector, label selector and name correctly, timeoffset is empty, pods are all displayed and selected.
