### ISSUE TITLE
Changing definition of an expriment on dashboard failed.

### ISSUE THREAD

**Issue by FingerLeader** [chaos-mesh/chaos-mesh#2117]
## Bug Report

**What version of Kubernetes are you using?**
client:v1.21.2
server:v1.21.2

**What version of Chaos Mesh are you using?**
```
Controller manager Version: version.Info{GitVersion:"master-g2bc0fa81544659", GitCommit:"2bc0fa815446599852116ac0dfb612f659376745", BuildDate:"2021-07-12T09:58:17Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**
I updated definition of an experiment on dashboard. 
This is my configuration:
```
ind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: bbb
  namespace: tidb-cluster
  annotations:
    experiment.chaos-mesh.org/pause: 'false'
spec:
  selector:
    namespaces:
      - tidb-cluster
    labelSelectors:
      app.kubernetes.io/component: tidb
  mode: one
  action: bandwidth
  bandwidth:
    rate: 20 kbps
    limit: 100
    buffer: 998
    peakrate: 0
    minburst: 0
  direction: to
```
I changed rate to 10 kbps
**What did you expect to see?**
The configuration changed.
**What did you see instead?**
The dashboard shows updated successfully. But it is the same as before after I refresh browser.
