### ISSUE TITLE
Is Namespace selector too heavy?

### ISSUE THREAD

**Issue by RenxuanW** [chaos-mesh/chaos-mesh#2283]
## Question

We have 4 namespaces (say, n1-n4), each has 10-20 pods. We are trying to inject network larencies between <n1, n3>, <n1, n4>, <n2, n3> and <n2, n4>. We are using the [Namespace selector](https://github.com/chaos-mesh/chaos-mesh/blob/8bb47bce8769/api/v1alpha1/selector.go#L44). We find that the first experiment can be injected pretty quick. The second injection always time out. Is Namespace selector too heavy?

We are using an older version (v0.0.0-20210728073817-92f5e71c799f) that the [PodSelectorSpec](https://github.com/chaos-mesh/chaos-mesh/blob/8bb47bce8769/api/v1alpha1/selector.go#L41) is still named SelectorSpec, and located in common_types.go.

**Comment by STRRL** [comment]
Hi @RenxuanW, which version of Chaos Mesh are you using? And could you provide the definition (in YAML) of each chaos experience? I could not get what the "first experiment" and `second injection` actually are. :heart:

**Comment by RenxuanW** [comment]
Hi @STRRL, thank you for your response! We are using chaos-mesh v1.2.3. By `first` and `second`, I just mean network latencies between <n1, n3> and <n1, n4>, respectively.

The yaml contents are
```
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: iczilhwvblgxgeauhmsmhtzgeebcyw3l
  namespace: renxuan-primary
  labels: null
  annotations: null
spec:
  action: delay
  mode: all
  value: ''
  selector:
    namespaces:
      - renxuan-primary
  duration: 998h
  scheduler:
    cron: '@every 999h'
  delay:
    latency: 50ms
    correlation: '0'
    jitter: 0ms
  direction: both
  target:
    selector:
      namespaces:
        - renxuan-remote
    mode: all
    value: ''
```
and
```
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: zaexysej9vhdxt6uu5g9bhljbdhhhuj5
  namespace: renxuan-primary
  labels: null
  annotations: null
spec:
  action: delay
  mode: all
  value: ''
  selector:
    namespaces:
      - renxuan-primary
  duration: 998h
  scheduler:
    cron: '@every 999h'
  delay:
    latency: 50ms
    correlation: '0'
    jitter: 0ms
  direction: both
  target:
    selector:
      namespaces:
        - renxuan-remote-satellite
    mode: all
    value: ''
```
Looks identical expect for the namespace.
