### ISSUE TITLE
Chaos Dashboard cant create an experiment due to no namespace or label selectors

### ISSUE THREAD

**Issue by andrewgkew** [chaos-mesh/chaos-mesh#2306]
## Bug Report

**What version of Kubernetes are you using?**
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

**What version of Chaos Mesh are you using?**
Controller manager Version: version.Info{GitVersion:"v2.0.0", GitCommit:"8055e259680adbedd728ca121b33ce2f94f72aac", BuildDate:"2021-07-23T07:27:10Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**
Installed using helm

helm repo add chaos-mesh https://charts.chaos-mesh.org
helm install chaos-mesh chaos-mesh/chaos-mesh   --version v2.0.0   --namespace chaos-mesh

**What did you expect to see?**
I can access the chaos dashboard which is a really great tool and I would expected to be able to see my namespaces and label selectors to be able to create an experiment. 

**What did you see instead?**
When I try to create an experiment and define my targets there are no values in my namespace or label selector drop down and I cant put any values into the fields

When I click the dropdowns they say no options

Also at the very top the namespace selector only has the all option

**Comment by andrewgkew** [comment]
Following the interactive demo too I also tried adding the RBAC permissions and generating a token and applying that too but no luck

```
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: account-default-viewer-wqjot

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: role-default-viewer-wqjot
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups:
  - chaos-mesh.org
  resources: [ "*" ]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-default-viewer-wqjot
  namespace: default
subjects:
- kind: ServiceAccount
  name: account-default-viewer-wqjot
  namespace: default
roleRef:
  kind: Role
  name: role-default-viewer-wqjot
  apiGroup: rbac.authorization.k8s.io
```

```
kubectl describe -n default secrets account-default-viewer-wqjot
```

**Comment by iguoyr** [comment]
@andrewgkew Hi, is the `default` namespace your target namespace? I noticed that the role and the rolebinding you posted only work in `default` namespace, which means that the dashboard can only fetch resources(like labels or pods) in `default` namespace.

**Comment by iguoyr** [comment]
@andrewgkew And if you want to have access cluster-wide, try to use clusterRole and clusterRoleBinding which maybe a better choice :)

**Comment by andrewgkew** [comment]
@iguoyr - thanks for the tip on setting Custer roles instead.

I tried the following and it didnt work

```
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: account-default-viewer-wqjot

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-default-viewer-wqjot
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups:
  - chaos-mesh.org
  resources: [ "*" ]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-default-viewer-wqjot
subjects:
- kind: ServiceAccount
  name: account-default-viewer-wqjot
  namespace: default
roleRef:
  kind: ClusterRole
  name: role-default-viewer-wqjot
  apiGroup: rbac.authorization.k8s.io
```

Then got the token and add it in the settings field in the dashboard and still nothing in the drop down.
I got the CRDs to work when using kubectl which is great just want it to work through dashboard now if possible please

Can you help?
