### ISSUE TITLE
Creating `StressChaos` on dashboard will cause unexpected arguments

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#2343]
Creating `StressChaos` on dashboard will generate such spec:

```yaml
Spec:
  Duration:  
  Mode:      one
  Selector:
    Namespaces:
      skywalking
  Stressors:
    Cpu:
      Load:     100
      Workers:  1
    Memory:
      Workers:  0
```

However, the behavior of  `memory: workers: 0` and `memory: nil` is different. For `memory: workers: 0`, the `stress-ng` will be passed arguments `--vm 0 --vm-keep`, and will spawn a lot of workers to eat memory. For `memory: nil`, the `stress-ng` will not have related arguments.

The implementation of `StressChaos` should ignore the zero workers config (and don't pass related argument to `stress-ng`), as the behavior of zero worker is not well defined in the document of `stress-ng`.
