### ISSUE TITLE
ui: duplicate names detected

### ISSUE THREAD

**Issue by iguoyr** [chaos-mesh/chaos-mesh#2503]
## Bug Report

**What version of Kubernetes are you using?**

**What version of Chaos Mesh are you using?**

this issue is related to https://github.com/chaos-mesh/chaos-mesh/pull/2308

**What did you do?**

1. create a new workflow
2. create a `httprequest` task, submit it
3. back to edit this `httprequest` task, submit it again, and dashboard will show this error message

**What did you expect to see?**
dashboard works without error message

**What did you see instead?**

<img width="1552" alt="截屏2021-11-09 下午2 31 52" src="https://user-images.githubusercontent.com/11804251/140908008-77c67690-4102-49d3-8555-a95ff66994af.png">

**Output of chaosctl**

**Comment by STRRL** [comment]
This issue is not introduced by  #2308, it has been also existed for a while, like #2504.

I think we would fix it in the next PRs, but not #2308.

**Comment by victoriacheng15** [comment]
Tested on the latest `master` branch (`master-g12bba257c5577c`). The reported `"Duplicate names detected"` validation error no longer occurs because the legacy form-based workflow UI was removed in PR #4698.

However, in the new whiteboard UI (`NewWorkflowNext`), naming two connected nodes identically results in only one child and template being generated (the second one is silently discarded). If they have different names, both are generated successfully (not sure if this is intended behavior or a bug) 🤔:

### Reproduction Steps:
  1. Deploy a dummy pod in your cluster to satisfy target validation:
     ```bash
     kubectl run nginx-target --image=nginx --labels="app=nginx"
     ```
  2. Compile and start the local dashboard:
     ```bash
     UI=1 make local/chaos-dashboard
     ./bin/chaos-dashboard
     ```
  3. Open your browser to `http://localhost:2333`.
  4. Generate a token for the default ServiceAccount: `kubectl create token default`, paste it in, and log in.
  5. Go to **Workflows** -> **New Workflow** in the sidebar.
  6. Under **Chaos Nodes** (e.g., Kubernetes -> PodChaos) in the left sidebar, click **pod-kill** to add it to the whiteboard canvas.
  7. Click the node on the canvas to open the right-side: 
      - Set the **Name** to `chaos-a`
      - Select namespace `default` 
      - Target labels `app: nginx`
  8. Repeat step 7 again for 2nd node.
  9. Connect the two nodes by dragging an arrow from the first `chaos-a` node to the second `chaos-a` node (linking them in series).
  10. Observe that the UI successfully allows duplicate names without displaying any `"Duplicate names detected"` warning.
  11. Click the **Submit Workflow** button in the top-right.

  ### Resulting YAML (Case A: Both named `chaos-a`):
  The second node is silently discarded from both the `templates` array and the parent's `children` array:
  ```yaml
  apiVersion: chaos-mesh.org/v1alpha1
  kind: Workflow
  metadata:
    name: ''
    namespace: ''
  spec:
    entry: entry
    templates:
      - name: entry
        templateType: Serial
        children:
          - chaos-a
      - name: chaos-a
        templateType: PodChaos
        podChaos:
          action: pod-kill
          selector:
            namespaces:
              - default
            labelSelectors:
              app: nginx
          mode: all
  ```

  ### Expected YAML (Case B: Nodes named `chaos-a` and `chaos-b` respectively):
  If the second node is renamed to `chaos-b`, both are correctly preserved:
  ```yaml
  apiVersion: chaos-mesh.org/v1alpha1
  kind: Workflow
  metadata:
    name: ''
    namespace: ''
  spec:
    entry: entry
    templates:
      - name: entry
        templateType: Serial
        children:
          - chaos-a
          - chaos-b
      - name: chaos-a
        templateType: PodChaos
        podChaos:
          action: pod-kill
          selector:
            namespaces:
              - default
            labelSelectors:
              app: nginx
          mode: all
      - name: chaos-b
        templateType: PodChaos
        podChaos:
          action: pod-kill
          selector:
            namespaces:
              - default
            labelSelectors:
              app: nginx
          mode: all
```
