### ISSUE TITLE
Dashboard: format YAML file

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#2507]
## Feature Request

**Is your feature request related to a problem? Please describe:**
  

latest, v2.0.x

**Describe the feature you'd like:**
  

As usual, we use the following format to define chaos object: 
```
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: burn-cpu
  namespace: chaos-testing
```

Define `apiVersion` and then `kind`, but the YAML file download from Chaos Dashboard got the wrong order:

![image](https://user-images.githubusercontent.com/22956341/141114573-e21127e1-fb1b-4934-a84a-c61ca41b741a.png)

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**
