### ISSUE TITLE
NamespaceChaos - namespace-deleted

### ISSUE THREAD

**Issue by andylibrian** [chaos-mesh/chaos-mesh#2567]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I would like to run a chaos test where namespaces are deleted. I use GitOps and I would expect that the namespace and the resources inside it would be recreated shortly.

**Describe the feature you'd like:**

I would imagine a kind of "NamespaceChaos":

```
apiVersion: chaos-mesh.org/v1alpha1
kind: NamespaceChaos
metadata:
  name: namespace-deleted-example
  namespace: chaos-testing
spec:
  action: namespace-deleted
```

**Teachability, Documentation, Adoption, Migration Strategy:**

It would be similar to existing chaos types. This one is for namespace.
