### ISSUE TITLE
Some port configurations in helm templates are hardcoded 

### ISSUE THREAD

**Issue by TangliziGit** [chaos-mesh/chaos-mesh#2569]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Some port configurations in helm templates `/helm/chaos-mesh/templates/controller-manager-deployment.yaml` are hardcoded:
```yaml
ports:
  - name: webhook
    containerPort: 9443
  - name: http
    containerPort: 10080
  {{- if .Values.enableProfiling }}
  - name: pprof
    containerPort: 10081
  {{- end }}
  {{- if .Values.enableCtrlServer }}
  - name: ctrl
    containerPort: 10082
{{- end 
```

**Describe the feature you'd like:**

These port configurations should be exposed at the helm `values.yaml` level for users to customize them, like chaos-dashboard:
```yaml
ports:
  - name: http
    containerPort: {{ .Values.dashboard.env.LISTEN_PORT }
```

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**
