### ISSUE TITLE
Unable to delete bandwidth NetworkChaos with bad minburst

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2572]
## Bug Report

**What version of Kubernetes are you using?**

kubernetes 1.22.3

**What version of Chaos Mesh are you using?**

master, 9a71f58fd8ea54267796bab16ce0f78b3eabcf34

**What did you do?**

workload:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-3
  name: nginx-3
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-3
  template:
    metadata:
      labels:
        app: nginx-3
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged
        name: nginx-unprivileged
      restartPolicy: Always

```

NetworkChaos:

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: networkchaos-1
  namespace: default
spec:
  action: bandwidth
  mode: all
  selector:
    labelSelectors:
      "app": nginx-3
  bandwidth:
    rate: 2mbps
    limit: 1
    buffer: 4096
    peakrate: 10
    minburst: 0
```

Notice that `minburst: 0` would setup `mtu 0` with the`tc-tbf`, which is **invalid**.

Then I try to delete this NetworkChaos.

**What did you expect to see?**

1. Validation Webhook could reject the invalid configuration for bandwidth
2. I could delete this invalid NetworkChaos

**What did you see instead?**

I create this NetworkChaos Object and I could not delete it anymore.

**Output of chaosctl**
