### ISSUE TITLE
PhysicalMachineChaos: mode  not supported

### ISSUE THREAD

**Issue by WangXiangUSTC** [chaos-mesh/chaos-mesh#2815]
## Bug Report

**What version of Chaos Mesh are you using?**

master: ea9c6cc646a17fe0912128f157cb1c4983f4ced7

**What did you do?**
create a PhysicalMachineChaos, the YAML file:

```YAML
kind: PhysicalMachineChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: loss
spec:
  action: network-loss
  address:
    - http://172.16.173.129:31767
  uid: 810acd21-050e-48a8-b310-ade764bf97f2
  network-loss:
    correlation: '10'
    device: ens33
    ip-protocol: all
    hostname: baidu.com
    percent: '50'
```

**What did you expect to see?**

Experiment run success.

**What did you see instead?**

see error log in controller manager:

```log
1.6427557001473231e+09  ERROR   records fail to select  {"error": "mode  not supported",
"errorVerbose": "mode  not supported\ngithub.com/chaos-mesh/chaos-mesh/pkg/selector/gener
ic.FilterObjectsByMode\n\t/Users/xiang/newWorld/gopath/src/github.com/chaos-mesh/chaos-me
sh/pkg/selector/generic/mode.go:92\ngithub.com/chaos-mesh/chaos-mesh/pkg/selector/physica
lmachine.filterPhysicalMachinesByMode\n\t/Users/xiang/newWorld/gopath/src/github.com/chao
s-mesh/chaos-mesh/pkg/selector/physicalmachine/selector.go:255\ngithub.com/chaos-mesh/cha
os-mesh/pkg/selector/physicalmachine.(*SelectImpl).Select\n\t/Users/xiang/newWorld/gopath
/src/github.com/chaos-mesh/chaos-mesh/pkg/selector/physicalmachine/selector.go:81\nreflec
t.Value.call\n\t/usr/local/go/src/reflect/value.go:543\nreflect.Value.Call\n\t/usr/local/
go/src/reflect/value.go:339\ngithub.com/chaos-mesh/chaos-mesh/pkg/selector.(*Selector).Se
lect\n\t/Users/xiang/newWorld/gopath/src/github.com/chaos-mesh/chaos-mesh/pkg/selector/se
lector.go:49\ngithub.com/chaos-mesh/chaos-mesh/controllers/common/records.(*Reconciler).R
econcile\n\t/Users/xiang/newWorld/gopath/src/github.com/chaos-mesh/chaos-mesh/controllers
/common/records/controller.go:83\ngithub.com/chaos-mesh/chaos-mesh/controllers/common/pip
eline.(*Pipeline).Reconcile\n\t/Users/xiang/newWorld/gopath/src/github.com/chaos-mesh/cha
os-mesh/controllers/common/pipeline/pipeline.go:73\nsigs.k8s.io/controller-runtime/pkg/in
ternal/controller.(*Controller).Reconcile\n\t/tmp/go/pkg/mod/sigs.k8s.io/controller-runti
me@v0.11.0/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/
internal/controller.(*Controller).reconcileHandler\n\t/tmp/go/pkg/mod/sigs.k8s.io/control
ler-runtime@v0.11.0/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-run
time/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/tmp/go/pkg/mod/sigs.k8
s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/co
ntroller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/tmp/go/pkg/mod/s
igs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227\nruntime.
goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1133"}
```
