### ISSUE TITLE
IOChaos: default percent field not work

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#2843]
## Bug Report

**What version of Kubernetes are you using?**
 

1.20.0 
**What version of Chaos Mesh are you using?**

v2.1.1
**What did you do?**
 

Create an IOChaos experiment and set the `percent` field empty. According to chaos mesh docs, the default `percent` field is `100`. But when I set it to empty, the chaos action didn't work.  

```
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-delay-example
spec:
  action: latency
  mode: one
  selector:
    labelSelectors:
      statefulset.kubernetes.io/pod-name: advanced-tidb-tikv-0
    namespaces:
      - tidb-c0
  volumePath: /var/lib/tikv
  path: /var/lib/tikv/raft/*
  delay: "1s"
  ```

When I set the `percent` to `100`, this chaos experiment worked. 

**What did you expect to see?**
 

**What did you see instead?** 

IO delay action was working. 

**Output of chaosctl**
