### ISSUE TITLE
qestions about scheduler

### ISSUE THREAD

**Issue by vrublevskyyy** [chaos-mesh/chaos-mesh#2897]
## Question
Hello

1) If I can add workflow(kind) execution in the scheduler? (I would like to add a few steps to the scheduler notification in slack + chaos test)
2) Can I choose many nodeSecectors zones?

I was trying to add my workflow in schedule:
```
kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: chaos-mesh-sheduler
spec:
  schedule: 05 12 * * 1
  startingDeadlineSeconds: 3
  concurrencyPolicy: Forbid
  historyLimit: 4
  type: NetworkChaos
  networkChaos:
    selector:
      namespaces:
        - traefik-api
      labelSelectors:
        app.kubernetes.io/name: traefik-api
      nodeSelectors:
        failure-domain.beta.kubernetes.io/zone: ru-central1-a
        failure-domain.beta.kubernetes.io/zone: ru-central1-b #  add another zone like this
        failure-domain.beta.kubernetes.io/zone: ru-central1-c #  add another zone like this
    mode: one
    action: partition
    duration: 5m
    direction: to
```

**Comment by Hexilee** [comment]
1. Yes, you can embed workflow in the scheduler.
2. Yes, you can choose many nodeSecectors zones.

**Comment by vrublevskyyy** [comment]
> 1. Yes, you can embed workflow in the scheduler.
> 2. Yes, you can choose many nodeSecectors zones.

Could you show examples? I didn't find them in the official documentation

**Comment by Hexilee** [comment]
Just use the `Workflow` type in the scheduler:

```yaml
kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: chaos-mesh-sheduler
spec:
  schedule: 05 12 * * 1
  startingDeadlineSeconds: 3
  concurrencyPolicy: Forbid
  historyLimit: 4
  type: Workflow
  workflow:
      entry: the-entry
      templates:
        - name: the-entry
          templateType: Parallel
          deadline: 240s
          children:
            - workflow-stress-chaos
            - workflow-network-chaos
            - workflow-pod-chaos-schedule
        - name: workflow-network-chaos
          templateType: NetworkChaos
          deadline: 20s
          networkChaos:
            direction: to
            action: delay
            mode: all
            selector:
              labelSelectors:
                'app': 'hello-kubernetes'
            delay:
              latency: '90ms'
              correlation: '25'
              jitter: '90ms'
        - name: workflow-pod-chaos-schedule
          templateType: Schedule
          deadline: 40s
          schedule:
            schedule: '@every 2s'
            type: 'PodChaos'
            podChaos:
              action: pod-kill
              mode: one
              selector:
                labelSelectors:
                  'app': 'hello-kubernetes'
        - name: workflow-stress-chaos
          templateType: StressChaos
          deadline: 20s
          stressChaos:
            mode: one
            selector:
              labelSelectors:
                'app': 'hello-kubernetes'
            stressors:
              cpu:
                workers: 1
                load: 20
                options: ['--cpu 1', '--timeout 600']
```
