### ISSUE TITLE
workflows: endless events

### ISSUE THREAD

**Issue by imlonghao** [chaos-mesh/chaos-mesh#2901]
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:06:15Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.3", GitCommit:"01849e73f3c86211f05533c2e807736e776fcf29", GitTreeState:"clean", BuildDate:"2021-02-17T12:35:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**

```
Controller manager Version: version.Info{GitVersion:"v2.1.2", GitCommit:"24a1f565ed000ba8738a4ed568b4e9a0925fe2fb", BuildDate:"2021-12-29T11:43:40Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

Create a workflow

```
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: sleep
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      deadline: 10s
      children:
        - sleep
    - name: sleep
      templateType: Suspend
      deadline: 10s
```

**What did you expect to see?**

After the workflow is accomplished, no more event can be generated.

**What did you see instead?**

Events still generate everyday, about 8-12 events per day.

```
sleep - workflow accomplished
entry-m6wrm - node accomplished
sleep - workflow accomplished
entry-m6wrm - node accomplished
[...]
```

**Output of chaosctl**

N
