### ISSUE TITLE
Etcd Pod's statu will be error when inject io latency to etcd

### ISSUE THREAD

**Issue by zhuwenxing** [chaos-mesh/chaos-mesh#2946]
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
**What version of Chaos Mesh are you using?**

```
Controller manager Version: version.Info{GitVersion:"v2.0.3", GitCommit:"c417f2b9a2adad567a00742efdec0d87f15807ac", BuildDate:"2021-10-19T08:12:23Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}
```
**What did you do?**

inject io-latency into etcd pod
yaml config:
```
kind: IOChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: test-etcd-io-latency
  namespace: chaos-testing
spec:
  selector:
    namespaces:
      - chaos-testing
    labelSelectors:
      app.kubernetes.io/name: etcd
      app.kubernetes.io/instance: milvus-chaos
  mode: all
  action: latency
  delay: 200ms
  methods:
    - read
    - write
    - flush
  percent: 100
  volumePath: /bitnami/etcd
```

**What did you expect to see?**
io-latency injection success and that takes effect, like command `touch test.txt` need some time to return result

**What did you see instead?**
io-latency injection success
```
Events:
  Type    Reason           Age   From          Message
  ----    ------           ----  ----          -------
  Normal  FinalizerInited  37m   finalizer     Finalizer has been inited
  Normal  Started          37m   desiredphase  Experiment has started
  Normal  Updated          37m   finalizer     Successfully update finalizer of resource
  Normal  Updated          37m   records       Successfully update records of resource
  Normal  Updated          37m   desiredphase  Successfully update desiredPhase of resource
  Normal  Updated          37m   records       Successfully update records of resource
  Normal  Applied          37m   records       Successfully apply chaos for chaos-testing/milvus-chaos-etcd-0/etcd
  Normal  Updated          37m   records       Successfully update records of resource
```
But this injection will cause etcd pod error
```
{"level":"info","ts":"2022-02-25T07:59:29.218Z","caller":"mvcc/index.go:214","msg":"compact tree index","revision":2133}
{"level":"info","ts":"2022-02-25T07:59:29.219Z","caller":"mvcc/kvstore_compaction.go:57","msg":"finished scheduled compaction","compact-revision":2133,"took":"498.725µs"}
unexpected fault address 0x7ff9f6445000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7ff9f6445000 pc=0x9c8d82]

goroutine 85 [running]:
runtime.throw(0x1201763, 0x5)
	/home/remote/sbatsche/.gvm/gos/go1.16.3/src/runtime/panic.go:1117 +0x72 fp=0xc0005b4120 sp=0xc0005b40f0 pc=0x4385d2
runtime.sigpanic()
	/home/remote/sbatsche/.gvm/gos/go1.16.3/src/runtime/signal_unix.go:741 +0x268 fp=0xc0005b4158 sp=0xc0005b4120 pc=0x44fce8
go.etcd.io/bbolt.(*DB).page(...)
	/home/remote/sbatsche/.gvm/pkgsets/go1.16.3/global/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:933
go.etcd.io/bbolt.(*Tx).page(...)
	/home/remote/sbatsche/.gvm/pkgsets/go1.16.3/global/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:617
go.etcd.io/bbolt.(*Bucket).pageNode(0xc000c16e18, 0x2d, 0xc0000d9000, 0xc0005b4208)
	/home/remote/sbatsche/.gvm/pkgsets/go1.16.3/global/pkg/mod/go.etcd.io/bbolt@v1.3.6/bucket.go:726 +0xa2 fp=0xc0005b41b8 sp=0xc0005b4158 pc=0x9c8d82
```

**Output of chaosctl**
