### ISSUE TITLE
zero value config of httpchaos replace action cause wrong behavior

### ISSUE THREAD

**Issue by Hexilee** [chaos-mesh/chaos-mesh#2988]
## Bug Report

**What version of Chaos Mesh are you using?**
Latest

**What did you do?**

Apply following config.

```yaml
kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: http-fault
  namespace: default
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: nginx
  mode: all
  target: Request
  port: 80
  path: /*
  replace:
    code: 502
```

**What did you expect to see?**

HTTPChaos works.

**What did you see instead?**

```
400 Fail to apply, unknown variant ``, expected `TEXT` or `BASE64`.
```

**The possible cause**
In https://github.com/chaos-mesh/chaos-mesh/pull/2555, we introduce the chaos-tproxy v0.4.x, which needs a compatibility layer to HTTPChaos config. However, the zero value of field [`Body`](https://github.com/chaos-mesh/chaos-mesh/blob/5005201fdab583f46bef71c2e9e536f6766cc7b6/pkg/chaosdaemon/tproxyconfig/config.go#L179) in ` PodHttpChaosReplaceActions` is wrong, we should replace it with a pointer.
