### ISSUE TITLE
IoChaos "EACCES: Permission denied" on chaos-daemon.log

### ISSUE THREAD

**Issue by jasonstack** [chaos-mesh/chaos-mesh#2995]
## Bug Report

**What version of Kubernetes are you using?**
Google Kubernetes Engine (GKE) 1.20

**What version of Chaos Mesh are you using?**
Chart 0.4.1

**What did you do?**
Inject IoChaos

**What did you expect to see?**
IO operation failed

**What did you see instead?**
IO operation didn't fail.

I think `privileged` is default to `true` in `Chart 0.4.1`

From `Chaos-daemon.log`:
```
Error: source: /cassandra-data, target: /__chaosfs__cassandra-data__

Caused by:
    EACCES: Permission denied

Stack backtrace:
   0: <E as anyhow::context::ext::StdError>::ext_context
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.38/src/backtrace.rs:26
      anyhow::context::<impl anyhow::Context<T,E> for core::result::Result<T,E>>::context::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.38/src/context.rs:50
      core::result::Result<T,E>::map_err
             at ./rustc/16957bd4d3a5377263f76ed74c572aad8e4b7e59/src/libcore/result.rs:612
      anyhow::context::<impl anyhow::Context<T,E> for core::result::Result<T,E>>::context
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.38/src/context.rs:50
      toda::mount::MountsInfo::move_mount
             at src/mount.rs:42
   1: toda::mount_injector::MountInjector::mount
             at src/mount_injector.rs:115
   2: toda::inject
             at src/main.rs:88
      toda::main
             at src/main.rs:165
   3: std::rt::lang_start::{{closure}}
             at ./rustc/16957bd4d3a5377263f76ed74c572aad8e4b7e59/src/libstd/rt.rs:67
   4: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
      std::panicking::try::do_call
             at src/libstd/panicking.rs:342
      std::panicking::try
             at src/libstd/panicking.rs:319
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:51
   5: main
   6: <unknown>
   7: _start
2022-03-07T13:48:19.386Z	INFO	background-process-manager	process stopped	{"pid": 27609}
```

IoChaos yaml:
```
apiVersion: chaos-mesh.org/v1alpha1
kind: IoChaos
metadata:
  name: cassandra-io-error
spec:
  action: fault
  mode: all
  selector:
    labelSelectors:
      "app.kubernetes.io/component": "cassandra-installation"
  volumePath: /cassandra-data
  path: /cassandra-data/**/*
  methods:
    - READ
    - WRITE
    - OPEN
  errno: 2
  percent: 100
  duration: "300s"
  scheduler:
    cron: "@every 10m"
```
