### ISSUE TITLE
different behaviour between memStress and stress-ng after OOM Killing

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2999]
## Bug Report

**What version of Kubernetes are you using?**

N/A

**What version of Chaos Mesh are you using?**

memStress in `master` branch
(using stress-ng with `2.1.1` as controlled group)

**What did you do?**

create a StressChaos with extremely large size aims to oom kill:

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: burn-cpu
spec:
  mode: one
  selector:
    labelSelectors:
      "app": "nginx"
  stressors:
    memory:
      size: 1000Gi
      workers: 1
  duration: "5m"
``` 

**What did you expect to see?**

`memStress` should act like `stress-ng`:
- keep allocating memory even after oom killing

**What did you see instead?**

 `memStress` was killed, and StressChaos would also failed to recover

It relates to the process model of `stress-ng`, stress-ng would create new sub-processes (not sure process or thread) to allocate the memory, so oom killer would only kill the sub-process, then `stress-ng` main process would keel spawning new sub process.

But `memStress` would only work in one process, after oom killing, it did gone.

I think we could update the memStress, using `stress-ng` process model as a reference, for keeping the consistent behavior.

**Output of chaosctl**
