### ISSUE TITLE
Failed to apply chaos: rpc error: code = Unknown desc = expected containerd:// but got docker

### ISSUE THREAD

**Issue by rongGreate** [chaos-mesh/chaos-mesh#3057]
## Bug Report

**What version of Kubernetes are you using?**

v1.22.3

**What version of Chaos Mesh are you using?**

v2.1.3

**What did you do?**

create JVM experiments

**What did you expect to see?**

experiments can work

**What did you see instead?**
<img width="358" alt="image" src="https://user-images.githubusercontent.com/94539012/159877603-ca40611b-6ac2-46f6-b354-15f720e9b2ff.png">

**Output of chaosctl**
<img width="376" alt="image" src="https://user-images.githubusercontent.com/94539012/159877531-4ffebe08-c6a6-4394-8569-79bc9c4c9461.png">

**Comment by fewdan** [comment]
It seems that you should specify the container runtime at installation. Can you describe your kubernetes environment (what is your kubernetes container runtime)? And which command did you install chaos-mesh with?

**Comment by rongGreate** [comment]
the problem was sloved, now i use `helm repo add chaos-mesh https://charts.chaos-mesh.org`，thanks your reply

**Comment by osouza-de** [comment]
Hey there. I am glad you managed to solve your issue.

May I ask what it was and how did you solved it? 'Cause I'm now facing a similar one.

Thanks in advance.

**Comment by fewdan** [comment]
@osouza-de 
Usually, this problem is because the container runtime of your kubernetes cluster is different from the container runtime specified by the chaos mesh.
So, you can first confirm the container runtime of your kubernetes cluster, and recall how the chaos mesh was installed at that time.

**Comment by osouza-de** [comment]
oh, thanks!

The issue, in my case,  was fixed by setting "kvm2" instead of "docker" as minikube driver:

`minikube start --driver=kvm2`

I followed [this tutorial](https://minikube.sigs.k8s.io/docs/drivers/kvm2/) to get it done.

**Comment by 2022MT03512** [comment]
I too have this issue 
Failed to apply chaos: rpc error: code = Unknown desc = expected docker:// but got container

**Comment by Gittysri** [comment]
@2022MT03512 

Did you find the solution to this issue? Cause I'm facing similar one

Thanks in Advance

**Comment by hecalzu** [comment]
@2022MT03512 @Gittysri 
To fix "rpc error: code = Unknown desc = expected docker:// but got container", check what your env is using for container runtime. It seems like it is containerd but just in case use "kubectl get nodes -o wide" there, you should be able to see something like CONTAINER-RUNTIME column. there you'll find your needed value (containerd://1.7.5 in my case) to select the installation command from https://chaos-mesh.org/docs/production-installation-using-helm/

This worked for me.

**Comment by xavier-romero** [comment]
Facing same issue.
I can run `PodChaos` test against my pod, but I can't run `StressChaos` against that same pod using same config and selector.

PodChaos:
```
        kind: PodChaos
        apiVersion: chaos-mesh.org/v1alpha1
        spec:
          action: pod-failure
          duration: 5s
          mode: all
          selector:
            labelSelectors:
              kurtosistech.com/id: contracts-001

```
-> works OK.

StressChaos:
```
        kind: StressChaos
        apiVersion: chaos-mesh.org/v1alpha1
        spec:
          mode: all
          selector:
            labelSelectors:
              kurtosistech.com/id: contracts-001

```
-> does NOT work
`Failed to apply chaos: rpc error: code = Unknown desc = expected containerd:// but got docker://7f7e`
