### ISSUE TITLE
RabbitMQ keeps failing with IOChaos

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#3094]
## Question

Asked by an adaptor, it is quite weird. RabbitMQ keeps failing when injecting certain IOChaos.

It looks like IOChaos did work well, and the application(rabbitmq) could not tolerate this chaos.
 
For more detail, see the attachments:

IOChaos:

```yaml
kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: openstack
  name: k8s-openstack-rabbitmq-io-fault-20220210
  annotations:
    experiment.chaos-mesh.org/pause: 'false'
spec:
  schedule: '*/4 11-23 * * *'
  startingDeadlineSeconds: 1800
  concurrencyPolicy: Forbid
  historyLimit: 1
  type: IOChaos
  ioChaos:
    selector:
      namespaces:
        - openstack
      labelSelectors:
        app: rabbitmq-ha
    mode: all
    action: fault
    errno: 1
    path: /var/lib/rabbitmq/**/*
    percent: 100
    volumePath: /var/lib/rabbitmq
    duration: 60s

```

```yaml
kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: openstack
  name: k8s-openstack-rabbitmq-io-latency-20220210
  annotations:
    experiment.chaos-mesh.org/pause: 'false'
spec:
  schedule: '*/4 11-23 * * *'
  startingDeadlineSeconds: 1798
  concurrencyPolicy: Forbid
  historyLimit: 1
  type: IOChaos
  ioChaos:
    selector:
      namespaces:
        - openstack
      labelSelectors:
        app: rabbitmq-ha
    mode: all
    action: latency
    delay: 2ms
    path: /var/lib/rabbitmq/**/*
    percent: 100
    volumePath: /var/lib/rabbitmq
    duration: 60s

```

logs:
[chaos-daemon-gzcpb.log](https://github.com/chaos-mesh/chaos-mesh/files/8394618/chaos-daemon-gzcpb.log)
