### ISSUE TITLE
Created a physical disk experiment and it didn't work

### ISSUE THREAD

**Issue by ThreadDao** [chaos-mesh/chaos-mesh#3126]
## Bug Report

**What version of Kubernetes are you using?**

**What version of Chaos Mesh are you using?**

Controller manager Version: version.Info{GitVersion:"v2.1.3", GitCommit:"cbe789587678a5ea28e9b38343d222c1d5ea8657", BuildDate:"2022-01-27T05:15:02Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**

1. Install chaosd on physical  machine
2. Deploy chaos-mesh in k8s cluster
3. Kubectl apply the following yaml, and successfully `physicalmachinechaos.chaos-mesh.org/physical-chaos-disk-fill created`
```
kind: PhysicalMachineChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-testing
  name: physical-chaos-disk-fill
spec:
  action: disk-fill
  address:
    - 10.100.32.147:31767
  disk-fill:
    size: 20G
    path: /tmp
    fill-by-fallocate: true
  duration: 1m
```
4. However no file was created in `/tmp/`

The chaos-mesh controller log
[chaos-controller-54.log](https://github.com/chaos-mesh/chaos-mesh/files/8482609/chaos-controller-54.log)

[chaos-controller-7w.log](https://github.com/chaos-mesh/chaos-mesh/files/8482606/chaos-controller-7w.log)

[chaos-controller-hd.log](https://github.com/chaos-mesh/chaos-mesh/files/8482616/chaos-controller-hd.log)

**What did you expect to see?**
A 20G file is created in /tmp/ to fill the disk

**What did you see instead?**

**Output of chaosctl**
