### ISSUE TITLE
more clear status to tell if the experiment succeed

### ISSUE THREAD

**Issue by xlgao-zju** [chaos-mesh/chaos-mesh#3127]
## Feature Request

**Is your feature request related to a problem? Please describe:**

from existing status, we can hardly to tell if the experiment succeed, or just duration exceeded. e.g.
```yaml
  spec:
    clockIds:
    - CLOCK_REALTIME
    duration: 10s
    mode: one
    selector:
      labelSelectors:
        app: nginx
      namespaces:
      - xlgao
    timeOffset: 10s
  status:
    conditions:
    - reason: ""
      status: "True"
      type: AllRecovered
    - reason: ""
      status: "False"
      type: Paused
    - reason: ""
      status: "True"
      type: Selected
    - reason: ""
      status: "False"
      type: AllInjected
    experiment:
      containerRecords:
      - id: xlgao/nginx-644467cc8b-dv25r/centos
        phase: Not Injected
        selectorKey: .
      desiredPhase: Stop
```

if we do not see the events, we may not know if the record had been injected in the duration.

**Describe the feature you'd like:**

we need a clearer way to know if the record had been injected in the duration.

since a experiment is a stateful resource, I think we should add more fields in status. for this case ,maybe add a bool field in status like `durationExceeded` or something 

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by xlgao-zju** [comment]
for now, I think we need to find the proper way to expose more details of status. and when we find the way, I'd like to file a PR to close this issue. :)

**Comment by xlgao-zju** [comment]
for now, the state machine of record phase is:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/1636894/163309824-34f4e2a2-79ff-4b1c-a085-5f2146487db1.png">

in order to know if the record succeed, we can also add a new phase called `Recovered`. then the new state machine will be like this:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/1636894/163309725-31cde2f0-109b-4f9d-b15c-19d5e2817d0b.png">

**Comment by cwen0** [comment]
> for now, the state machine of record phase is: <img alt="image" width="377" src="https://user-images.githubusercontent.com/1636894/163309824-34f4e2a2-79ff-4b1c-a085-5f2146487db1.png">
> 
> in order to know if the record succeed, we can also add a new phase called `Recovered`. then the new state machine will be like this: <img alt="image" width="597" src="https://user-images.githubusercontent.com/1636894/163309725-31cde2f0-109b-4f9d-b15c-19d5e2817d0b.png">
> 
> after experiment stop, we will know if the record succeed, according to the record phase. if the phase is Recovered: the record succeed Not Injected: the record failed

@xlgao-zju In the new state machine of the record phase, you remove `Not Injected/*`, which is required by `NetworChaos`.

**Comment by xlgao-zju** [comment]
<img width="576" alt="image" src="https://user-images.githubusercontent.com/1636894/163317637-6603bca1-410a-421a-8515-0fcc945e978a.png">


@cwen0 you are right, how about this version of state machine?

**Comment by YangKeao** [comment]
> <img alt="image" width="576" src="https://user-images.githubusercontent.com/1636894/163317637-6603bca1-410a-421a-8515-0fcc945e978a.png">
> 
> @cwen0 you are right, how about this version of state machine?

It sounds good. The `Not Injected` and `Recovered` are actually the same during execution. But I still have another concern:

If the user pause and restart the chaos, and unfortunately, this injection failed. He can still not tell whether it's failed or expired after the duration.

**Comment by xlgao-zju** [comment]
@YangKeao  when we resume the experiment, we can move the state from `Recovered` to `Not Injected`. so the state machine will be like this:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/1636894/163342862-d5cd45b2-d301-4a89-a251-483942200c26.png">

**Comment by xlgao-zju** [comment]
I will file a PR soon, according to this state machine :)

**Comment by Hexilee** [comment]
@xlgao-zju  Hi, in my understanding, the phase `Recovered` and `Not Injected` represent the same meaning for the state machine, but a new variant with the same meaning will make the logic confusing.

If you just want to know if the experiment has injected successfully, how about adding a `inject counter` field to count the injection times?

**Comment by xlgao-zju** [comment]
> the phase Recovered and Not Injected represent the same meaning for the state machine, isn't it?

@Hexilee 

`NotInjected` means the target is not injected yet. the controller could call "Inject" on the target
`Recovered` means the target had been injected and recovered successfully. for now, when we resume a paused experiment, the `Recovered` phase will step to `Not Injected`.  and only when state steps from `Recovered` to `Not Injected`, the controller could call "Inject" on the target

without the `Recovered` state, we can not know if the record has been injected successfully.

> If you just want to know if the experiment has injected successfully, how about adding a inject counter field to count the injection times?

A `inject counter` may not tell us which record has been injected successfully, we can only know the sum.

**Comment by Hexilee** [comment]
> 

The `phase` is mainly read by the state machine, I think `Recovered` and `Not Injected` should be the same state if the state machine does nothing during the state conversion.

We can add a counter for each record, then we can know if the record has been injected successfully.

**Comment by xlgao-zju** [comment]
@cwen0 @STRRL @YangKeao @Hexilee 

since k8s event ttl is a little short, we can put the essential events in the status. and in order to know the sum of injection and recovery, we can add the `injectedCount` and `recoveredCount`.

and then the status will be like this:
```yaml
status:
    conditions:
    - reason: ""
      status: "True"
      type: AllRecovered
    - reason: ""
      status: "False"
      type: Paused
    - reason: ""
      status: "True"
      type: Selected
    - reason: ""
      status: "False"
      type: AllInjected
    experiment:
      containerRecords:
      - id: xlgao/nginx-644467cc8b-dv25r/centos
        phase: Not Injected
        selectorKey: .
        injectedCount: 0
        recoveredCount: 0
        events:
        - type: failed
          stage: inject # inject or recover
          message : "failed to xxxx"
          timestamp : "2022-04-13T09:40:51Z"
      desiredPhase: Stop
```
