### ISSUE TITLE
Do we support defining scheduling rules or creating workflows for experiments of type PhysicalMachineChaos?

### ISSUE THREAD

**Issue by ThreadDao** [chaos-mesh/chaos-mesh#3142]
## Question

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/chaos-mesh/chaos-mesh/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [Chaos Mesh Readme](https://github.com/chaos-mesh/chaos-mesh)
  - [Chaos Mesh Doc](https://chaos-mesh.org/docs)

**Output of chaosctl**

I want to know if chaos-mesh is not supported yet or where am I doing something wrong. I can't create a workflow or define schedule rules for PhysicalMachineChaos experiment.
1. Do we support creating workflows for PhysicalMachineChaos experiment？
```
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: disk-workflow-serial
spec:
  entry: serial-of-disk-node
  templates:
    - name: serial-of-disk-node
      templateType: Serial
      children:
        - disk-write
        - suspending
        - xxx
    - name: disk-write
      templateType: PhysicalMachineChaos
      physicalMachineChaos:
        action: disk-write-payload
        address:
          - http://xxxx:31760
          - http://xxx:31760
          - http://xxx:31760
        disk-write-payload:
          size: 10G
          path: /tmp
          payload-process-num: 4
        duration: 1m
    ...
```
And the output of `kubectl apply -f yaml`
```
error: error validating "xxxx.yaml": error validating data: [ValidationError(Workflow.spec.templates[1]): unknown field "physicalMachineChaos" in org.chaos-mesh.v1alpha1.Workflow.spec.templates]; if you choose to ignore these errors, turn validation off with --validate=false
```

2. Do we support defining schedule rules for the PhysicalMachineChaos experiment？
my experiment yaml:
```
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: schedule-delay-example
spec:
  schedule: 3 * * * *
  historyLimit: 2
  concurrencyPolicy: Allow
  type: PhysicalMachineChaos
  physicalMachineChaos:
    action: disk-write-payload
    address:
      - http://10.100.32.xx:31760
    disk-write-payload:
      size: 10G
      path: /tmp
      payload-process-num: 4
    duration: 1m
```
the output of `kubectl apply -f yaml`:
```
error: error validating "chaos-disk-write-schedule.yaml": error validating data: ValidationError(Schedule.spec): unknown field "physicalMachineChaos" in org.chaos-mesh.v1alpha1.Schedule.spec; if you choose to ignore these errors, turn validation off with --validate=false
```
