### ISSUE TITLE
Bug: Network Partition with both target & external target will block from target to external target

### ISSUE THREAD

**Issue by Andrewmatilde** [chaos-mesh/chaos-mesh#3204]
## Bug Report

**What version of Chaos Mesh are you using?**
master

**What did you do?**
apply network chaos like :
```yaml
kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: shenan-net
spec:
  selector:
    namespaces:
      - default
    pods:
      default:
        - e2e-helper
  mode: all
  action: partition
  direction: to
  target:
    selector:
      namespaces:
        - default
      pods:
        default:
          - e2e-helper1
    mode: all
  externalTargets:
    - www.baidu.com
```

**What did you expect to see?**

curl www.baidu.com in e2e-help1 works.

**What did you see instead?**

curl www.baidu.com in e2e-help1 failed.
