### ISSUE TITLE
NetworkChaos: External Target cannot get all the IPs through domain.

### ISSUE THREAD

**Issue by Andrewmatilde** [chaos-mesh/chaos-mesh#3252]
## Bug Report

**What version of Chaos Mesh are you using?**
master

**What did you do?**
Apply NetworkChaos with action:Partition on external target www.baidu.com.
```
kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: shenan-net
spec:
  selector:
    namespaces:
      - default
    pods:
      default:
        - e2e-helper
  mode: all
  action: partition
  direction: to
  externalTargets:
    - www.baidu.com
```

**What did you expect to see?**
The IPSET of target www.baidu.com contains a lot of IPs.

**What did you see instead?**
The IPSET stand for www.baidu.com only contains two IPs.

```
Name: shena_a8f649488eddb_net_tgt
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 504
References: 2
Number of entries: 2
Members:
220.181.38.150
220.181.38.149
```

**Output of chaosctl**
