### ISSUE TITLE
Chaos Mesh Network Attack experiment doesn't work on GKE cluster with Cilium Service Mesh

### ISSUE THREAD

**Issue by hoozgomk** [chaos-mesh/chaos-mesh#3302]
## Bug Report

**What version of Kubernetes are you using?**
`1.21.11-gke.900`

**What version of Chaos Mesh are you using?**
`2.1.3`

**What version of Cilium are you using**
`Cilium 1.11.3`

**What did you do?**
```
helm repo add chaos-mesh https://charts.chaos-mesh.org
kubectl create ns chaos-testing
helm install chaos-mesh chaos-mesh/chaos-mesh -n=chaos-testing --set chaosDaemon.runtime=containerd --set chaosDaemon.socketPath=/run/containerd/containerd.sock --set dashboard.securityMode=false --version 2.1.3
```

**What did you expect to see?**
I used to use linkerd service mesh within the experimental clusters where Chaos Mesh works flawlessly. I started to use Cilium service mesh, and here I faced a problem when submitting Network Attack (delay and loss) scenarios.
The experiment yaml file listed below applies correctly on a cluster with linkerd.
But when it is applied on a cluster with Cilium, then nothing happens. 
According to Chaos Mesh dashboard information, the experiment is applied correctly, and status changes to running, ( I’m getting information that chaos was successfully applied to specified pods), but services are not really impacted. I don’t see any significant footprint on the metrics as well.

experiment yaml file:

```
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: client-server-delay
  namespace: default
spec:
  action: delay
  mode: one
  selector:
    labelSelectors:
      name: "frontend"
  delay:
    latency: "17900ms"
    jitter: "200ms"
  direction: to
  target:
    selector:
      labelSelectors:
        name: "productcatalogservice"
    mode: one
```

Events in the Chaos Mesh dashboard are as follows:

```
Successfully update records of resource
Successfully apply chaos for default/frontend-654d7b6b74-hgcq5
Successfully update records of resource
Successfully apply chaos for default/productcatalogservice-6fc7746855-vqf69
Successfully update desiredPhase of resource
Successfully update finalizer of resource
Experiment has started
Finalizer has been inited
```

Experiment is run on cluster where online-butique https://github.com/GoogleCloudPlatform/microservices-demo is deployed and affects two of its services. 

I read that Chaos actions cover regular network faults, such as network delay, duplication, loss, and corruption using Network Emulation (Netem), where eBPF is used within Cilium.
Could you please confirm that Chaos Mesh works correctly when Cilium Service Mesh is used?
