### ISSUE TITLE
install.sh not working due to deprecated version warning in kubectl

### ISSUE THREAD

**Issue by timdrysdale** [chaos-mesh/chaos-mesh#3307]
## Bug Report

Hopefully this is not just some basic PEBKAC issue of my own making .... but for me the install script is failing to detect versions correctly due to the "helpful" warning being thrown by my version of kubectl about output format changing, and hence I cannot complete the install with `install.sh`.

**What version of Kubernetes are you using?**
```
clientVersion:
  buildDate: "2022-05-04T02:28:17Z"
  compiler: gc
  gitCommit: 4ce5a8954017644c5420bae81d72b09b735c21f0
  gitTreeState: clean
  gitVersion: v1.24.0
  goVersion: go1.18.1
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-01-25T21:19:12Z"
  compiler: gc
  gitCommit: 816c97ab8cff8a1c72eccca1026f7820e93e0d25
  gitTreeState: clean
  gitVersion: v1.23.3
  goVersion: go1.17.6
  major: "1"
  minor: "23"
  platform: linux/amd64
```
**What version of Chaos Mesh are you using?**
latest 

**What did you do?**
```
$ curl -sSL https://mirrors.chaos-mesh.org/v2.2.0/install.sh | bash
```
**What did you expect to see?**
No errors

**What did you see instead?**
```
check Kubernetes failed, error: WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
```
**Output of chaosctl**
N/A

I tried modifying the script to add --output=yaml and --output=json as appropriate to the `kubectl version` calls but that only got me as far as having further issues with the client version check, due to the default json output now being split across multiple lines.
