### ISSUE TITLE
How to determine the completed status of an experiment

### ISSUE THREAD

**Issue by xbx** [chaos-mesh/chaos-mesh#3316]
## Question

The following are the status fields of 2 different finished experiments:

```
# pod-kill

status:
  conditions:
  - reason: ""
    status: "True"
    type: Selected
  - reason: ""
    status: "True"
    type: AllInjected
  - reason: ""
    status: "False"
    type: AllRecovered
  - reason: ""
    status: "False"
    type: Paused
  experiment:
    containerRecords:
    - id: default/nginx-7667d48884-9fdr6
      phase: Injected
      selectorKey: .
    desiredPhase: Run
```

```
# StressChaos/cpu

status:
  conditions:
  - reason: ""
    status: "True"
    type: Selected
  - reason: ""
    status: "False"
    type: AllInjected
  - reason: ""
    status: "True"
    type: AllRecovered
  - reason: ""
    status: "False"
    type: Paused
  experiment:
    containerRecords:
    - id: default/nginx-7667d48884-qlstp/nginx-example
      phase: Not Injected
      selectorKey: .
    desiredPhase: Stop
```

They seem to follow opposite logic as `desiredPhase` ends up as Run and Stop, same thing for AllRecovered and AllInjected. So, from the status objects alone, how can determine that the experiments have finished? We are looking for something simple, like `Completed: True/False`.

Thanks
