### ISSUE TITLE
Pod Security Policy doesn't match Chaos Deamon's requirements

### ISSUE THREAD

**Issue by stephen-harris** [chaos-mesh/chaos-mesh#3321]
## Bug Report

**What version of Kubernetes are you using?**
1.20.15

**What version of Chaos Mesh are you using?**
2.2.0

**What did you do?**
Deployed Chaos Mesh using Helm (via ArgoCD) in a cluster with restricted PodSecurityPolicies, docker runtime and `.Values.bpfki.create` set to `false`.

**What did you expect to see?**
Chaos daemon to be deployed

**What did you see instead?**
The error: 

> Error creating: pods "chaos-daemon-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.volumes[0].hostPath.pathPrefix: Invalid value: "/var/run": is not allowed to be used spec.volumes[2].hostPath.pathPrefix: Invalid value: "/lib/modules": is not allowed to be used]

The existing PSP [allows](https://github.com/chaos-mesh/chaos-mesh/blob/release-2.2/helm/chaos-mesh/templates/chaos-daemon-rbac.yaml#L91) mounting `/var/run/docker.sock`, but the chaos-daemon tries to [mount the parent directory](https://github.com/chaos-mesh/chaos-mesh/blob/release-2.2/helm/chaos-mesh/templates/chaos-daemon-daemonset.yaml#L185) `/var/run`

The chaos-daemon also [tries to mount](https://github.com/chaos-mesh/chaos-mesh/blob/9b90670091014171cb7ee52ce34fa71c70a3a782/helm/chaos-mesh/templates/chaos-daemon-daemonset.yaml#L202) `/lib/modules` but this is [not always allowed](https://github.com/chaos-mesh/chaos-mesh/blob/release-2.2/helm/chaos-mesh/templates/chaos-daemon-rbac.yaml#L90) by the PSP.

**Output of chaosctl**
n/a - this is a helm configuration issue not runtime issue.

**Comment by Andrewmatilde** [comment]
Tanks for your feedback. Can you show your raw helm command? What is `restricted PodSecurityPolicies, docker runtime` acctually means? And I think set .Values.chaosDaemon.privileged be true may help it.

**Comment by stephen-harris** [comment]
Sorry, that was clumsily put by me. By "restricted PodSecurityPolicies", I just meant that the chaos-daemon couldn't use an already existing pod security policy (because they are either locked down, or provide insufficient permissions). So it's relying on the PSP provided by the chart to give it appropriate permissions. (On EKS there is by default a highly privileged PSP - in such circumstances you might not see the error because the chaos-daemon uses the existing PSP).

Regarding docker. The cluster uses Docker container runtime. At the time I thought the `/var/run` mount issue was specific to the docker runtime. This might not be the case. The PSP is allowing mounting a specific path to the socket, whereas the chaos-daemon is mounting the parent directory. 

Lastly if `.Values.bpfki.create` were set to true then the `/lib/modules` is added to the allowed path prefix in the PSP.

Chaos mesh was deployed via ArgoCD, so I don't have a helm command, but here's our values file:

```
controllerManager:  
  service:
    type: ClusterIP
  
chaosDaemon:
  privileged: false
  podSecurityPolicy: true

  env:
    DOCKER_API_VERSION: "1.40"
```

Here's the output of `kubectl -n chaos-mesh get ds chaos-daemon -o yaml | yq .spec.template.spec.volumes`

```

- hostPath:
    path: /var/run
    type: ""
  name: socket-path
- hostPath:
    path: /sys
    type: ""
  name: sys-path
- hostPath:
    path: /lib/modules
    type: ""
  name: lib-modules
- name: chaos-daemon-cert
  secret:
    defaultMode: 420
    secretName: chaos-mesh-daemon-certs
```

And the output `kubectl get psp chaos-mesh-chaos-daemon -o yaml | yq .spec.allowedHostPaths`

```
- pathPrefix: /var/run/docker.sock
- pathPrefix: /sys
```

If you add `/lib/modules` and `/var/run` to that list, the daemon pods deploy correctly.
