### ISSUE TITLE
Field `options` in kind:PhysicalMachineChaos cannot work

### ISSUE THREAD

**Issue by masa-oza** [chaos-mesh/chaos-mesh#3327]
## Bug Report

**What version of Kubernetes are you using?**
GitVersion: v1.23.5+rke2r1
GoVersion: go1.17.8b7

**What version of Chaos Mesh are you using?**
GitVersion: v2.2.0
GoVersion: go1.18

**What did you do?**
Bug that the type of field options is different between chaos mesh and chaosd.
I applied below manifest, but got error event at `options` field.
```
---
kind: PhysicalMachineChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-mesh
  name: test1
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  action: stress-mem
  address:
    - http://xx.xx.xx.xx:31767/
  mode: all
  stress-mem:
    size: 3GiB
    options: "--vm-hang=0" # here
```

Error event is below.
> Failed to apply chaos:
> {
> "error":true,
> "message":"error.api.internal_server_error: json: cannot unmarshal string into Go struct field StressCommand.options of type []string",
> "code":"error.api.internal_server_error",
> "full_text":"error.api.internal_server_error: json: cannot unmarshal string into Go struct field StressCommand.options of type []string\n at github.com/chaos-mesh/chaosd/pkg/server/httpserver.(*httpServer).createStressAttack()\n\t/__w/chaosd/chaosd/pkg/server/httpserver/server.go:191\n at github.com/gin-gonic/gin.(*Context).Next()\n\t/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\n at github.com/chaos-mesh/chaosd/pkg/server/utils.MWHandleErrors.func1()\n\t/__w/chaosd/chaosd/pkg/server/utils/error.go:47\n at github.com/gin-gonic/gin.(*Context).Next()\n\t/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\n at github.com/gin-gonic/gin.RecoveryWithWriter.func1()\n\t/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83\n at github.com/gin-gonic/gin.(*Context).Next()\n\t/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\n at github.com/gin-gonic/gin.LoggerWithConfig.func1()\n\t/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241\n at github.com/gin-gonic/gin.(*Context).Next()\n\t/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\n at github.com/gin-gonic/gin.(*Engine).handleHTTPRequest()\n\t/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409\n at github.com/gin-gonic/gin.(*Engine).ServeHTTP()\n\t/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367\n at net/http.serverHandler.ServeHTTP()\n\t/__t/go/1.16.2/x64/src/net/http/server.go:2887\n at net/http.(*conn).serve()\n\t/__t/go/1.16.2/x64/src/net/http/server.go:1952\n at runtime.goexit()\n\t/__t/go/1.16.2/x64/src/runtime/asm_amd64.s:1371"
> }: HTTP status is not OKs

Ref. https://cloud-native.slack.com/archives/C0193VAV272/p1654505897904179
