### ISSUE TITLE
PodKill would not completed within Workflow

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#3345]
## Bug Report

**What version of Kubernetes are you using?**

N/A

**What version of Chaos Mesh are you using?**

master branch

**What did you do?**

create a workflow like :

```
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  namespace: default
  name: suspend-then-kill-nginx2
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      deadline: 5m
      children:
        - suspend-1s
        - kill-nginx
        - suspend-2s
    - name: suspend-1s
      templateType: Suspend
      deadline: 1s
    - name: kill-nginx
      templateType: PodChaos
      podChaos:
        selector:
          namespaces:
            - default
          labelSelectors:
            app: nginx
        mode: all
        action: pod-kill
        gracePeriod: 0
    - name: suspend-2s
      templateType: Suspend
      deadline: 2s

```
**What did you expect to see?**

three nodes would execute one by one

**What did you see instead?**

stucked in second node kill-nginx

**Output of chaosctl**
