### ISSUE TITLE
Many Error messages pointing to privilege issue with service account (after generating token and updating in Dashboard)

### ISSUE THREAD

**Issue by gopimandala** [chaos-mesh/chaos-mesh#3371]
## Bug Report

**What version of Kubernetes are you using?**
v1.22.0

**What version of Chaos Mesh are you using?**
v2.2.0

**What did you do?**
Installed using this link for **containerd** (https://chaos-mesh.org/docs/production-installation-using-helm/)

**What did you expect to see?**
After the dashboard UI opens up, it asks for a token with a yaml manifest for roles/bindings etc. And I have followed the steps and generated the token and provided as suggested. There should be no error messages after the token is provided.
(By the way, when i installed chaos mesh without using helm (curl -sSL https://mirrors.chaos-mesh.org/v2.2.0/install.sh | bash), the dashboard never asked for this token and i could even run a pod kill experiment successfully. The token is being asked only for helm installation. But the issue with manual installation was it installed with docker and my cluster is using containerd, so i am trying with helm + containerd option)

**What did you see instead?**
There are quite a few error msgs such as these constantly displayed on the screen:

```
- error.api.no_cluster_privilege: can't list resource in the cluster
- error.api.no_cluster_privilege: azurechaos.chaos-mesh.org is forbidden: User "system:serviceaccount:default:account-default-viewer-vwsmw" cannot list resource "azurechaos" in API group "chaos-mesh.org" at the cluster scope
- error.api.no_cluster_privilege: physicalmachinechaos.chaos-mesh.org is forbidden: User "system:serviceaccount:default:account-default-viewer-vwsmw" cannot list resource "physicalmachinechaos" in API group "chaos-mesh.org" at the cluster scope
```

I even tweaked the manifest as below (just for the heck of it) giving irresponsibly :) wider privilege but the issue still persists:
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: role-default-viewer-vwsmw
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - chaos-mesh.org
  resources: [ "*" ]
  verbs: ["*"]

```

The SA, role, binding are all in default ns. My dummy apps are also in default ns.

I am following the tutorial with canned helm chart, so I am assuming all the privileges would be taken care of in the manifest templates provided. Please let me know what could be going wrong.

I am surprised by the difference in the token demand process b/w manual and helm installation.

Here is the full manifest:
```
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: account-default-viewer-vwsmw

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: role-default-viewer-vwsmw
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - chaos-mesh.org
  resources: [ "*" ]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-default-viewer-vwsmw
  namespace: default
subjects:
- kind: ServiceAccount
  name: account-default-viewer-vwsmw
  namespace: default
roleRef:
  kind: Role
  name: role-default-viewer-vwsmw
  apiGroup: rbac.authorization.k8s.io
```
