### ISSUE TITLE
scheduler do not support on v2.2.0?

### ISSUE THREAD

**Issue by hillbun** [chaos-mesh/chaos-mesh#3373]
scheduler do not support on v2.2.0?

**Comment by hillbun** [comment]
any advice?

**Comment by STRRL** [comment]
What does "scheduler" means?

`Schedule` is supported after Chaos Mesh 2.0.0, and it is supported in 2.2.0. https://chaos-mesh.org/docs/define-scheduling-rules/

Did you face any issues when using `Schedule`?

**Comment by eskuai** [comment]
Hi !`

As a user, using  chaos-mesh/chaos-mesh:v2.3.1" , if  I apply 

```
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: web-show-network-delay
spec:
  action: delay # the specific chaos action to inject
  mode: one # the mode to run chaos action; supported modes are one/all/fixed/fixed-percent/random-max-percent
  selector: # pods where to inject chaos actions
    namespaces:
      - default
    labelSelectors:
      "app": "web-show"  # the label of the pod for chaos injection
  delay:
    latency: "10ms"
  duration: "30s" # duration for the injected chaos experiment
  scheduler: # scheduler rules for the running time of the chaos experiments about pods.
    cron: "@every 60s"
```
I got a error:

```
root@fedora mesh]# kubectl apply -f w2.yaml
error: error validating "w2.yaml": error validating data: ValidationError(NetworkChaos.spec): unknown field "scheduler" in org.chaos-mesh.v1alpha1.NetworkChaos.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

any help?
