### ISSUE TITLE
specify a pod which is not existed,  will get a confusing experiment status

### ISSUE THREAD

**Issue by xlgao-zju** [chaos-mesh/chaos-mesh#3374]
## Bug Report

**What version of Kubernetes are you using?**

1.16.6

**What version of Chaos Mesh are you using?**

2.2.0

**What did you do?**

specify a pod which is not existed, like
```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  finalizers:
  - chaos-mesh/records
  namespace: chaos-testing
spec:
  action: pod-kill
  gracePeriod: 0
  mode: fixed
  selector:
    namespaces:
    - chaos-testing
    pods:
      bar:
      - foo
  value: "2"
```
in this case, there is no pod called foo in bar namespace in k8s cluster.

**What did you expect to see?**
some error message which tell me, the pod is not found, and the selecting failed.

**What did you see instead?**
I get a confusing status:
```yaml
status:
  conditions:
  - reason: ""
    status: "False"
    type: Selected
  - reason: ""
    status: "True"
    type: AllInjected
  - reason: ""
    status: "True"
    type: AllRecovered
  - reason: ""
    status: "False"
    type: Paused
  experiment:
    desiredPhase: Run
```

**Output of chaosctl**

**Comment by xlgao-zju** [comment]
I thin we need a well-designed experiment status to tell end user what happened and why this happened.

cc @STRRL @track87

**Comment by Andrewmatilde** [comment]
I agree with that it is confusing , but I also have no good idea  on it. Maybe log error in status will be better?

**Comment by xlgao-zju** [comment]
>  I agree with that it is confusing , but I also have no good idea on it. Maybe log error in status will be better?

yep, put the error message in this status will be a good choice. 

and I think we need to think about the whole picture of status, and re-design it.  I think the most important thing about status is: let users know if the experiment completed, and why.

**Comment by Andrewmatilde** [comment]
@xlgao-zju sorry for reply so late.  I can hardly talk about this. Because I usaully just check the logs in chaos-daemon as a developer acctually. I agree a better status system will help user know a lot of things ,but I cannot image what it will be. PTAL @YangKeao ,can you give some advice?

**Comment by xlgao-zju** [comment]
@Andrewmatilde I think we can put the details in the `reason ` field in the `condition`. 
when specify a pod which is not existed, we will get `condition` like this:
```yaml
status:
  conditions:
  - reason: "specified pods are not existed"
    status: "False"
    type: Selected
  - reason: ""
    status: "True"
    type: AllInjected
  - reason: ""
    status: "True"
    type: AllRecovered
  - reason: ""
    status: "False"
    type: Paused
  experiment:
    desiredPhase: Run
```

**Comment by xlgao-zju** [comment]
looks like the `reason` field in the `condition` will always be empty? I think put some details in it would be a good idea 😆 

WDYT? @STRRL @YangKeao

**Comment by STRRL** [comment]
The current message in reason is "specified pods are not existed", do you have any suggestion? :heart: @xlgao-zju

**Comment by xlgao-zju** [comment]
for now, we select the target in `record phase`.

 if we need the details of selector, when we update the `condition`. could we select the target in `condition phase`?

**Comment by Andrewmatilde** [comment]
> looks like the `reason` field in the `condition` will always be empty? I think put some details in it would be a good idea 😆
> 
> WDYT? @STRRL @YangKeao

I also stand with this suggestion! ❤️

**Comment by Andrewmatilde** [comment]
> for now, we select the target in `record phase`.
> 
> if we need the details of selector, when we update the `condition`. could we select the target in `condition phase`?

There is a problem that the `target` is not human readable now. If we make the message of `target` more reasonable ,I think it is good.

**Comment by xlgao-zju** [comment]
> There is a problem that the target is not human readable now. If we make the message of target more reasonable ,I think it is good.

yes, for now, we just put all the target info in a `string`, and the code like:
```golang
func (c *Container) Id() string {
	return c.Pod.Namespace + "/" + c.Pod.Name + "/" + c.ContainerName
}
```

if we want to make the target info human readable, maybe we can put this info as a field of record. and add a file in `experiment` to indicate the target type. maybe like:
```yaml 
    experiment:
      targetType: container
      containerRecords:
      - id: xlgao/nginx-644467cc8b-dv25r/nnn
        namespace: xlgao
        pod: nginx-644467cc8b-dv25r
        container: nnn
        phase: Not Injected
        selectorKey: .
      desiredPhase: Stop
```

and to be honest, I do not know if it is the reason why we select the target in `record phase` for now...
