### ISSUE TITLE
Network Chaos is injecting more delay

### ISSUE THREAD

**Issue by QAInsights** [chaos-mesh/chaos-mesh#3399]
## Bug Report

**What version of Kubernetes are you using?**
Client Version: v1.23.0
Server Version: v1.22.8

**What version of Chaos Mesh are you using?**
2.2.0

**What did you do?**
Network delay is injecting too much delay in the response time. Below is the networkChaos experiment manifest where I configured 5 seconds. But it is showing the delay of 20s.
```
kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: nginx
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: nginx
  mode: all
  action: delay
  delay:
    latency: 5s
    correlation: '0'
    jitter: 0ms
  direction: to
```

**What did you expect to see?**
5s delay

**What did you see instead?**
20s delay

**Output of chaosctl**
[chaos-daemon-q6r55.log](https://github.com/chaos-mesh/chaos-mesh/files/8997128/chaos-daemon-q6r55.log)
[chaos-daemon-bnp85.log](https://github.com/chaos-mesh/chaos-mesh/files/8997129/chaos-daemon-bnp85.log)
[chaos-daemon-nknn8.log](https://github.com/chaos-mesh/chaos-mesh/files/8997130/chaos-daemon-nknn8.log)
