### ISSUE TITLE
pod io injection finished but injected dir got "Transport endpoint is not connected" error

### ISSUE THREAD

**Issue by zhangyulu** [chaos-mesh/chaos-mesh#3424]
## Bug Report

**What version of Kubernetes are you using?**
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:30Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**What version of Chaos Mesh are you using?**
Controller manager Version: version.Info{GitVersion:"chart-2.2.1", GitCommit:"2f01b6da2cfbe6ac89ea612da5880fa647427079", BuildDate:"2022-06-29T06:02:20Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**
New Experiments -> Kubernetes -> IO injection
Kind: IOChaos
Action: fault
Errno: 30
Volume path: /xxx/dump
Percent: 100
Duration: 30m

**What did you expect to see?**
After the experiment finished, injected dir recovers and I can access it

**What did you see instead?**
ls in parent dir:
ls: cannot access 'dump': Transport endpoint is not connected

ll in parent dir:
d????????? ? ?    ?           ?            ? dump

df shows nothing abount the injected dir, but there is a mounted dir: /xxx/__chaosfs__dump__

/proc/mounts contains following record, but no toda process running(already exited):
toda /xxx/dump fuse rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other 0 0

**Comment by Hexilee** [comment]
It seems the toda process didn't exit gracefully, could you provide the logs of chaos-daemon?

**Comment by zhangyulu** [comment]
[chaos_daemon.log](https://github.com/chaos-mesh/chaos-mesh/files/9070833/chaos_daemon.log)

**Comment by STRRL** [comment]
> [chaos_daemon.log](https://github.com/chaos-mesh/chaos-mesh/files/9070833/chaos_daemon.log)

Ping @Hexilee , it seems `toda` paniced.

HI @zhangyulu , could you tell us how to repoduce this issue? For example:

 - how you deploy redis? which container image is used with redis?
 - the yaml spec of IOChaos
 - other information if you think it's helpful to reproduce this issue. 

also cc @YangKeao @Andrewmatilde

**Comment by zhangyulu** [comment]
redis is deployed with a pv mounted as /redis/dump, which is the path I injected IO chaos, the image is self-made with some hack in redis, but I think it's not the key point
yaml of IOChaos is like this:
```
kind: IOChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: redis
  name: io-readonly
  annotations:
    experiment.chaos-mesh.org/pause: 'false'
spec:
  selector:
    namespaces:
      - redis
    labelSelectors:
      statefulset.kubernetes.io/pod-name: whatever-the-name
  mode: all
  action: fault
  errno: 30
  percent: 100
  volumePath: /redis/dump
  duration: 30m
```
