### ISSUE TITLE
Failed to recover TimeChaos: TaskID not found.

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#3454]
## Bug Report

**What version of Kubernetes are you using?**
 

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.14", GitCommit:"57a3aa3f13699cf3db9c52d228c18db94fa81876", GitTreeState:"clean", BuildDate:"2021-12-15T14:47:10Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**
 

v2.2.0

**What did you do?**
 

Create a new TimeChaos 
```
kind: TimeChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: clock-skew
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  selector:
    namespaces:
      - default
    pods:
      default:
        - time
  mode: all
  containerNames:
    - time
  timeOffset: 10m
  clockIds:
    - CLOCK_REALTIME

```

Achieve TimeChaos experiment on Chaos Dashboard

**What did you expect to see?**

TimeChaos was deleted successfully. 

**What did you see instead?**.  

![image](https://user-images.githubusercontent.com/22956341/178933200-ad5a0671-eeab-4a3f-b6bf-22c6660dd13e.png)

**Output of chaosctl**
