### ISSUE TITLE
Failed to update finalizer: updateError.Error()

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#3455]
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.14", GitCommit:"57a3aa3f13699cf3db9c52d228c18db94fa81876", GitTreeState:"clean", BuildDate:"2021-12-15T14:47:10Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**
 

v2.2.0

**What did you do?**
 

Create a PhysicalMachineChaos 
```
kind: PhysicalMachineChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: pd-21
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  action: disk-write-payload
  address:
    - http://172.16.7.173:31767
  selector: {}
  mode: ''
  uid: 2d1e6fac-d2f6-4efa-9dee-f25d6c47366b
  disk-write-payload:
    size: 200GB
    path: /home/tmp/bbb
    payload-process-num: 2
```  

And achieve it on chaos dashboard. 

**What did you expect to see?** 

The PhysicalMachineChaos was deleted successfully. 

**What did you see instead?**  

![Uploading image.png…]()

**Output of chaosctl**
