### ISSUE TITLE
TimeChaos doesn't have effect on nginx

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#3467]
I setup an nginx server through the following deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: chaos-mesh-poc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers: 
      - name: nginx
        image: nginx:latest
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - mountPath: /mnt
          name: test-volume
      volumes:
      - name: test-volume
        emptyDir: {}
```

After injecting the TimeChaos, I found the time in HTTP header doesn't shift. I want to know why.
