### ISSUE TITLE
JVMChaos stress not works on 2.2.2

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#3472]
## Bug Report

**What version of Kubernetes are you using?**

N/A

**What version of Chaos Mesh are you using?**

2.2.2

**What did you do?**

create workload:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  containers:
    - name: helloworld
      # source code: https://github.com/WangXiangUSTC/byteman-example/tree/main/example.helloworld
      # this application will print log like this below:
      # 0. Hello World
      # 1. Hello World
      # ...
      image: xiang13225080/helloworld:v1.0
      imagePullPolicy: IfNotPresent
```

create jvmchaos

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: jvm-stress
spec:
  action: stress
  cpuCount: 2
  mode: all
  selector:
    labelSelectors:
      app: helloworld
```

**What did you expect to see?**

top could see the java process use 200% CPU.

**What did you see instead?**

no CPU stress created with error log

![image](https://user-images.githubusercontent.com/20221408/180422210-81d926cb-4234-429f-84b1-e2d83b1641a0.png)

It seems that the file `/usr/local/byteman/lib/chaos-agent.jar` could not be accessed in the JVM application's mount namespace.

**Output of chaosctl**
