### ISSUE TITLE
Create NetworkChaos with same selector in . and target will cause error

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#3493]
## Bug Report

```
spec:
  selector:
    namespaces:
    .....
  direction: both
  target:
    selector:
      ....
```
