### ISSUE TITLE
Error: Failed to update records: Internal error occurred: failed calling webhook "vauth.kb.io": failed to call webhook: Post "https://chaos-mesh-controller-manager.chaos-testing.svc:443/validate-auth?timeout=5s": EOF

### ISSUE THREAD

**Issue by pcgeek86** [chaos-mesh/chaos-mesh#3542]
## Bug Report

**What version of Kubernetes are you using?**

k3s 1.24.3

**What version of Chaos Mesh are you using?**

2.3.0

**What did you do?**

* Install Chaos Mesh via Helm `helm install chaos-mesh chaos-mesh/chaos-mesh -n=chaos-testing --set chaosDaemon.runtime=containerd --set chaosDaemon.socketPath=/run/k3s/containerd/containerd.sock --version 2.3.0`
* Created namespace `pwsh`
* Ran an interactive Pod-container: `kubectl run --rm -it --image=mcr.microsoft.com/powershell --namespace pwsh pwsh`
* Create a Chaos Mesh experiment according to below manifest

```yml
kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: pwsh
  name: pwsh
spec:
  selector:
    namespaces:
      - pwsh
  mode: all
  containerNames:
    - pwsh
  action: container-kill
  gracePeriod: 0
```

**What did you expect to see?**

Container should be killed off successfully, without any errors appearing.

**What did you see instead?**

```
Failed to update records: Internal error occurred: failed calling webhook "vauth.kb.io": failed to call webhook: Post "https://chaos-mesh-controller-manager.chaos-testing.svc:443/validate-auth?timeout=5s": EOF
```

![image](https://user-images.githubusercontent.com/466713/183809450-954a6947-65bd-4198-8405-e0443a9573d3.png)

**Output of chaosctl**
