### ISSUE TITLE
Dashboard: can't show the right workflow graph 

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#3543]
## Bug Report

**What version of Kubernetes are you using?**
. 

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**
. 

v2.1.5 

**What did you do?**
 

Create a parallel task on workflow  

```
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  namespace: default
  name: delayxxxx
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      deadline: 2m
      children:
        - network-delay
    - name: delay-10ms
      templateType: NetworkChaos
      deadline: 30s
      networkChaos:
        selector:
          namespaces:
            - default
          labelSelectors:
            app: web-show
        mode: all
        action: delay
        delay:
          latency: 10ms
          correlation: '0'
          jitter: 0ms
        direction: to
    - name: delay-10ms-2
      templateType: NetworkChaos
      deadline: 30s
      networkChaos:
        selector:
          namespaces:
            - default
          labelSelectors:
            app: web-show
        mode: all
        action: delay
        delay:
          latency: 10ms
          correlation: '0'
          jitter: 0ms
        direction: to
    - name: network-delay
      templateType: Parallel
      deadline: 2m
      children:
        - delay-10ms
        - delay-10ms-2
```

**What did you expect to see?**. 

Show the right workflow graph 

**What did you see instead?** 

![image](https://user-images.githubusercontent.com/22956341/183845607-a6bb7e25-d100-4316-a550-847b293e4ea0.png)

event: 
```
delayxxxx

workflow accomplished

1 MINUTE AGO
delay-10ms-2-ft8c2

chaos CR delay-10ms-2-ft8c2-mwppx deleted

1 MINUTE AGO
delay-10ms-2-ft8c2

deadline exceed

1 MINUTE AGO
network-delay-4nh56

node accomplished

1 MINUTE AGO
delay-10ms-l4896

chaos CR delay-10ms-l4896-9rv6s deleted

1 MINUTE AGO
delay-10ms-l4896

deadline exceed

1 MINUTE AGO
entry-9xz2l

node accomplished

1 MINUTE AGO
delayxxxx

entry node created, entry node entry-9xz2l

2 MINUTES AGO
delay-10ms-l4896

chaos CR delay-10ms-l4896-9rv6s created

2 MINUTES AGO
entry-9xz2l

child nodes created, network-delay-4nh56

2 MINUTES AGO
delay-10ms-2-ft8c2

chaos CR delay-10ms-2-ft8c2-mwppx created

2 MINUTES AGO
network-delay-4nh56

child nodes created, delay-10ms-l4896,delay-10ms-2-ft8c2
```

**Output of chaosctl**
