### ISSUE TITLE
[Bug] 🐛 Workflow PREVIEW UI fails to create HTTP Chaos node in Chaos Mesh v2.3.0

### ISSUE THREAD

**Issue by pcgeek86** [chaos-mesh/chaos-mesh#3545]
## Bug Report

**What version of Kubernetes are you using?** 1.23.6

**What version of Chaos Mesh are you using?** 2.3.0

**What did you do?**

- Set up fresh Kubernetes cluster 1.23.6 on Linode LKE
- Install Helm Chart for Chaos Mesh v2.3.0
- Login to Chaos Mesh dashboard and enable Workflow **PREVIEW** feature checkbox
- Create new workflow in web UI / dashboard
- Add a HTTPChaos node
- Enable `abort=true` in HTTPChaos node
- Save the workflow

```
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: wf01
  namespace: default
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      children:
        - dnschaos01
        - http01
      deadline: 60s
    - name: dnschaos01
      templateType: Schedule
      deadline: 30s
      schedule:
        schedule: '*/1 * * * *'
        historyLimit: 3
        concurrencyPolicy: Forbid
        type: DNSChaos
        dnsChaos:
          action: error
          selector:
            namespaces:
              - default
          mode: all
    - name: http01
      templateType: HTTPChaos
      deadline: 15s
      httpChaos:
        selector:
          namespaces:
            - default
        mode: all
        abort: true

```

**What did you expect to see?**

Successfully create workflow

**What did you see instead?**

![image](https://user-images.githubusercontent.com/466713/184002324-ecc00c23-58b6-4fa0-9731-cc2931f55a9a.png)

**Output of chaosctl**
