### ISSUE TITLE
HTTPChaos can not inject 

### ISSUE THREAD

**Issue by webliupeng** [chaos-mesh/chaos-mesh#3568]
K8S version: 1.20
Chaos Mesh Version: 2.3.3

I have flow official document install chaos mesh, I've created a HTTPChaos resource on dashboard.But it's do not work.  State is  always "Injecting" on dashboard.  below is my resource yaml.
```yaml
kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: dev2
  name: slow-http
spec:
  selector:
    namespaces:
      - dev2
  mode: all
  target: Response
  delay: 100s
  port: 80
  path: '*'
```
the resource status:

```yaml
Name:         slow-http
Namespace:    dev2
Labels:       <none>
Annotations:  <none>
API Version:  chaos-mesh.org/v1alpha1
Kind:         HTTPChaos
Metadata:
  Creation Timestamp:  2022-08-19T03:20:18Z
  Finalizers:
    chaos-mesh/records
  Generation:  5
Spec:
  Delay:  100s
  Mode:   all
  Path:   *
  Port:   80
  Selector:
    Namespaces:
      dev2
  Target:  Response
Status:
  Conditions:
    Reason:  
    Status:  True
    Type:    Selected
    Reason:  
    Status:  False
    Type:    AllInjected
    Reason:  
    Status:  False
    Type:    AllRecovered
    Reason:  
    Status:  False
    Type:    Paused
  Experiment:
    Container Records:
      Id:               dev2/ew-launcher-6fc6854cbc-4dpvz
      Injected Count:   0
      Phase:            Not Injected/Wait
      Recovered Count:  0
      Selector Key:     .
      Id:               dev2/ew-map-6b84b44c9d-9x8hn
      Injected Count:   0
      Phase:            Not Injected/Wait
      Recovered Count:  0
      Selector Key:     .
      Id:               dev2/ew-launcher-6fc6854cbc-7lxfp
      Injected Count:   0
      Phase:            Not Injected/Wait
      Recovered Count:  0
      Selector Key:     .
      Id:               dev2/ew-launcher-6fc6854cbc-zc78b
      Injected Count:   0
      Phase:            Not Injected/Wait
      Recovered Count:  0
      Selector Key:     .
      Id:               dev2/ew-launcher-6fc6854cbc-zlz6l
      Injected Count:   0
      Phase:            Not Injected/Wait
      Recovered Count:  0
      Selector Key:     .
      Id:               dev2/ew-launcher-6fc6854cbc-b8tj2
      Injected Count:   0
      Phase:            Not Injected/Wait
      Recovered Count:  0
      Selector Key:     .
    Desired Phase:      Run
  Instances:
    dev2/ew-launcher-6fc6854cbc-4dpvz:  1
    dev2/ew-launcher-6fc6854cbc-7lxfp:  1
    dev2/ew-launcher-6fc6854cbc-b8tj2:  1
    dev2/ew-launcher-6fc6854cbc-zc78b:  1
    dev2/ew-launcher-6fc6854cbc-zlz6l:  1
    dev2/ew-map-6b84b44c9d-9x8hn:       2
Events:                                             <none>

```
