### ISSUE TITLE
HTTPChaos cannot be deleted and recovered

### ISSUE THREAD

**Issue by Makalov1111** [chaos-mesh/chaos-mesh#3728]
## Bug Report

**What version of Kubernetes are you using?**
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:41Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}

**What version of Chaos Mesh are you using?**
Controller manager Version: version.Info{GitVersion:"v2.2.0", GitCommit:"22a1cf57398e35da58dd391b79b64f3071e2863b", BuildDate:"2022-04-29T13:15:01Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}

**What did you do? / Minimal Reproducible Example**

1. deploy a HTTPChaos with wrong delay config , as follow:
```
kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: test
  name: frontend-test
  annotations:
    chaos-mesh.chaos-mesh.org/cleanFinalizer: forced
    experiment.chaos-mesh.org/pause: 'true'
spec:
  selector:
    namespaces:
      - test
    labelSelectors:
      app: backend
  mode: all
  target: Request
  abort: true
  port: 9998
  path: http://backend.test:9998/api/v1/loginByUsername         # frontend login api
  method: POST
```
2.  When I test with it, I found that my frontend page could not be logined, so I pause it, and delete it in the dashboard, found out unable to delete.
3.  So I forcibly delete the Chaos experiment with the following command:
```
kubectl annotate httpchaos test chaos-mesh.chaos-mesh.org/cleanFinalizer=forced
```
4. When I delete httpchaos, my frontend page is still unable to access it, unless I delete frontend server pod.In addition, I found that other urls, including path, were injected with chaos.

**What did you expect to see?**
I think it is because the PATH field does not take effect, and all HTTP requests have been abandoned that HTTPCHAOS cannot be deleted
**What did you see instead?**

**Output of chaosctl**
