### ISSUE TITLE
JVMChaos is not working as expected

### ISSUE THREAD

**Issue by anuragpaliwal80** [chaos-mesh/chaos-mesh#3827]
## Bug Report

**What version of Kubernetes are you using?**

1.22

**What version of Chaos Mesh are you using?**

2.2

**What did you do? / Minimal Reproducible Example**

Applied JVMChaos.
```
apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: return
  namespace: helloworld
spec:
  action: return
  class: Main
  method: getnum
  value: "9999"
  mode: all
  selector:
    namespaces:
      - helloworld
```

**What did you expect to see?**
Should be injected.

**What did you see instead?**
Not injected.

**Output of chaosctl**
