### ISSUE TITLE
`Workflow` will always hang on when a `WorkflowNode` with `xxxChaos` type and empty `deadline` field

### ISSUE THREAD

**Issue by iguoyr** [chaos-mesh/chaos-mesh#3846]
## Bug Report

**What version of Kubernetes are you using?**

**What version of Chaos Mesh are you using?**

**What did you do? / Minimal Reproducible Example**

```yaml
...
spec:
  entry: node1
  templates:
    - name: node1
      templateType: Serial
      children:
        - node2
    - name: node2
      deadline: 10s # without this line, the workflow will hang on
      templateType: PodChaos
      podChaos:
        action: pod-kill
        mode: one
...
```

**What did you expect to see?**
There are two solutions:
1. (recommended) `ChaosNodeReconciler` watches the chaos resources, and set some conditions to represent that `xxxChaos` is finished.
2. adjust `deadline` to a required field, if users set an empty deadline field, return error

**What did you see instead?**
The workflow will always hang on, when I remove the `deadline: 10s` line

**Output of chaosctl**
