### ISSUE TITLE
remoteCluster is not working as expected

### ISSUE THREAD

**Issue by tamz-kwon** [chaos-mesh/chaos-mesh#4014]
## Bug Report

**What version of Kubernetes are you using?**
Main eks 1.24, remote Cluster eks 1.25

**What version of Chaos Mesh are you using?**
2.5.2

**What did you do? / Minimal Reproducible Example**
Installed using helm-chart.

**What did you expect to see?**
necessary components will be installed automatically in the remote cluster. 

**Output of chaosctl**
```https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins", "errorVerbose": "Get \"https://$clusterAddress.eks.amazonaws.com/version\": getting credentials: exec: executable aws not found```

kubeconfig added on secret such as below.
```
apiVersion: v1
clusters:
- cluster:
    server: $cluster_endpoint
    certificate-authority-data: $certificate_data
  name: arn:aws:eks:$region_code:$account_id:cluster/$cluster_name
contexts:
- context:
    cluster: arn:aws:eks:$region_code:$account_id:cluster/$cluster_name
    user: arn:aws:eks:$region_code:$account_id:cluster/$cluster_name
  name: arn:aws:eks:$region_code:$account_id:cluster/$cluster_name
current-context: arn:aws:eks:$region_code:$account_id:cluster/$cluster_name
kind: Config
preferences: {}
users:
- name: arn:aws:eks:$region_code:$account_id:cluster/$cluster_name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "$cluster_name"
```

remoteCluster is here.
```
apiVersion: chaos-mesh.org/v1alpha1
kind: RemoteCluster
metadata:
  name: $cluster_name
spec:
  namespace: 'chaos-mesh'
  kubeConfig:
    secretRef:
      name: kubeconfig-chaosmesh
      namespace: chaos-mesh
      key: kubeconfig
```

**Comment by tamz-kwon** [comment]
hello @g1eny0ung Thanks for response!

kubeconfig is define such as below.
```
- name: arn:aws:eks:$region_code:$account_id:cluster/$cluster_name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ap-northeast-2
      - eks
      - get-token
      - --cluster-name
      - "$cluster_name"
      command: aws
```

And below are installation logs.
```
ERROR    remotecluster    remotecluster/controller.go:122    fail to list or install remote helm release    {"error": "get release chaos-mesh, in namespace chaos-mesh: Kubernetes cluster unreachable: Get \"
https://075B1C7DDD1ECD0948821A97D558D8A5.gr7.ap-southeast-1.eks.amazonaws.com/version\": getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins", 
      "errorVerbose": "Get \"https://BDCA23251DC1007ADFFG.gr7.ap-southeast-2.eks.amazonaws.com/version\": getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
Kubernetes cluster unreachable
helm.sh/helm/v3/pkg/kube.(*Client).IsReach
able
    /tmp/go/pkg/mod/helm.sh/helm/v3@v3.11.1/pkg/kube/client.go:126
helm.sh/helm/v3/pkg/action.(*Get).Run
    /tmp/go/pkg/mod/helm.sh/helm/v3@v3.11.1/pkg/action/get.go:42
github.com/chaos-mesh/chaos-mesh/pkg/helm.(*HelmClient).Get
Release
    /home/runner/work/chaos-mesh/chaos-mesh/pkg/helm/helm_client.go:76
github.com/chaos-mesh/chaos-mesh/controllers/multicluster/remotecluster.(*Reconciler).ensureHelmRelease
    /home/runner/work/chaos-mesh/chaos-mesh/controll
ers/multicluster/remotecluster/controller.go:189
github.com/chaos-mesh/chaos-mesh/controllers/multicluster/remotecluster.(*Reconciler).Reconcile
    /home/runner/work/chaos-mesh/chaos-mesh/controllers/multicluster/remotecluster/contro
ller.go:120
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
    /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:122
sigs.k8s.io/controller-runtime/pkg/intern
al/controller.(*Controller).reconcileHandler
    /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:323
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem

    /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
    /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime
@v0.14.2/pkg/internal/controller/controller.go:235
runtime.goexit
    /usr/local/go/src/runtime/asm_amd64.s:1594
get release chaos-mesh, in namespace chaos-mesh
github.com/chaos-mesh/chaos-mesh/pkg/helm.(*HelmClient).GetRelease
    /
home/runner/work/chaos-mesh/chaos-mesh/pkg/helm/helm_client.go:78
github.com/chaos-mesh/chaos-mesh/controllers/multicluster/remotecluster.(*Reconciler).ensureHelmRelease
    /home/runner/work/chaos-mesh/chaos-mesh/controllers/multiclu
ster/remotecluster/controller.go:189
github.com/chaos-mesh/chaos-mesh/controllers/multicluster/remotecluster.(*Reconciler).Reconcile
    /home/runner/work/chaos-mesh/chaos-mesh/controllers/multicluster/remotecluster/controller.go:120\
nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
    /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:122
sigs.k8s.io/controller-runtime/pkg/internal/controlle
r.(*Controller).reconcileHandler
    /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:323
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    /tmp/go/
pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
    /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg
/internal/controller/controller.go:235
runtime.goexit
    /usr/local/go/src/runtime/asm_amd64.s:1594"}
github.com/chaos-mesh/chaos-mesh/controllers/multicluster/remotecluster.(*Reconciler).Reconcile
    /home/runner/work/chaos-mesh/chaos-mesh/controllers/multicluster/remotecluster/controller.go:122
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
    /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:122
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
    /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:323
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
    /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:235
```
