### ISSUE TITLE
DNSChaos error action does not take effect, when using go http client request

### ISSUE THREAD

**Issue by AllenZMC** [chaos-mesh/chaos-mesh#4027]
## Bug Report

**What version of Kubernetes are you using?**

v1.23

**What version of Chaos Mesh are you using?**

chaos-daemon  v2.5.2
chaos-coredns  v0.2.6

**What did you do? / Minimal Reproducible Example**

```
apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: dns-chaos-example
  namespace: chaos-mesh
spec:
  action: error
  mode: all
  patterns:
    - '*'
  selector:
    namespaces:
      - busybox
```

It is inaccessible to use curl to access the specified domain name, but it can still be accessed in the go program.
