### ISSUE TITLE
Certificate issue when creating PhysicalMachineChaos

### ISSUE THREAD

**Issue by dgiebert** [chaos-mesh/chaos-mesh#4042]
## Bug Report

**What version of Kubernetes are you using?**
v1.21.9+k3s1 

**What version of Chaos Mesh are you using?**
Controller manager Version: version.Info{GitVersion:"chart-2.5.2", GitCommit:"f20e0d6d5fe29b7b802ebc03110a96692ef15e08", BuildDate:"2023-04-13T08:48:40Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}

Installed using helm with no cert-manager, following the [docs](https://chaos-mesh.org/docs/production-installation-using-helm/#k3s) 

**What did you do? / Minimal Reproducible Example**
```yaml
kind: PhysicalMachineChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: test2
spec:
  action: stress-cpu
  address:
    - https://192.168.249.67:31767
  selector: {}
  mode: all
  uid: 1cb4b390-9e44-43ee-b43b-5ad9623fb57d
  stress-cpu:
    load: 10
    workers: 1
  duration: 60s
```

**What did you see**
`"https://X.X.X.X:31767/api/attack/stress": x509: certificate is valid for localhost, chaos-daemon.chaos-mesh.org, not chaosd.chaos-mesh.org`

It looks to me that either the controller is looking for the wrong domain name or that the name should be added as e.g. a SAN
