### ISSUE TITLE
remotecluster can not upgrade helm release

### ISSUE THREAD

**Issue by nioshield** [chaos-mesh/chaos-mesh#4063]
## Bug Report

**What version of Kubernetes are you using?**
v1.23.4
**What version of Chaos Mesh are you using?**
last 

**What did you do? / Minimal Reproducible Example**
update remotecluster can not upgrade helm release

1. Create a remote cluster using the yaml configuration file

```
apiVersion: chaos-mesh.org/v1alpha1
kind: RemoteCluster
metadata:
 name: remote-cls
spec:
 namespace: "chaos-mesh"
 version: "2.5.0"
 configOverride: eyJkYXNoYm9hcmQiOnsiY3JlYXRlIjpmYWxzZX19    //{"dashboard":{"create":false}}
 kubeConfig:
   secretRef:
      name: remote-cls
      namespace: default
      key: remote-cls
```
2.   edit configOverride to another value and apply to k8s
      `configOverride: eyJkYXNoYm9hcmQiOnsiY3JlYXRlIjp0cnVlfX0=`
3. verify remote cluster dashboard is not start

**What did you expect to see?**
expect the remote cluster to be reinstalled
**What did you see instead?**

**Output of chaosctl**
