### ISSUE TITLE
Chaos mesh doesn't support temporary AWS credentials - simply because it is not reading the aws_session_token

### ISSUE THREAD

**Issue by punarjitsingh-okta** [chaos-mesh/chaos-mesh#4065]
## Bug Report

Chaos mesh doesn't support the use of [temporary AWS credentials](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html) for awschaos. The simple reason being its not reading the valid session `aws_session_token` set in the kubernetes secrets or environment variables otherwise.

for example see: https://github.com/chaos-mesh/chaos-mesh/blob/2dc55a234727d08613ac1f5b9766c1523967c793/controllers/chaosimpl/awschaos/ec2stop/impl.go#L76

**What version of Kubernetes are you using?**
```
% kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.24.2
```

**What version of Chaos Mesh are you using?**
`2.5.2`

**What did you do? / Minimal Reproducible Example**
1. Prerequisites: Create an AWS IAM user and then create an IAM role from the IAM user and provide ec2 instance stop / start access.
2. Programmatically call AWS STS API `AssumeRole` and extract the resulting credentials and session token for the created role. Or use AWS cli to do the same.
3. Store the temporary credentials and session token in a kubernetes secret e.g.:
```
apiVersion: v1
kind: Secret
metadata:
  name: aws-temp-creds
  namespace: chaos-mesh
type: Opaque
stringData:
  aws_access_key_id:  'XXXXX'
  aws_secret_access_key: 'XXXXX'
  aws_session_token:  'XXXXX'
```
4. Create a simple aws choas like ec2stop and use temporary credentials for an aws role/profile that is provided by AWS STS API `AssumeRole`

e.g.:
```
apiVersion: chaos-mesh.org/v1alpha1
kind: AWSChaos
metadata:
  name: ec2-stop-experiment
  namespace: chaos-mesh
spec:
  action: ec2-stop
  secretName: aws-temp-creds
  awsRegion: 'us-east-1'
  ec2Instance: 'i-xyz'
  duration: '2m'
```

**What did you expect to see?**
ec2-stop-experiment is able to authenticate to aws using the aws-temp-creds and should not return 401 AuthFailure. For example if `instance-id i-xyz` doesn't exist, it simply returns a 400 bad request instance not found, but should not the 401 AuthFailure.

**What did you see instead?**

```
{"error": "operation error EC2: StopInstances, https response error StatusCode: 401, RequestID: xxx-xxx-xxx-xxx-xxx, api error AuthFailure: AWS was not able to validate the provided access credentials"}
```

**Output of chaosctl**
N/A
