### ISSUE TITLE
AWS Chaos Authorisation using AIM Roles

### ISSUE THREAD

**Issue by miketonks-form3** [chaos-mesh/chaos-mesh#4092]
## Feature Request

**Describe the feature you'd like:**

When using AWS Chaos, we would prefer not to pass credentials such as `aws_access_key_id` and `aws_secret_access_key`

We would like to use use IAM Roles to authorise chaos-mesh to talk to the AWS API.

**Teachability, Documentation, Adoption, Migration Strategy:**

AWS provides an integration for this, so long as your service is running in EKS: [IAM Roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)

By creating a service account with the correct permissions, the AWS SDK will pick this up automatically and handle the authorisation without needing secrets or credentials.

All that is needed is a small patch to the helm chart:

```
    - kustomize:
        patchesJson6902:
          - target:
              version: v1
              kind: ServiceAccount
              name: chaos-controller-manager
            patch:
              - op: add
                path: /metadata/annotations
                value:
                  'eks.amazonaws.com/role-arn': "arn:aws:iam::<blah-blah>"
```

This can be better supported by allowing role-arn to be passed in the chart values, and added to the ServiceAccount annotations if present.
