### ISSUE TITLE
Schedule slack notificate

### ISSUE THREAD

**Issue by kkkk4000** [chaos-mesh/chaos-mesh#4128]
### Discussed in https://github.com/chaos-mesh/chaos-mesh/discussions/4126

<div type='discussions-op-text'>

<sup>Originally posted by **kkkk4000** July 17, 2023</sup>
We use helm v [2.6.1](https://github.com/chaos-mesh/chaos-mesh/tree/master/helm/chaos-mesh)
We want to send notificates in slack https://chaos-mesh.org/docs/send-http-request-on-workflow/

Do you have CronWorkflow like [litmus](https://docs.litmuschaos.io/docs/concepts/chaos-workflow#what-is-a-cron-chaos-scenario)?
Or can we add `templateType: Schedule` in step `- name: slack-notificate` to run all steps at the same time (`schedule: "00 23 * * *"`)

_example chaos-mesh config:_

```
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: try-workflow-parallel
spec:
  entry: the-entry
  templates:
    - name: the-entry
      templateType: Parallel
      children:
        - workflow-pod-kill-schedule
        - slack-notificate
    - name: workflow-pod-kill-schedule
      templateType: Schedule
      schedule:
        schedule: "00 23 * * *"
        concurrencyPolicy: Allow
        type: "PodChaos"
        podChaos:
          selector:
            namespaces:
              - default
            labelSelectors:
              app: test
          mode: all
          action: pod-kill
    - name: slack-notificate
      templateType: Task
      task:
        container:
          name: slack-notificate-rendered-http-request
          image: curlimages/curl:7.78.0
          command:
            - curl
            - "-i"
            - "-s"
            - "-X"
            - POST
            - "-d"
            - >-
              {"channel": "#test-channel", "text": "Hello!", "icon_url":
              "https://cncf-branding.netlify.app/img/projects/chaosmesh/icon/color/chaosmesh-icon-color.png",
              "username": "Chaos-Mesh"}
            - "-H"
            - "Content-Type: application/json"
            - >-
              https://hooks.slack.com/*****
          resources: {}
```
