### ISSUE TITLE
PhysicalMachine network-partition: direction "both" not work with workflow

### ISSUE THREAD

**Issue by grzesrap** [chaos-mesh/chaos-mesh#4223]
## Bug Report

**What version of Kubernetes are you using?**
v1.21.8

**What version of Chaos Mesh are you using?**
v2.6.1

**What did you do? / Minimal Reproducible Example**
```
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: test-core-network-partition-fault-ws95d
  namespace: test-core-chaos-mesh
spec:
  entry: the-entry
  templates:
    - name: the-entry
      templateType: Serial
      children:
        - network-partition-fault
    - name: network-partition-fault
      templateType: PhysicalMachineChaos
      deadline: 20m
      physicalmachineChaos:
        action: network-partition
        mode: one
        selector:
          namespaces:
            - test-core-chaos-mesh
          labelSelectors:
            chaosd: enabled
        network-partition:
          device: eth0
          direction: both
          ip-address: "10.10.26.0/24"
```

**What did you expect to see?**
https://chaos-mesh.org/docs/simulate-network-chaos-in-physical-nodes/#simulate-network-partition-using-the-command-line-mode

direction -> string, values can be "to", "from" or "both" (default "both")

**What did you see instead?**
```
Error from server (Spec.spec: Invalid value: v1alpha1.PhysicalMachineChaosSpec{Action:"network-partition", PhysicalMachineSelector:v1alpha1.PhysicalMachineSelector{Address:[]string(nil), Selector:v1alpha1.PhysicalMachineSelectorSpec{GenericSelectorSpec:v1alpha1.GenericSelectorSpec{Namespaces:[]string{"test-core-chaos-mesh"}, FieldSelectors:map[string]string(nil), LabelSelectors:map[string]string{"chaosd":"enabled"}, ExpressionSelectors:v1alpha1.LabelSelectorRequirements(nil), AnnotationSelectors:map[string]string(nil)}, PhysicalMachines:map[string][]string(nil)}, Mode:"one", Value:""}, ExpInfo:v1alpha1.ExpInfo{UID:"69798b8f-ea0c-4ac8-9fac-77ce0ea22a3c", Action:"", StressCPU:(*v1alpha1.StressCPUSpec)(nil), StressMemory:(*v1alpha1.StressMemorySpec)(nil), DiskReadPayload:(*v1alpha1.DiskPayloadSpec)(nil), DiskWritePayload:(*v1alpha1.DiskPayloadSpec)(nil), DiskFill:(*v1alpha1.DiskFillSpec)(nil), NetworkCorrupt:(*v1alpha1.NetworkCorruptSpec)(nil), NetworkDuplicate:(*v1alpha1.NetworkDuplicateSpec)(nil), NetworkLoss:(*v1alpha1.NetworkLossSpec)(nil), NetworkDelay:(*v1alpha1.NetworkDelaySpec)(nil), NetworkPartition:(*v1alpha1.NetworkPartitionSpec)(0xc001d774a0), NetworkDNS:(*v1alpha1.NetworkDNSSpec)(nil), NetworkBandwidth:(*v1alpha1.NetworkBandwidthSpec)(nil), NetworkFlood:(*v1alpha1.NetworkFloodSpec)(nil), NetworkDown:(*v1alpha1.NetworkDownSpec)(nil), Process:(*v1alpha1.ProcessSpec)(nil), JVMException:(*v1alpha1.JVMExceptionSpec)(nil), JVMGC:(*v1alpha1.JVMGCSpec)(nil), JVMLatency:(*v1alpha1.JVMLatencySpec)(nil), JVMReturn:(*v1alpha1.JVMReturnSpec)(nil), JVMStress:(*v1alpha1.JVMStressSpec)(nil), JVMRuleData:(*v1alpha1.JVMRuleDataSpec)(nil), JVMMySQL:(*v1alpha1.PMJVMMySQLSpec)(nil), Clock:(*v1alpha1.ClockSpec)(nil), RedisExpiration:(*v1alpha1.RedisExpirationSpec)(nil), RedisPenetration:(*v1alpha1.RedisPenetrationSpec)(nil), RedisCacheLimit:(*v1alpha1.RedisCacheLimitSpec)(nil), RedisSentinelRestart:(*v1alpha1.RedisSentinelRestartSpec)(nil), RedisSentinelStop:(*v1alpha1.RedisSentinelStopSpec)(nil), KafkaFill:(*v1alpha1.KafkaFillSpec)(nil), KafkaFlood:(*v1alpha1.KafkaFloodSpec)(nil), KafkaIO:(*v1alpha1.KafkaIOSpec)(nil), HTTPAbort:(*v1alpha1.HTTPAbortSpec)(nil), HTTPDelay:(*v1alpha1.HTTPDelaySpec)(nil), HTTPConfig:(*v1alpha1.HTTPConfigSpec)(nil), HTTPRequest:(*v1alpha1.HTTPRequestSpec)(nil), FileCreate:(*v1alpha1.FileCreateSpec)(nil), FileModifyPrivilege:(*v1alpha1.FileModifyPrivilegeSpec)(nil), FileDelete:(*v1alpha1.FileDeleteSpec)(nil), FileRename:(*v1alpha1.FileRenameSpec)(nil), FileAppend:(*v1alpha1.FileAppendSpec)(nil), FileReplace:(*v1alpha1.FileReplaceSpec)(nil), VM:(*v1alpha1.VMSpec)(nil), UserDefined:(*v1alpha1.UserDefinedSpec)(nil)}, Duration:(*string)(nil), RemoteCluster:""}: direction should be one of 'to' and 'from'): error when creating "00-schedule-kubelet-test.yaml": admission webhook "vworkflow.kb.io" denied the request: Spec.spec: Invalid value: v1alpha1.PhysicalMachineChaosSpec{Action:"network-partition", PhysicalMachineSelector:v1alpha1.PhysicalMachineSelector{Address:[]string(nil), Selector:v1alpha1.PhysicalMachineSelectorSpec{GenericSelectorSpec:v1alpha1.GenericSelectorSpec{Namespaces:[]string{"test-core-chaos-mesh"}, FieldSelectors:map[string]string(nil), LabelSelectors:map[string]string{"chaosd":"enabled"}, ExpressionSelectors:v1alpha1.LabelSelectorRequirements(nil), AnnotationSelectors:map[string]string(nil)}, PhysicalMachines:map[string][]string(nil)}, Mode:"one", Value:""}, ExpInfo:v1alpha1.ExpInfo{UID:"69798b8f-ea0c-4ac8-9fac-77ce0ea22a3c", Action:"", StressCPU:(*v1alpha1.StressCPUSpec)(nil), StressMemory:(*v1alpha1.StressMemorySpec)(nil), DiskReadPayload:(*v1alpha1.DiskPayloadSpec)(nil), DiskWritePayload:(*v1alpha1.DiskPayloadSpec)(nil), DiskFill:(*v1alpha1.DiskFillSpec)(nil), NetworkCorrupt:(*v1alpha1.NetworkCorruptSpec)(nil), NetworkDuplicate:(*v1alpha1.NetworkDuplicateSpec)(nil), NetworkLoss:(*v1alpha1.NetworkLossSpec)(nil), NetworkDelay:(*v1alpha1.NetworkDelaySpec)(nil), NetworkPartition:(*v1alpha1.NetworkPartitionSpec)(0xc001d774a0), NetworkDNS:(*v1alpha1.NetworkDNSSpec)(nil), NetworkBandwidth:(*v1alpha1.NetworkBandwidthSpec)(nil), NetworkFlood:(*v1alpha1.NetworkFloodSpec)(nil), NetworkDown:(*v1alpha1.NetworkDownSpec)(nil), Process:(*v1alpha1.ProcessSpec)(nil), JVMException:(*v1alpha1.JVMExceptionSpec)(nil), JVMGC:(*v1alpha1.JVMGCSpec)(nil), JVMLatency:(*v1alpha1.JVMLatencySpec)(nil), JVMReturn:(*v1alpha1.JVMReturnSpec)(nil), JVMStress:(*v1alpha1.JVMStressSpec)(nil), JVMRuleData:(*v1alpha1.JVMRuleDataSpec)(nil), JVMMySQL:(*v1alpha1.PMJVMMySQLSpec)(nil), Clock:(*v1alpha1.ClockSpec)(nil), RedisExpiration:(*v1alpha1.RedisExpirationSpec)(nil), RedisPenetration:(*v1alpha1.RedisPenetrationSpec)(nil), RedisCacheLimit:(*v1alpha1.RedisCacheLimitSpec)(nil), RedisSentinelRestart:(*v1alpha1.RedisSentinelRestartSpec)(nil), RedisSentinelStop:(*v1alpha1.RedisSentinelStopSpec)(nil), KafkaFill:(*v1alpha1.KafkaFillSpec)(nil), KafkaFlood:(*v1alpha1.KafkaFloodSpec)(nil), KafkaIO:(*v1alpha1.KafkaIOSpec)(nil), HTTPAbort:(*v1alpha1.HTTPAbortSpec)(nil), HTTPDelay:(*v1alpha1.HTTPDelaySpec)(nil), HTTPConfig:(*v1alpha1.HTTPConfigSpec)(nil), HTTPRequest:(*v1alpha1.HTTPRequestSpec)(nil), FileCreate:(*v1alpha1.FileCreateSpec)(nil), FileModifyPrivilege:(*v1alpha1.FileModifyPrivilegeSpec)(nil), FileDelete:(*v1alpha1.FileDeleteSpec)(nil), FileRename:(*v1alpha1.FileRenameSpec)(nil), FileAppend:(*v1alpha1.FileAppendSpec)(nil), FileReplace:(*v1alpha1.FileReplaceSpec)(nil), VM:(*v1alpha1.VMSpec)(nil), UserDefined:(*v1alpha1.UserDefinedSpec)(nil)}, Duration:(*string)(nil), RemoteCluster:""}: direction should be one of 'to' and 'from'
```

**Output of chaosctl**
