### ISSUE TITLE
Helm deployment with pvc fails because of missing rights

### ISSUE THREAD

**Issue by andres32168** [chaos-mesh/chaos-mesh#4224]
## Bug Report

**What version of Kubernetes are you using?**

**What version of Chaos Mesh are you using?**
2.6.2

**What did you do? / Minimal Reproducible Example**
```
dashboard:
    securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
    create: true
    resources:
        requests:
            cpu: 25m
            memory: 256Mi
        limits:
            cpu: 250m
            memory: 512Mi

    persistentVolume:
        enabled: true
        size: 8Gi
        storageClassName: default
        mountPath: /data
```

**What did you expect to see?**
I was expected to see that chaos-mesh dashboard is installed with da persistent volume claim.
The persistent volume claim is created but the dashboard isn't starting. See error log.
**What did you see instead?**
Following error is produced
See error-log
[chaos-mesh-error.log](https://github.com/chaos-mesh/chaos-mesh/files/12869818/chaos-mesh-error.log)

** Possible solution 1**
The issue seems to occur because of missing permissions to /data
Without pvc the /data directory has 777 and with pvc the directory has only 755.
Add a initContainer to chaos-dashboard-deployment.yaml like in prometheus-deployment.yaml

```
    spec:
      {{- if .Values.prometheus.serviceAccount }}
      serviceAccount: {{ .Values.prometheus.serviceAccount }}
      {{- end }}
      priorityClassName: {{ .Values.prometheus.priorityClassName}}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      initContainers:
        - name: data-permission-fix
          image: busybox
          command: ["/bin/chmod","-R","777", "/data"]
          volumeMounts:
            - name: data
              mountPath: /data
```

** Possible solution 2 **
Add fsGroup to securityContext

```
dashboard:
    securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
```
