### ISSUE TITLE
Chaos Test Deviates from Specified Schedule and Randomly Triggers

### ISSUE THREAD

**Issue by artur-akh** [chaos-mesh/chaos-mesh#4236]
## Bug Report

**What version of Kubernetes are you using?**
v1.23.15-v1.23.17
**What version of Chaos Mesh are you using?**
2.6.1

**What did you do? / Minimal Reproducible Example**
Hello. We have set up chaos testing on a schedule using the following configuration:
```
{{- $zones := index .Values.zones .Values.environmentInstance }}
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: {{ template "services.name" . }}-zone-partition
spec:
  schedule: "0 18 * * 4"
  historyLimit: 1
  concurrencyPolicy: 'Forbid'
  startingDeadlineSeconds: 1800
  type: 'Workflow'
  workflow:
    entry: entry
    templates:
      - name: entry
        templateType: Serial
        children:
          - network-partition-random-zone

      - name: network-partition-random-zone
        templateType: Task
        task:
          container:
            name: random-number-selector
            image: debian
            command: ["/bin/bash"]
            # date used as a seed to achieve correlation between different services
            args: ["-c", "RANDOM=`date +%Y%m%d`; number=$RANDOM; let \"number %= {{ len $zones }}\"; echo $number"]
        conditionalBranches:
        {{- range $zoneIndex, $zone := $zones }}
          - expression: 'stdout == "{{ $zoneIndex }}"'
            target: network-partition-{{ $zone }}
        {{- end }}

      {{- range $zone := $zones }}
      - name: network-partition-{{ $zone }}
        templateType: NetworkChaos
        deadline: 5m
        networkChaos:
          selector:
            labelSelectors:
              app: {{ if $.Values.services.canary.enabled }}
                   {{- template "services.name" $ }}-primary
                   {{- else }}
                   {{- template "services.name" $ }}
                   {{- end }}
            nodeSelectors:
              failure-domain.beta.kubernetes.io/zone: {{ $zone }}
          mode: all
          action: partition
          direction: to
      {{- end }}
```
Our values:
```
environmentInstance: eu-aws
zones:
  eu-aws:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c
```
Additionally, we are using the startingDeadlineSeconds: 1800 parameter in our configuration.

**What did you expect to see?**
We expected the chaos test to run strictly according to the schedule "0 18 * * 4".
**What did you see instead?**
The chaos test occasionally starts running randomly, not adhering to the specified schedule. This issue is critical for us, and we are urgently seeking a solution.

**Additional Information**
I'm attaching logs from GrafanaLoki for further insight:

{ pod =~ "chaos-.*"} |~ "operations-api-async-services-primary"
[Explore-logs-2023-10-24 16_54_08.txt](https://github.com/chaos-mesh/chaos-mesh/files/13114749/Explore-logs-2023-10-24.16_54_08.txt)

{ pod =~ "chaos-.*"}
[Explore-logs-2023-10-24 16_55_24.txt](https://github.com/chaos-mesh/chaos-mesh/files/13114759/Explore-logs-2023-10-24.16_55_24.txt)
