### ISSUE TITLE
IO latency chaos causes "no such file or directory" 

### ISSUE THREAD

**Issue by sticnarf** [chaos-mesh/chaos-mesh#4298]
## Bug Report

**What version of Kubernetes are you using?**

```
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.6-aliyun.1", GitCommit:"5296768e052ba56e92b5d5bf7b52d33973a34c6f", GitTreeState:"clean", BuildDate:"2023-04-19T06:36:28Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**

```
Controller manager Version: version.Info{GitVersion:"chart-2.5.1", GitCommit:"08b173528f315d3a6621b9be5566e74ab9e0d35d", BuildDate:"2023-01-14T02:33:15Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do? / Minimal Reproducible Example**

I applied an IO latency chaos.

```
kind: IOChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: # ...
  name: io-latency-u4oof
spec:
  selector:
    # ...
  mode: one
  action: latency
  delay: 30000ms
  percent: 100
  volumePath: /data
  duration: 30000ms
```

**What did you expect to see?**

IO just gets stuck, but no error should occur.

**What did you see instead?**

Shortly after the chaos is applied, our application raised some "no such file or directory" errors. Our application were opening and reading files during the chaos.

**Output of chaosctl**

chaosctl debug iochaos output: [iochaos.txt](https://github.com/chaos-mesh/chaos-mesh/files/13768224/iochaos.txt)

chaos daemon logs: 
[chaos-daemon-9rdlk_chaos-daemon.log](https://github.com/chaos-mesh/chaos-mesh/files/13768238/chaos-daemon-9rdlk_chaos-daemon.log)

The request raising error started at `15:04:22.354Z`, and the `No such file or directory` error occurs at `23:04:22.361Z`. The time range seems to overlap with toda injecting chaos.
