### ISSUE TITLE
HTTP Chaos experiment hung in deleting state

### ISSUE THREAD

**Issue by ashish-kumar-r** [chaos-mesh/chaos-mesh#4311]
# Bug Report

**What version of Kubernetes are you using?**
Server Version: v1.27.3

**What version of Chaos Mesh are you using?**
GitVersion:"chart-2.6.2", GitCommit:"f1dacea430068701a6dd48fdde7ad7ed97b49f0e", BuildDate:"2023-08-23T07:03:24Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/arm64"

**What did you do? / Minimal Reproducible Example**
- Installed Chaos-Mesh on Kind cluster with Helm values as defined below

```
clusterScoped: true

rbac:
  create: true

chaosDaemon:
  runtime: containerd
  socketPath: /run/containerd/containerd.sock
  nodeSelector:
    chaos: "enabled"

```
- The cluster consisted 2 nodes, one with the label chaos=enabled, Idea is to limit daemonset installation on selected nodegroups
- Perform to run HTTPChaos on a Pod running on Node where the daemonset isn't running, to demonstrate the failure due to missing daemonIP
- Clean up the experiment using Archive option from Dashboard. (Also tried to use the annotation _chaos-mesh.chaos-mesh.org/cleanFinalizer=forced_)

**What did you expect to see?**
The HTTP chaos experiment to be deleted from Dashboard and K8s objects

**What did you see instead?**
The experiment stays as deleting state in Chaos dashboard.
![image](https://github.com/chaos-mesh/chaos-mesh/assets/58840673/e4f5435e-66cc-42d6-bed2-ff0abfaf7749)

The K8s object isn't removed from the Cluster
<img width="464" alt="image" src="https://github.com/chaos-mesh/chaos-mesh/assets/58840673/d2fc96a6-9462-4800-961c-6256b76f870d">

**Output of chaosctl**
