### ISSUE TITLE
chore: add service account creation as optional and allow podSecurityContext

### ISSUE THREAD

**Issue by awatterson22** [chaos-mesh/chaos-mesh#4353]
**What would you like to be added**:

For helmchart, could the following fields be added?

- In `values.yaml`, change the `serviceAccount` field to look like this:
```YAML
controllerManager:
  .
  .
  serviceAccount:
    create: true
    name: chaos-controller-manager
```
- In `values.yaml`:  `chaosDaemon.podSecurityContext: {}`
```YAML
      chaosDaemon:
        .
        .
        podSecurityPolicy: false
        podSecurityContext: {}
```

- Then in `helm/chaos-mesh/templates/controller-manager-deployment.yaml`, change the if statement to this:
```YAML
{{- if .Values.controllerManager.serviceAccount.create }}
serviceAccountName: {{ .Values.controllerManager.serviceAccount.name }}
```
- Then in `helm/chaos-mesh/templates/controller-manager-rbac.yaml`, add the following if statement around the serviceAccount:
```YAML
{{- if .Values.controllerManager.serviceAccount.create }}
.
.
.
{{- end }}
```

**Why is this needed**:
- I would like to be able to not ignore the service account creation as I create it in another process and would like the ability to template the podSecurityContext for the chaosDaemon.
