### ISSUE TITLE
HTTPChaos Affecting Multiple Paths Instead of Targeted Path in API Service

### ISSUE THREAD

**Issue by dommgifer** [chaos-mesh/chaos-mesh#4453]
## Bug Report

**What version of Kubernetes are you using?**
Openshift 4.12.40

**What version of Chaos Mesh are you using?**
2.6.3

**What did you do? / Minimal Reproducible Example**
I have a simple API service with three paths:
/hello
/actuator/health
/secrets

I used HTTPChaos to add a response delay to the /hello path.
```
kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: demo
  name: http-response-delay
spec:
  selector:
    namespaces:
      - demo
    labelSelectors:
      app: api-test
  mode: all
  target: Response
  delay: 5s
  port: 8080
  path: /hello
  method: GET
  duration: 2m

```
**What did you expect to see?**

I expected to see the API response delayed only for the /hello path.

**What did you see instead?**

When I tried to call the /actuator/health and /secrets paths, these paths also experienced response delays, causing the k8s Liveness probe for /actuator/health to fail and the pod to restart.

**Output of chaosctl**
