### ISSUE TITLE
Simulate HTTP replace Faults, causing my pod to fail to resolve dns properly

### ISSUE THREAD

**Issue by Drewolf** [chaos-mesh/chaos-mesh#4466]
## Bug Report

**What version of Kubernetes are you using?**
华为云 CCE Turbo v1.21

**What version of Chaos Mesh are you using?**
Controller manager Version: version.Info{GitVersion:"chart-2.6.3", GitCommit:"b159d1c5a361ca350ca7789c9eb7fc917479db39", BuildDate:"2024-01-23T15:04:53Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}

**What did you do? / Minimal Reproducible Example**
I created an experiment, after the experiment ran, my pod couldn't resolve dns properly
```
kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: asset
  name: http-response-5
  annotations:
    experiment.chaos-mesh.org/pause: 'false'
spec:
  selector:
    namespaces:
      - asset
    labelSelectors:
      app: asset-manager-gateway-open
  mode: all
  target: Response
  replace:
    body: ewoJImNvZGUiOiAyMDAsCgkibXNnIjogInN1Y2Nlc3MiLAoJImRhdGEiOiB7fQp9
  port: 80
  path: /assets/video/detail
  method: POST
  duration: 2m
```
Before experiment run：
![image](https://github.com/user-attachments/assets/0c416c12-0402-4d47-ad2c-c402bf32cbaa)

After experiment run：
![image](https://github.com/user-attachments/assets/4f015451-71d2-4f42-bc3b-4282f491c842)

**What did you expect to see?**
replaces part of content in HTTP request or response messages

**What did you see instead?**
pod can not resolv dns

**Output of chaosctl**
![image](https://github.com/user-attachments/assets/42db1f78-583f-4380-8e97-46a328f5d5dc)
