### ISSUE TITLE
gracePeriod don't work  as expected

### ISSUE THREAD

**Issue by Chen-Xintong** [chaos-mesh/chaos-mesh#4468]
## Bug Report

**What version of Kubernetes are you using?**
1.29

**What version of Chaos Mesh are you using?**
2.6.3

**What did you do? / Minimal Reproducible Example**
According to the user guide, I want add a `gracePeriod` parameter when running pod-kill to delay the time of pod-kill, but this parameter does not seem to work.
https://chaos-mesh.org/docs/simulate-pod-chaos-on-kubernetes/#field-description

Here's my defination:
```
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  generateName: pod-deletion-1
  namespace: chaos-mesh
  labels:
    app: pod-deletion-1
spec:
  action: pod-kill
  gracePeriod: 20
  mode: one
  selector:
    namespaces:
    - cert-manager
    labelSelectors:
      app: cert-manager
```

**What did you expect to see?**
I expect the pod-kill operation will be execute after 20 seconds, but when I apply this configuration, the pod is killed immediately.
