### ISSUE TITLE
Network Partition in NetworkChaos behaves like both when set to from or to

### ISSUE THREAD

**Issue by thuuuha17** [chaos-mesh/chaos-mesh#4477]
## Bug Report

**What version of Kubernetes are you using?**
K8S v1.25.16

**What version of Chaos Mesh are you using?**
Chaos Mesh version v2.6.1

**What did you do? / Minimal Reproducible Example**
I encountered an issue with the partition network attack in NetworkChaos.

Here are the steps to reproduce the issue:

Configure a NetworkChaos experiment with a partition network attack.
Set the direction to from or to.
Observe the traffic between the affected pods.

**What did you expect to see?**
When set to from, the pod should only be unable to send traffic, while it should still be able to receive it.
When set to to, the pod should only be unable to receive traffic, while it should still be able to send it.

**What did you see instead?**
Traffic is disrupted in both directions regardless of whether from or to is set, behaving as if it was set to both.

**My yaml file**
kind: NetworkChaos
```
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: learn
  name: networkpartition
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  selector:
    namespaces:
      - learn
    labelSelectors:
      app.kubernetes.io/instance: devops-demo
  mode: all
  action: partition
  duration: 1m
  direction: to
```
