### ISSUE TITLE
The certificates YAML cause endless OutOfSync loop in ArgoCD

### ISSUE THREAD

**Issue by MarkKharitonov** [chaos-mesh/chaos-mesh#4481]
## Bug Report

**What version of Kubernetes are you using?**
```
mark@L-R910LPKW:~$ k version -o yaml
clientVersion:
  buildDate: "2022-12-08T19:58:30Z"
  compiler: gc
  gitCommit: b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d
  gitTreeState: clean
  gitVersion: v1.26.0
  goVersion: go1.19.4
  major: "1"
  minor: "26"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2024-04-12T23:22:53Z"
  compiler: gc
  gitCommit: 5214c5ddb5785ed9d8e47e79e67181e205555067
  gitTreeState: clean
  gitVersion: v1.28.3
  goVersion: go1.20.10
  major: "1"
  minor: "28"
  platform: linux/amd64

WARNING: version difference between client (1.26) and server (1.28) exceeds the supported minor version skew of +/-1
mark@L-R910LPKW:~$
```

**What version of Chaos Mesh are you using?**
**v2.6.4**

**What did you do? / Minimal Reproducible Example**
Deployed the HELM chart with the following ArgoCD application:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: >-
      eastus2-green-systemtools:argoproj.io/Application:system-d-argocd/eastus2-green-chaos-mesh
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    chip/app-kind: systemtool
    chip/cluster: eastus2-green
    chip/systemtool: chaos-mesh
  name: eastus2-green-chaos-mesh
  namespace: system-d-argocd
spec:
  destination:
    name: eastus2-green
    namespace: system-d-chaos-mesh
  project: eastus2-green-systemtools
  source:
    chart: chaos-mesh
    helm:
      releaseName: chaos-mesh
      skipCrds: true
      valuesObject:
        chaosDaemon:
          runtime: containerd
          socketPath: /run/containerd/containerd.sock
        dashboard:
          ingress:
            annotations:
              nginx.ingress.kubernetes.io/configuration-snippet: |
                sub_filter '<head>' '<head> <base href="/chaos-mesh/">';
              nginx.ingress.kubernetes.io/rewrite-target: /$1
            certManager: true
            enabled: true
            hosts:
              - name: eastus2-app505.np.xyz.com
            ingressClassName: nginx-internal
            paths:
              - /chaos-mesh(?:/(.*)|$)
        dnsServer:
          image: app505deploycr.azurecr.io/chaos-mesh/chaos-coredns:v0.2.6
        images:
          registry: app505deploycr.azurecr.io
        webhook:
          certManager:
            enabled: true
    repoURL: https://charts.chaos-mesh.org
    targetRevision: v2.6.4
  syncPolicy:
    automated:
      prune: true
    managedNamespaceMetadata:
      annotations:
        scheduler.alpha.kubernetes.io/defaultTolerations: >-
          [{"operator": "Equal", "effect": "NoSchedule", "key": "dedicated",
          "value": "tools"}]
        scheduler.alpha.kubernetes.io/node-selector: agentpool=toolsnp1
    syncOptions:
      - CreateNamespace=true
```

**What did you expect to see?**
All the chaos mesh objects created from the HELM chart in sync.

**What did you see instead?**
The 3 certificates having `isCA = false` being out of sync.

**The root cause**
When creating a certificate with `isCA = false` and getting it back from the API server, the `isCA` field is removed, if it is `false`. This confuses ArgoCD, which does expect to find `isCA = false` and so it enters an endless out-of-sync loop.

An additional point of friction is the `duration = 43800h` on one of the certificates. It comes back from the API server as `duration = 
 43800h0m0s`. BTW, this is a problem in only one of the certificates, the others use `43800h0m0s` already.

**The workaround**
Adding the following to the ArgoCD application object:
```
ignoreDifferences:
  - group: cert-manager.io
    kind: Certificate
    namespace: system-d-chaos-mesh
    jqPathExpressions:
      - .spec | select(.isCA == false).isCA
      - .spec | select(.duration == "43800h").duration
```
However, it would be nice if the certificates created by the chaos mesh were more ArgoCD friendly.
