### ISSUE TITLE
MemoryStressor does not support the time property contrary to the documentation.

### ISSUE THREAD

**Issue by MarkKharitonov** [chaos-mesh/chaos-mesh#4485]
## Bug Report

**What version of Kubernetes are you using?**
**1.28.3**

**What version of Chaos Mesh are you using?**
**2.6.4**

**What did you do? / Minimal Reproducible Example**
Create the following object:
```
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: mem-stress
spec:
  mode: all
  selector:
    namespaces:
      - hpa-test
  stressors:
    memory:
      workers: 1
      size: 95%
      time: 10min
  duration: 1h
```

**What did you expect to see?**
The object is created successfully.

**What did you see instead?**
```
mark@L-R910LPKW:~/hpa-test$ k create -f mem-stress.yaml
Error from server (BadRequest): error when creating "mem-stress.yaml": StressChaos in version "v1alpha1" cannot be handled as a StressChaos: strict decoding error: unknown field "spec.stressors.memory.time"
mark@L-R910LPKW:~/hpa-test$
```

**Additional Details**
According to https://chaos-mesh.org/docs/simulate-heavy-stress-on-kubernetes/#memorystressor we should be able to provide the time property:
![image](https://github.com/user-attachments/assets/eb22ce96-a695-4e9d-997a-6aaeb52553b6)

However, the respective CRD does not define this field:
```
mark@L-R910LPKW:~/hpa-test$ k get crds stresschaos.chaos-mesh.org -o yaml | yq '.spec.versions[].schema.openAPIV3Schema.properties.spec.properties.stressors.properties.memory.properties|keys'
- oomScoreAdj
- options
- size
- workers
mark@L-R910LPKW:~/hpa-test$
```

This is a bit weird, because the [documentation for v2.4.3](https://chaos-mesh.org/docs/2.4.3/simulate-heavy-stress-on-kubernetes/#memorystressor) claims the same. The current version is **v2.6.4**, so I am not sure what does it mean.

**Comment by mertcancam** [comment]
It appears that the documentation is incorrect; however, the functionality is still accessible by passing the `--time` parameter through the `options` property. Strangely, this isn't mentioned in the documentation, and the only way to discover it is by examining the CRD itself. 

Here’s an example of how to use it:

```yaml
  stressors:
    memory:
      workers: 1
      size: '1GiB'
      options: ["--time 300s"]
```

When applied, you'll see the process executed as follows:

```bash
memStress --size 1GiB --workers 1 --time 300s --client 1
```
