### ISSUE TITLE
Execution error for DNSChaos tests

### ISSUE THREAD

**Issue by liamgib** [chaos-mesh/chaos-mesh#4487]
## Bug Report

**What version of Kubernetes are you using?**

Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4

**What version of Chaos Mesh are you using?**

Controller manager Version: version.Info{GitVersion:"chart-2.6.3", GitCommit:"b159d1c5a361ca350ca7789c9eb7fc917479db39", BuildDate:"2024-01-23T15:04:53Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}

**What did you do? / Minimal Reproducible Example**

We are running Chaos Mesh in an AKS cluster, installed via Helm. When attempting to execute a DNSChaos test, we encounter a panic stack trace. This error occurs whether we run the test through the dashboard or using a CRD definition.

Here is a copy of our CRD definition:
```
apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: chaos-1725843790-error
  namespace: chaos-mesh
spec:
  action: error
  mode: all
  duration: "10m"
  selector:
    namespaces:
      - targetnamespace
    labelSelectors:
      app: example
```

```
Operation:  Apply
        Timestamp:  2024-09-09T01:04:24Z
        Type:       Failed
        Message:    rpc error: code = Unknown desc = error code: exit status 101, msg: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:108:37
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: __libc_start_main
  14: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
``` 

**What did you expect to see?**
DNSChaos injection is successful

**What did you see instead?**
Thread panic/Execution failure

**Output of chaosctl**
