### ISSUE TITLE
Chaos Dashboard Experiment Not Submitting

### ISSUE THREAD

**Issue by neerajverma004** [chaos-mesh/chaos-mesh#4494]
## Bug Report
What version of Kubernetes are you using?
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2

What version of Chaos Mesh are you using?
--version 2.6.4
What did you do? / Minimal Reproducible Example
I am going to Dashboard and trying to create an experiment as shown below. 
  
![chaos1](https://github.com/user-attachments/assets/e3612ec4-83e3-4bb7-8afe-34f0aada0329)

On the below screen it says all steps are completed but the submit button is not working. The button is not disabled but it doesn’t do anything. I have reinstalled the dashboard and chaos mesh multiple time but it doesn’t work. 

![chaos2](https://github.com/user-attachments/assets/e3d576f6-20c7-43de-8ebf-7286d108ae38)

What did you expect to see?
A new experiment added to the list of experiments. 
What did you see instead?
No Action

**Comment by g1eny0ung** [comment]
Would you please provide more information like devtools messages? There may be some errors in devtools.

**Comment by moefarag1** [comment]
I'm experiencing the same issue as above

**Comment by neerajverma004** [comment]
Hi, I fixed the issue. I was missing the RoleBinding for my namespace. Once done it started working. Thanks

**Comment by bumper-jorge-pino** [comment]
I'm experiencing exactly the same issue but I haven't found any fixes.

I'm using Chaos Mesh version 2.7.0.

Logs from dashboard and and controllers show no errors... I'm using the following RBAC and the experiment is pointing to resources in `prod` namespace:

```
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: prod
  name: account-cluster-manager-socvx
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-cluster-manager-socvx
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: [ "*" ]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-cluster-manager-socvx
subjects:
- kind: ServiceAccount
  name: account-cluster-manager-socvx
  namespace: prod
roleRef:
  kind: ClusterRole
  name: role-cluster-manager-socvx
  apiGroup: rbac.authorization.k8s.io
```
