### ISSUE TITLE
[Bug]: The serial workflow will not continue after the pod kill is executed in the workflow

### ISSUE THREAD

**Issue by boxker** [chaos-mesh/chaos-mesh#4539]
### Chaos Mesh Version

v2.7.0

### Kubernetes Version

v1.28.5+k3s1

### Describe the bug

![image](https://github.com/user-attachments/assets/1e4762b0-9270-43d9-acf6-0393e0a47af5)

Hello, when the pod kill is executed in my workflow, the serial workflow will not continue. It can be observed that the pod kill has been executed, but the workflow is still blocked and does not continue.

**Comment by boxker** [comment]
```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  namespace: chaos-mesh
  name: w3
spec:
  entry: s1
  templates:
    - name: s1
      templateType: Serial
      deadline: 1200s
      children:
        - '1'
    - name: '1'
      templateType: PodChaos
      podChaos:
        selector:
          namespaces:
            - default
          labelSelectors:
            app: nginx
        mode: one
        action: pod-kill
```

**Comment by boxker** [comment]
Another example is as follows：

![image](https://github.com/user-attachments/assets/952870de-80c7-4f7d-95f6-ba11be31a0f0)

**Comment by STRRL** [comment]
Hi @boxker, it seems the behavior is expected, the `Serial` node means its children nodes will execute one by one in serial. 

From the Workflow your provided, there is only one PodChaos experiment called `1` here, so it should be only one experiment executed, and not more in the next.

Could you tell us your expectations? Thanks

**Comment by boxker** [comment]
Hi, my example above may not be clear enough. Here is a workflow with a problem: two parallel experiments 1 and 2 are created, followed by two serial experiments 3 and 4. When the workflow finishes executing 3, it does not continue to execute 4, but is blocked on 3. The expectation is that 4 can be continued after 3 is completed. The following is the yaml file:

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  namespace: chaos-mesh
  name: w2
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      deadline: 1200s
      children:
        - p
        - s
    - name: p
      templateType: Parallel
      children:
        - '1'
        - '2'
    - name: '1'
      templateType: StressChaos
      deadline: 60s
      stressChaos:
        selector:
          namespaces:
            - default
          labelSelectors:
            app: nginx
        mode: one
        stressors:
          cpu:
            workers: 1
            load: 100
    - name: '2'
      templateType: StressChaos
      deadline: 60s
      stressChaos:
        selector:
          namespaces:
            - chaos-mesh
        mode: one
        stressors:
          cpu:
            workers: 1
            load: 50
    - name: s
      templateType: Serial
      children:
        - '3'
        - '4'
    - name: '3'
      templateType: PodChaos
      podChaos:
        selector:
          namespaces:
            - default
          labelSelectors:
            app: nginx
        mode: one
        action: pod-kill
    - name: '4'
      templateType: PodChaos
      podChaos:
        selector:
          namespaces:
            - default
          labelSelectors:
            app: nginx
        mode: one
        action: pod-kill

```

**Comment by snapfit05** [comment]
I have the exact same issue (v2.8.0), the workflow is stuck in the pod-kill step. This is a minimal example to reproduce, suspend-0 will never be executed.

```
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  namespace: experiments
  name: workflow-pod-kill-1
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      deadline: 5m
      children:
        - pod-kill-0
        - suspend-0
    - name: pod-kill-0
      templateType: PodChaos
      podChaos:
        selector:
          namespaces:
            - default
          labelSelectors:
            app: my-app
        mode: all
        action: pod-kill
    - name: suspend-0
      templateType: Suspend
      deadline: 1m
```

Chaos Events:

```
"Object ID","Namespace","Name","Kind","Time","Type","Reason","Message"
d3921a9e-ab02-4acc-9383-c330337ed87d,experiments,pod-kill-0-kv5cm-ljr9c,PodChaos,2025-10-17T11:25:22Z,Normal,Updated,Successfully update records of resource
d3921a9e-ab02-4acc-9383-c330337ed87d,experiments,pod-kill-0-kv5cm-ljr9c,PodChaos,2025-10-17T11:25:22Z,Normal,Recovered,Successfully recover chaos for default/my-app-58797dc8d5-4splv
d3921a9e-ab02-4acc-9383-c330337ed87d,experiments,pod-kill-0-kv5cm-ljr9c,PodChaos,2025-10-17T11:25:22Z,Normal,Updated,Successfully update desiredPhase of resource
d3921a9e-ab02-4acc-9383-c330337ed87d,experiments,pod-kill-0-kv5cm-ljr9c,PodChaos,2025-10-17T11:25:22Z,Normal,Deleted,Experiment has been deleted
504871ed-9aac-4ff2-afb4-19355f5e2faa,experiments,pod-kill-0-kv5cm,WorkflowNode,2025-10-17T11:25:22Z,Normal,ChaosCRDeleted,chaos CR pod-kill-0-kv5cm-ljr9c deleted
504871ed-9aac-4ff2-afb4-19355f5e2faa,experiments,pod-kill-0-kv5cm,WorkflowNode,2025-10-17T11:25:22Z,Normal,ParentNodeDeadlineExceed,deadline exceed bscause parent node entry-xbr75 deadline exceed
504871ed-9aac-4ff2-afb4-19355f5e2faa,experiments,pod-kill-0-kv5cm,WorkflowNode,2025-10-17T11:25:22Z,Normal,ParentNodeDeadlineExceed,deadline exceed bscause parent node entry-xbr75 deadline exceed
0e99f0da-b642-4969-986a-97965e582b82,experiments,workflow-pod-kill-1,Workflow,2025-10-17T11:25:22Z,Normal,WorkflowAccomplished,workflow accomplished
286b926f-1d15-47b8-9d75-69e016f8cd2e,experiments,entry-xbr75,WorkflowNode,2025-10-17T11:25:22Z,Normal,NodeDeadlineExceed,deadline exceed
d3921a9e-ab02-4acc-9383-c330337ed87d,experiments,pod-kill-0-kv5cm-ljr9c,PodChaos,2025-10-17T11:20:22Z,Normal,Updated,Successfully update records of resource
d3921a9e-ab02-4acc-9383-c330337ed87d,experiments,pod-kill-0-kv5cm-ljr9c,PodChaos,2025-10-17T11:20:22Z,Normal,Applied,Successfully apply chaos for default/my-app-58797dc8d5-4splv
d3921a9e-ab02-4acc-9383-c330337ed87d,experiments,pod-kill-0-kv5cm-ljr9c,PodChaos,2025-10-17T11:20:22Z,Normal,Updated,Successfully update desiredPhase of resource
d3921a9e-ab02-4acc-9383-c330337ed87d,experiments,pod-kill-0-kv5cm-ljr9c,PodChaos,2025-10-17T11:20:22Z,Normal,Updated,Successfully update finalizer of resource
d3921a9e-ab02-4acc-9383-c330337ed87d,experiments,pod-kill-0-kv5cm-ljr9c,PodChaos,2025-10-17T11:20:22Z,Normal,FinalizerInited,Finalizer has been inited
504871ed-9aac-4ff2-afb4-19355f5e2faa,experiments,pod-kill-0-kv5cm,WorkflowNode,2025-10-17T11:20:22Z,Normal,ChaosCRCreated,chaos CR pod-kill-0-kv5cm-ljr9c created
286b926f-1d15-47b8-9d75-69e016f8cd2e,experiments,entry-xbr75,WorkflowNode,2025-10-17T11:20:22Z,Normal,NodesCreated,"child nodes created, pod-kill-0-kv5cm"
0e99f0da-b642-4969-986a-97965e582b82,experiments,workflow-pod-kill-1,Workflow,2025-10-17T11:20:22Z,Normal,EntryCreated,"entry node created, entry node entry-xbr75"
```

I guess this is the same issue as #3345
