### ISSUE TITLE
[Bug]: The dashboard returns an exception when creating PhysicalMachineChaos related experiments from yaml

### ISSUE THREAD

**Issue by boxker** [chaos-mesh/chaos-mesh#4540]
### Chaos Mesh Version

v2.7.0

### Kubernetes Version

v1.28.5+k3s1

### Describe the bug

Hello, I used the experiment of creating PhysicalMachineChaos from yaml on the dashboard and it returned an exception. The exception is as follows: Unexpected Application Error!
Cannot read properties of undefined (reading 'filter')

![image](https://github.com/user-attachments/assets/6d739ca7-ebe5-4277-b339-70734c358f76)

```yaml
kind: PhysicalMachineChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-mesh
  name: phy-cpu-2
spec:
  action: stress-cpu
  address:
    - https://10.200.111.25:31768
  selector: {}
  mode: all
  stress-cpu:
    load: 50
    workers: 1
  duration: 60s
```
