### ISSUE TITLE
[Bug]: NetworkChaos delay times being passed as microseconds

### ISSUE THREAD

**Issue by andreyzher** [chaos-mesh/chaos-mesh#4545]
### Chaos Mesh Version

v2.7.0

### Kubernetes Version

v1.28.13

### Describe the bug

The latency and jitter values on Delay experiments appear to be passed with incorrect magnitude to `tc`.
When I apply the NetworkChaos as defined below, I see no effect when I curl from the "frontend" to the "backend" pod (status is marked as injected).
When I increase the latency x1000 (ie `50,000ms`), then I get the expected 50ms increase in latency (measured with `time curl ...`, from 0.025s to 0.075s)

```
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-50ms
  namespace: chaos-mesh
spec:
  action: delay
  mode: all
  direction: to
  selector:
    namespaces:
      - default
    labelSelectors:
      tier: frontend
  delay:
    latency: "50ms"
    correlation: "0"
  target:
    mode: all
    selector:
      namespaces:
        - default
      labelSelectors:
        tier: backend
  duration: "5m"
```

The generated `tc` command in the chaos-daemon pod log is `tc qdisc add dev eth0 root netem delay 50000`, which doesn't have the desired effect.
If I run either of the below 2 commands manually, then I get a ~50ms delay as expected:
```
tc qdisc add dev eth0 root netem delay 50ms
tc qdisc add dev eth0 root netem delay 50000000
```
