### ISSUE TITLE
[Feature]: 支持dns故障注入，解析为指定的ip

### ISSUE THREAD

**Issue by stanleylst** [chaos-mesh/chaos-mesh#4563]
### Feature request

chaos-mesh dns故障action只支持 random和error，但不支持指定value
但是 chaosblade有该功能，希望支持

### Proposed solution

chaosblade  yaml demo如下：
```yaml
apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: tamper-container-dns-by-id
spec:
  experiments:
    - scope: container
      target: network
      action: dns
      desc: "tamper container dns by id"
      matchers:
        - name: container-ids
          value:
            - "4b25f66580c4"
        - name: domain
          value: ["www.baidu.com"]
        - name: ip
          value: ["10.0.0.1"]
          # pod names
        - name: names
          value: ["frontend-d89756ff7-trsxf"]
          # or use pod labels
```

### Additional context

无
