### ISSUE TITLE
[Bug]: invalid spec for netem action, at least one is required from delay, loss, duplicate, corrupt

### ISSUE THREAD

**Issue by ashuels** [chaos-mesh/chaos-mesh#4571]
### Chaos Mesh Version

v2.7.0

### Kubernetes Version

v1.31.0

### Describe the bug

Creating a Network Attack experiment leads to following error:

```
Failed to apply chaos: failed to apply for pod ping/ping-a-8465f76895-dvw6c: invalid spec for netem action, at least one is required from delay, loss, duplicate, corrupt
```

This was the yaml file used
```yaml
kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: ping
  name: delay
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  selector:
    namespaces:
      - ping
  mode: all
  action: delay
  delay:
    latency: 10ms
    correlation: '100'
    jitter: 0ms
  direction: to
```
