### ISSUE TITLE
[Bug]: StressChaos CR: Memory Usage Fails to Reach Configured Value Despite Proper CR Setup

### ISSUE THREAD

**Issue by michaelberge8** [chaos-mesh/chaos-mesh#4585]
### Chaos Mesh Version

v2.6.3

### Kubernetes Version

v1.29.2

### Describe the bug

I am creating a StressChaos CR to perform artificial CPU and memory usage. I got the CPU stress to work, but I can't get memory to increase to the value I set it to in the CR.

Here's the CR I'm creating:
```
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-chaos
  namespace: chaos-mesh
spec:
  mode: one
  stressors:
    cpu:
      workers: 1
      load: 50
    memory:
      workers: 1
      size: "900MB"
  duration: '60s'
  selector:
    namespaces:
      - default
    expressionSelectors:
      - key: app
        operator: In
        values:
          - app-1
```

When I create the CR, I exec into the main container in the pod I am stressing (app: app-1), and use `top` to examine resources:
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                       
  29842 root      20   0   94852    480     52 S  49.2   0.0   0:04.66 stress-ng                     
  29836 root      20   0  703768   4136   1864 S   0.0   0.0   0:00.00 memStress                     
  29841 root      20   0 1582676 882868   1864 S   0.0   5.4   0:01.42 memStress
  ...
```

CPU usage from `stress-ng` is correct at 50%. But `memStress` is only utilizing around 5%, even though I have set the memory size to 900MB and the pod resource limit is 1024MB. If I increase the memory.size, the process crashes.

Anyone know what my issue is and how I can get memory stress working? Thanks.
