### ISSUE TITLE
[Bug]: Intervals for schedule type workflow do not work

### ISSUE THREAD

**Issue by bravosierrasierra** [chaos-mesh/chaos-mesh#4624]
### Chaos Mesh Version

v2.7.0

### Kubernetes Version

v1.29

### Describe the bug

Intervals for schedule type workflow do not work

If the interval is set as '@every 3m', then the error "error" will appear in the logs: "unsupported chaos type Workflow" and schedule will not create workflow. Just change shedule to '*/3 * * * *' and everything starts working.

For the PodChaos type, both options work.

Error details:
```
2025-02-21T11:43:06.944Z	ERROR	collector.schedule-collector.Schedule	collector/schedule_collector.go:63	failed to archive schedule	{"error": "unsupported chaos type Workflow", "errorVerbose": "unsupported chaos type Workflow\ngithub.com/chaos-mesh/chaos-mesh/pkg/dashboard/collector.(*ScheduleCollector).setUnarchivedSchedule\n\t/home/runner/work/chaos-mesh/chaos-mesh/pkg/dashboard/collector/schedule_collector.go:110\ngithub.com/chaos-mesh/chaos-mesh/pkg/dashboard/collector.(*ScheduleCollector).Reconcile\n\t/home/runner/work/chaos-mesh/chaos-mesh/pkg/dashboard/collector/schedule_collector.go:62\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598"}
```

This fails, because we use  "schedule: '@every 3m'":
```
---
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: schedule-issue
  namespace: chaos-podtato-kubectl
spec:
  schedule: '@every 3m'
  # schedule: '*/3 * * * *'
  startingDeadlineSeconds: 3
  concurrencyPolicy: Forbid
  historyLimit: 4
  type: Workflow
  workflow:
    entry: the-entry
    templates:
      - name: the-entry
        templateType: Serial
        deadline: 160s
        children:
          - pod-chaos
      - name: pod-chaos
        deadline: 60s
        templateType: PodChaos
        podChaos:
          action: pod-kill
          mode: fixed-percent
          value: "50"
          selector:
            namespaces:
              - chaos-podtato-kubectl
            labelSelectors:
              app: podtato-head
```

![Image](https://github.com/user-attachments/assets/3b3f6098-c834-437b-a84d-51379e233913)

Same, but "schedule: '*/3 * * * *'" works ok:

![Image](https://github.com/user-attachments/assets/5f90331a-5ff8-417d-8d3b-4a4b1985c7a4)
