### ISSUE TITLE
[Bug]: 选择 "加载自", ”配置文件“ 为 "物理机" 前端都报错

### ISSUE THREAD

**Issue by mingjiezxc** [chaos-mesh/chaos-mesh#4703]
### Chaos Mesh Version

v2.7.2

### Kubernetes Version

v1.31.5+k3s1

### Describe the bug

物理机配置无法使用 yaml
```text
Unexpected Application Error!
Cannot read properties of undefined (reading 'filter')
TypeError: Cannot read properties of undefined (reading 'filter')
    at vD (http://192.168.188.202:32317/static/js/main.022485b6.js:2:2059847)
    at na (http://192.168.188.202:32317/static/js/main.022485b6.js:2:1191856)
    at Ws (http://192.168.188.202:32317/static/js/main.022485b6.js:2:1244200)
    at El (http://192.168.188.202:32317/static/js/main.022485b6.js:2:1231446)
    at Cl (http://192.168.188.202:32317/static/js/main.022485b6.js:2:1231374)
    at Sl (http://192.168.188.202:32317/static/js/main.022485b6.js:2:1231237)
    at vl (http://192.168.188.202:32317/static/js/main.022485b6.js:2:1228203)
    at http://192.168.188.202:32317/static/js/main.022485b6.js:2:1177648
    at http://192.168.188.202:32317/static/js/main.022485b6.js:2:1291811
    at Ho (http://192.168.188.202:32317/static/js/main.022485b6.js:2:1177425)
```

**Comment by g1eny0ung** [comment]
这里可能是未适配的问题，我去试一下。

**Comment by mingjiezxc** [comment]
嗯，使用yaml , load form  物理机配置 都是相同的错误

![Image](https://github.com/user-attachments/assets/6e645f09-ee27-406e-a5b7-452d8ea85cc2)

![Image](https://github.com/user-attachments/assets/c77a957a-53bb-45ff-9aaf-8797804d18a0)

![Image](https://github.com/user-attachments/assets/2e8d8382-1e3a-4cf4-b839-984cdacd6711)

**Comment by g1eny0ung** [comment]
@mingjiezxc 我应该是找到问题所在了，有空了可以粘贴一份你出现问题的 yaml 到这里吗？我还想进一步测试一下。

**Comment by mingjiezxc** [comment]
好的。
```yaml
kind: PhysicalMachineChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: test-cpu-2
spec:
  action: stress-cpu
  address:
    - http://10.82.43.50:51031
  selector: {}
  mode: all
  uid: a40fa933-b860-461e-ae7c-e97a0e2605b9
  stress-cpu:
    load: 99
    workers: 1
  duration: 5m
```
