### ISSUE TITLE
[Bug]: Cannot apply HTTPChaos on outgoing HTTPS traffic from pod

### ISSUE THREAD

**Issue by mivasile** [chaos-mesh/chaos-mesh#4709]
### Chaos Mesh Version

master

### Kubernetes Version

v1.30.11

### Describe the bug

Hi, I have tried using the [TLS option](https://chaos-mesh.org/docs/simulate-http-chaos-on-kubernetes/#tls) of the HTTPChaos attack to inject some faults to traffic outgoing from my pod to external services, but couldn't do it.

I see that another issue with my exact problem is opened [here](https://github.com/chaos-mesh/chaos-tproxy/issues/65).

Do you plan to support injecting faults to HTTPS traffic or at least update the documentation accordingly? Thanks!

### To Reproduce
```
apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: test-http-server
spec:
  mode: all
  selector:
    labelSelectors:
      app: nginx
  target: Request
  port: 443
  abort: true
  tls:
    secretName: tls-secret
    secretNamespace: chaos-mesh
    certName: tls.crt
    keyName: tls.key
    caName: ca.crt
```
