### ISSUE TITLE
Application of network-delay-with-target-example.yaml file causes crashloopbackoff in controller-manager in chaosmesh

### ISSUE THREAD

**Issue by teachersun** [chaos-mesh/chaos-mesh#606]
The first step is to apply the network network-delay-with-target-example.yaml file
```
apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-example
  namespace: test
spec:
  action: delay
  mode: one
  selector:
    labelSelectors:
      "app.kubernetes.io/component": "cockroachdb"
    delay:
      latency: "90ms"
      correlation: "25"
      jitter: "90ms"
    direction: to
    target:
      selector:
        labelSelectors:
          "app.kubernetes.io/component": "cockroachdb"
        mode: one
    duration: "10s"
    scheduler:
      cron: "@every 15s"
```
kubectl apply -f network-delay-with-target-example.yaml 
The second step did not produce any chaotic action
```
Spec:
  Action:     delay
  Direction:  to
  Mode:       one
  Selector:
    Label Selectors:
      App . Kubernetes . Io / Component:  cockroachdb
    Namespaces:
      test
  Value:  
Status:
  Experiment:
  Phase:  
  Scheduler:
Events:  <none>
```
The log information of controller-manager is as follows 

```
"/var/run/secrets/kubernetes.io/serviceaccount"}],"livenessProbe":{"httpGet":{"path":"/health","port":"http","scheme":"HTTP"},"initialDelaySeconds":30,"timeoutSeconds":1,"periodSeconds":5,"successThreshold":1,"failureThreshold":3},"readinessProbe":{"httpGet":{"path":"/health?ready=1","port":"http","scheme":"HTTP"},"initialDelaySeconds":10,"timeoutSeconds":1,"periodSeconds":5,"successThreshold":1,"failureThreshold":2},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":60,"dnsPolicy":"ClusterFirst","serviceAccountName":"default","serviceAccount":"default","nodeName":"slave2","securityContext":{},"hostname":"my-release-cockroachdb-1","subdomain":"my-release-cockroachdb","affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"weight":100,"podAffinityTerm":{"labelSelector":{"matchLabels":{"app.kubernetes.io/component":"cockroachdb","app.kubernetes.io/instance":"my-release","app.kubernetes.io/name":"cockroachdb"}},"topologyKey":"kubernetes.io/hostname"}}]}},"schedulerName":"default-scheduler","tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"priority":0,"enableServiceLinks":true},"status":{"phase":"Running","conditions":[{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-06-09T02:34:35Z"},{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-06-09T02:34:49Z"},{"type":"ContainersReady","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-06-09T02:34:49Z"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-06-09T02:34:35Z"}],"hostIP":"20.20.20.5","podIP":"10.156.49.179","startTime":"2020-06-09T02:34:35Z","containerStatuses":[{"name":"db","state":{"running":{"startedAt":"2020-06-09T02:34:36Z"}},"lastState":{},"ready":true,"restartCount":0,"image":"cockroachdb/cockroach:v19.2.5","imageID":"docker-pullable://cockroachdb/cockroach@sha256:9abfdb8fa63d67b15c5cf11628259c8217c4651fd841666a559438aa76fa6912","containerID":"docker://d7ba96b9736ba58a2394953f31f3c77111c529169d4be32d77d88b8ac7abf042"}],"qosClass":"BestEffort"}}]}
2020-06-09T03:00:08.503Z	INFO	controllers.NetworkChaos	Try to apply netem on pod	{"reconciler": "networkchaos", "action": "netem", "namespace": "test", "name": "my-release-cockroachdb-1"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x132b0c6]

goroutine 476 [running]:
github.com/pingcap/chaos-mesh/api/v1alpha1.(*DelaySpec).ToNetem(0x0, 0x15561e0, 0x0, 0x18d5e20)
	/src/api/v1alpha1/networkchaos_types.go:307 +0x26
github.com/pingcap/chaos-mesh/controllers/networkchaos/netem.(*Reconciler).applyPod(0xc000370ed0, 0x190dce0, 0xc00020e000, 0xc000c65000, 0xc0001fcc80, 0xc0009471a0, 0xc0009471d0, 0x0, 0x0)
	/src/controllers/networkchaos/netem/types.go:270 +0x2f5
github.com/pingcap/chaos-mesh/controllers/networkchaos/netem.(*Reconciler).applyNetem.func1(0x482774, 0xc00050a040)
	/src/controllers/networkchaos/netem/types.go:367 +0xd0
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0003f48a0, 0xc000947170)

```

**Comment by yeya24** [comment]
I cannot reproduce this bug.
Is this the yaml you are using? Looks like there is an indentation problem. Could you please check it with the example here https://github.com/pingcap/chaos-mesh/blob/master/examples/network-delay-with-target-example.yaml?

``` yaml
apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-example
  namespace: test
spec:
  action: delay
  mode: one
  selector:
    labelSelectors:
      "app.kubernetes.io/component": "cockroachdb"
    delay:
      latency: "90ms"
      correlation: "25"
      jitter: "90ms"
    direction: to
    target:
      selector:
        labelSelectors:
          "app.kubernetes.io/component": "cockroachdb"
        mode: one
    duration: "10s"
    scheduler:
      cron: "@every 15s"
```
