### ISSUE TITLE
How to create PodChaos resources by using kubernates-python sdk

### ISSUE THREAD

**Issue by del-zhenwu** [chaos-mesh/chaos-mesh#714]
## Question
just as example shows, the pod spec: 
```
'''
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - test
    labelSelectors:
      "app": "tttt-mysql"
  scheduler:
    cron: "@every 30s"
'''

```
I can create pod resource by executing cmd: `kubectl apply -f **.yaml`
How can I create this custom resource by sdk(kubernates-python), `client.V1DeploymentSpec, client.AppsV1beta1Deployment` seems to be useless

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/chaos-mesh/chaos-mesh/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [Chaos Mesh Readme](https://github.com/chaos-mesh/chaos-mesh)
  - [Chaos Mesh Doc](https://github.com/chaos-mesh/chaos-mesh/tree/master/doc)
