### ISSUE TITLE
The stress-burn-cpu seems not working

### ISSUE THREAD

**Issue by del-zhenwu** [chaos-mesh/chaos-mesh#755]
## Question

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/chaos-mesh/chaos-mesh/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [Chaos Mesh Readme](https://github.com/chaos-mesh/chaos-mesh)
  - [Chaos Mesh Doc](https://github.com/chaos-mesh/chaos-mesh/tree/master/doc)

I'm testing StressChaos with the example yaml, it run successfully, but I found the CPU usage was not changed factually
(using `kubectl watch pod *` )
, what's the possible reason for this.
```
2020-07-30T04:00:23.009Z	INFO	chaos-daemon-server	running command	{"command": "nsenter -p/proc/11347/ns/pid -- stress-ng --cpu 2 --cpu-load 100"}
2020-07-30T04:00:23.009Z	INFO	chaos-daemon-server	Start process successfully
2020-07-30T04:00:53.001Z	INFO	chaos-daemon-server	Canceling stressors	{"request": "instance:\"10355\" startTime:1596081622000 "}
2020-07-30T04:00:53.005Z	INFO	chaos-daemon-server	killing children for nsenter	{"pid": 10356}
2020-07-30T04:00:53.005Z	INFO	chaos-daemon-server	Successfully canceled stressors
2020-07-30T04:00:53.006Z	INFO	chaos-daemon-server	Stressors cancelled	{"request": "scope:POD target:\"docker://3759c19a59c455bcedac07ba8d692fd3b129a2bdcb565d6bda06c7ce808dbb13\" stressors:\" --cpu 2 --cpu-load 100\" "}
2020-07-30T04:00:58.007Z	INFO	chaos-daemon-server	Executing stressors	{"request": "scope:POD target:\"docker://3759c19a59c455bcedac07ba8d692fd3b129a2bdcb565d6bda06c7ce808dbb13\" stressors:\" --cpu 2 --cpu-load 100\" "}
2020-07-30T04:00:58.010Z	INFO	chaos-daemon-server	running command	{"command": "nsenter -p/proc/11347/ns/pid -- stress-ng --cpu 2 --cpu-load 100"}
2020-07-30T04:00:58.011Z	INFO	chaos-daemon-server	Start process successfully
2020-07-30T04:01:28.005Z	INFO	chaos-daemon-server	Canceling stressors	{"request": "instance:\"11263\" startTime:1596081657000 "}
2020-07-30T04:01:28.010Z	INFO	chaos-daemon-server	killing children for nsenter	{"pid": 11264}
2020-07-30T04:01:28.010Z	INFO	chaos-daemon-server	Successfully canceled stressors
2020-07-30T04:01:28.010Z	INFO	chaos-daemon-server	Stressors cancelled	{"request": "scope:POD target:\"docker://3759c19a59c455bcedac07ba8d692fd3b129a2bdcb565d6bda06c7ce808dbb13\" stressors:\" --cpu 2 --cpu-load 100\" "}
2020-07-30T04:01:33.002Z	INFO	chaos-daemon-server	Executing stressors	{"request": "scope:POD target:\"docker://3759c19a59c455bcedac07ba8d692fd3b129a2bdcb565d6bda06c7ce808dbb13\" stressors:\" --cpu 2 --cpu-load 100\" "}
2020-07-30T04:01:33.003Z	INFO	chaos-daemon-server	running command	{"command": "nsenter -p/proc/11347/ns/pid -- stress-ng --cpu 2 --cpu-load 100"}
```
And no errors found in the logs on controller

**Comment by zhouqiang-cl** [comment]
@AngleNet @YangKeao PTAL

**Comment by YangKeao** [comment]
What's is `kubectl watch`?

**Comment by del-zhenwu** [comment]
> What is `kubectl watch`?

It's a mistake, cmd is: `watch kubectl top pod `

**Comment by YangKeao** [comment]
I guess that's because `StressChaos` starts in podwise cgroup in default. For example:

The cgroup file for `stress-ng` is 
```
11:pids:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fbfdfe6_00a9_4c6f_95cb_882ed1059fa0.slice
10:perf_event:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fbfdfe6_00a9_4c6f_95cb_882ed1059fa0.slice
9:cpuset:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fbfdfe6_00a9_4c6f_95cb_882ed1059fa0.slice
8:devices:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod3041ed04_c0cb_40f7_acd6_4bedd79d4552.slice/docker-a0c7a85576fdd627123ccdc78201e4963d41ba0628d2e73763b22988451d6cd1.scope
7:blkio:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod3041ed04_c0cb_40f7_acd6_4bedd79d4552.slice/docker-a0c7a85576fdd627123ccdc78201e4963d41ba0628d2e73763b22988451d6cd1.scope
6:freezer:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fbfdfe6_00a9_4c6f_95cb_882ed1059fa0.slice
5:cpu,cpuacct:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fbfdfe6_00a9_4c6f_95cb_882ed1059fa0.slice
4:memory:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod3041ed04_c0cb_40f7_acd6_4bedd79d4552.slice/docker-a0c7a85576fdd627123ccdc78201e4963d41ba0628d2e73763b22988451d6cd1.scope
3:hugetlb:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod3041ed04_c0cb_40f7_acd6_4bedd79d4552.slice/docker-a0c7a85576fdd627123ccdc78201e4963d41ba0628d2e73763b22988451d6cd1.scope
2:net_cls,net_prio:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fbfdfe6_00a9_4c6f_95cb_882ed1059fa0.slice
1:name=systemd:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fbfdfe6_00a9_4c6f_95cb_882ed1059fa0.slice
```

The cgroup file for docker is:

```
11:pids:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fbfdfe6_00a9_4c6f_95cb_882ed1059fa0.slice/docker-ad51293e946160e17ec29bb696b18df44581107e39ed050bab7225ed9e85ef41.scope
10:perf_event:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fbfdfe6_00a9_4c6f_95cb_882ed1059fa0.slice/docker-ad51293e946160e17ec29bb696b18df44581107e39ed050bab7225ed9e85ef41.scope
9:cpuset:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fbfdfe6_00a9_4c6f_95cb_882ed1059fa0.slice/docker-ad51293e946160e17ec29bb696b18df44581107e39ed050bab7225ed9e85ef41.scope
8:devices:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fbfdfe6_00a9_4c6f_95cb_882ed1059fa0.slice/docker-ad51293e946160e17ec29bb696b18df44581107e39ed050bab7225ed9e85ef41.scope
7:blkio:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fbfdfe6_00a9_4c6f_95cb_882ed1059fa0.slice/docker-ad51293e946160e17ec29bb696b18df44581107e39ed050bab7225ed9e85ef41.scope
6:freezer:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fbfdfe6_00a9_4c6f_95cb_882ed1059fa0.slice/docker-ad51293e946160e17ec29bb696b18df44581107e39ed050bab7225ed9e85ef41.scope
5:cpu,cpuacct:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fbfdfe6_00a9_4c6f_95cb_882ed1059fa0.slice/docker-ad51293e946160e17ec29bb696b18df44581107e39ed050bab7225ed9e85ef41.scope
4:memory:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fbfdfe6_00a9_4c6f_95cb_882ed1059fa0.slice/docker-ad51293e946160e17ec29bb696b18df44581107e39ed050bab7225ed9e85ef41.scope
3:hugetlb:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fbfdfe6_00a9_4c6f_95cb_882ed1059fa0.slice/docker-ad51293e946160e17ec29bb696b18df44581107e39ed050bab7225ed9e85ef41.scope
2:net_cls,net_prio:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fbfdfe6_00a9_4c6f_95cb_882ed1059fa0.slice/docker-ad51293e946160e17ec29bb696b18df44581107e39ed050bab7225ed9e85ef41.scope
1:name=systemd:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0fbfdfe6_00a9_4c6f_95cb_882ed1059fa0.slice/docker-ad51293e946160e17ec29bb696b18df44581107e39ed050bab7225ed9e85ef41.scope
```

But the metric-server (actually `kubelet`) collects metrics per container, so the `kubectl watch pod` won't show the high cpu usage. 

Should we add a flag to switch pod-wise injection or container-wise injection? What's your opinion?

@AngleNet  @cwen0 PTAL

**Comment by YangKeao** [comment]
Related codes are [here](https://github.com/chaos-mesh/chaos-mesh/blob/64522bfbdd9e49a4b3e8e515f489d87003966d9c/controllers/stresschaos/types.go#L248-L252)

```
res, err := daemonClient.ExecStressors(ctx, &pb.ExecStressRequest{
	Scope:     pb.ExecStressRequest_POD,
	Target:    target,
	Stressors: stressors,
})
```

@cwen0 Is there any benefit to inject stress in pod scope? If not, maybe we should use `ExecStressRequest_CONTAINER`

**Comment by YangKeao** [comment]
Maybe we should also support injecting stress for a single container, as Kubernetes supports resource limitation per container.

**Comment by cwen0** [comment]
> Maybe we should also support injecting stress for a single container, as Kubernetes supports resource limitation per container.

Yes, a flag to switch pod-wise injection or container-wise injection is necessary and we also need to support setting the specific container

**Comment by del-zhenwu** [comment]
So how to stress to the given container currently?

**Comment by zhouqiang-cl** [comment]
> So how to stress to the given container currently?

We are now fixing it, about 1 hour later it will be fixed

**Comment by zhouqiang-cl** [comment]
@del-zhenwu Fixed. can you update chaos-mesh and test it again?

**Comment by del-zhenwu** [comment]
> @del-zhenwu Fixed. can you update chaos-mesh and test it again?

yes, this has been fixed.

**Comment by del-zhenwu** [comment]
My app has been limited to run with 2-cpus, after applying chaos-stress-cpu(ex, 2-workers), There are 3 stress-ng processes running on the container, 2 of them use 100% cpu. If I run my-app and use full of cpus, there would be 400% cpu usage on the container, which is not expected. Any advices can you provide?

**Comment by YangKeao** [comment]
> My app has been limited to run with 2-cpus, after applying chaos-stress-cpu(ex, 2-workers), There are 3 stress-ng processes running on the container, 2 of them use 100% cpu. If I run my-app and use full of cpus, there would be 400% cpu usage on the container, which is not expected. Any advices can you provide? How to do chaos-stress, to make sure the stress-ng processes will occupy the cpu resources which my-app used

I cannot reproduce this bug. A pod (running `stress-ng --cpu 1`) limited with 1 cpu was injected stress chaos cpu (with `--cpu 4`), and the full cpu usage of this container is still around `1000m` but not `2000m` or `5000m`.

```
ubuntu-fdbd8949b-gr72n     1003m        9Mi
```

The deployment file:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu 
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        imagePullPolicy: Never
        image: ubuntu-debug
        args: ["stress-ng", "--cpu", "1", "--cpu-load", "100"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "1"
          limits:
            memory: "128Mi"
            cpu: "1"
```

Do you have any idea on how to reproduce the problems?

**Comment by del-zhenwu** [comment]
I specified `containerName` in yaml, does it make a difference?

**Comment by YangKeao** [comment]
> I specified `containerName` in stress-yaml, does it make a difference? And there are two containers in my pod, one of the containers has been stressed

No difference.  My StressChaos yaml file is :

```
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: burn-cpu
spec:
  mode: all
  selector:
    labelSelectors:
      "app": "ubuntu"
  stressors: 
    cpu: 
      workers: 1
      load: 100
      options: ["--cpu 4", "--timeout 600"]
  containerName: "ubuntu"
  duration: "60s"
  scheduler:
    cron: "@every 65s"
```

To verify whether the cgroup is set successfully, you can check the cgroup of these processes (include stress-ng)  in procfs.

```
kubectl exec -it my-app /bin/sh

# in kubectl exec
# this file is the cgroup config for your application
cat /proc/1/cgroup 
# this file is the cgroup config for stress-ng
cat /proc/$(pgrep stress-ng)/cgroup
```

The content of these files should be the same. And you can check whether the `cfs_quote_us` and `cfs_period_us` are set for this cgroup.

```
kubectl exec -n chaos-testing -it chaos-daemon /bin/sh

# replace the cgroup directory with the name found in /proc/1/cgroup file
cat /sys/fs/cgroup/cpu,cpuacct/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod1b9c33a5_e968_4ee0_ab76_d751c48e7844.slice/docker-c15717e10f6724456691164bff29e91e7172c1f86acae88c9816c7846446e960.scope/cpu.cfs_quota_us
cat /sys/fs/cgroup/cpu,cpuacct/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod1b9c33a5_e968_4ee0_ab76_d751c48e7844.slice/docker-c15717e10f6724456691164bff29e91e7172c1f86acae88c9816c7846446e960.scope/cpu.cfs_period_us
# `cpu.cfs_quota_us` / `cpu.cfs_period_us` should equal with your settings in kubernetes resources limitation
```

**Comment by del-zhenwu** [comment]
I test almost the same config.
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                
  163 root      20   0   27532   3580    724 R 100.0  0.0   0:07.37 stress-ng-cpu                                                                                                          
  165 root      20   0   27532   3580    720 R 100.0  0.0   0:07.34 stress-ng-cpu                                                                                                          
  164 root      20   0   27532   3580    716 R 100.0  0.0   0:07.36 stress-ng-cpu                                                                                                          
  162 root      20   0   27532   3580    716 R  99.0  0.0   0:07.33 stress-ng-cpu                                                                                                          
  161 root      20   0   27532   3580    716 R  98.7  0.0   0:07.33 stress-ng-cpu  
```
```
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: burn-cpu
  namespace: chaos-testing
spec:
  mode: one
  containerName: a
  selector:
    labelSelectors:
      "app.kubernetes.io/instance": "test-a"
    namespaces:
      - milvus
  stressors:
    cpu:
      workers: 1
      load: 100
      options: ["--cpu 4", "--timeout 600"]
  duration: "30s"
  scheduler:
    cron: "@every 35s"
```

**Comment by cwen0** [comment]
> My app has been limited to run with 2-cpus, after applying chaos-stress-cpu(ex, 2-workers), There are 3 stress-ng processes running on the container, 2 of them use 100% cpu. If I run my-app and use full of cpus, there would be 400% cpu usage on the container, which is not expected. Any advices can you provide? How to do chaos-stress, to make sure the stress-ng processes will occupy the cpu resources which my-app used

@del-zhenwu I also didn't reproduce this issue. Can you check if `limits` fields of application container is defined in the application configuration, like this: 

```yaml
          limits. 
            cpu: 2000m
            memory: 2560Mi
``` 
In addition, If you have defined  `workers`  field in chaos experiment, `options: ["--cpu 4", "--timeout 600"]` is not necessary.

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: burn-cpu
  namespace: chaos-testing
spec:
  mode: one
  containerName: a
  selector:
    labelSelectors:
      "app.kubernetes.io/instance": "test-a"
    namespaces:
      - milvus
  stressors:
    cpu:
      workers: 4
      load: 100
  duration: "30s"
  scheduler:
    cron: "@every 35s"
```

**Comment by del-zhenwu** [comment]
Yes, I have checked the config using cmd `kubectl describe pod`, 
```
    Limits:
      cpu:     4
      memory:  12Gi
    Requests:
      cpu:        2
      memory:     8Gi
```
still occupy other cpus, not sharing the limited cpus.
```

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                
    1 root      20   0 2137532 123540   9264 S 372.0  0.4  14:59.77 milvus_server                                                                                                          
 9870 root      20   0   27536   3580    720 R  86.7  0.0   0:23.06 stress-ng-cpu                                                                                                          
 9868 root      20   0   27536   3580    716 R  85.0  0.0   0:22.42 stress-ng-cpu                                                                                                          
 9867 root      20   0   27536   3580    720 R  84.7  0.0   0:22.35 stress-ng-cpu                                                                                                          
 9869 root      20   0   27536   3580    720 R  83.0  0.0   0:22.30 stress-ng-cpu                                                                                                          
 9866 root      20   0   27536   3580    716 R  79.7  0.0   0:22.80 stress-ng-cpu                                                                                                          
 9871 root      20   0   27536   3580    716 R  71.0  0.0   0:21.82 stress-ng-cpu    
```
yaml:
```
  containerName: milvus
  selector:
    labelSelectors:
      "app.kubernetes.io/instance": "test"
    namespaces:
      - milvus
  stressors:
    cpu:
      workers: 6
      load: 100
```
