### ISSUE TITLE
Chaos Mesh not recover after some failuer

### ISSUE THREAD

**Issue by zhouqiang-cl** [chaos-mesh/chaos-mesh#756]
## Bug Report

**What version of Kubernetes are you using?**

<img width="1778" alt="截屏2020-07-30 下午2 08 53" src="https://user-images.githubusercontent.com/23521459/88887111-602cb680-d26e-11ea-9904-b1dff66ac6cc.png">

yaml file is here
```
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition
  namespace: dgraph-chaos
spec:
  action: partition
  mode: one
  selector:
    labelSelectors:
      "component": "alpha"
  direction: to
  target:
    selector:
      labelSelectors:
        "component": "zero"
    mode: one
  duration: "30s"
  scheduler:
    cron: "@every 2m"
```
