### ISSUE TITLE
pod-failure action didn't work on dgraph pod

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#757]
## Bug Report

**What version of Kubernetes are you using?**
 

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-02-07T01:05:17Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**
  

Apply `pod-failure` action to graph pod 

```
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-alpha
  namespace: dgraph-chaos
spec:
  action: pod-failure
  mode: one
  selector:
    labelSelectors:
      "component": "alpha"
```

**What did you expect to see?**  

![image](https://user-images.githubusercontent.com/22956341/88897880-92deab00-d27e-11ea-9e61-70d141749af4.png)

**What did you see instead?**

![image](https://user-images.githubusercontent.com/22956341/88897919-a12cc700-d27e-11ea-811c-f192d2dc80d9.png)
